using System.Diagnostics.CodeAnalysis;
using Fdw.Abstractions;
using Fdw.Collections;

namespace Fdw.Services.Authorization;

/// <summary>
/// ServiceTypeCollection for authorization service types.
/// Generated by ServiceTypeCollectionGenerator with high-performance lookups.
/// </summary>
[ExcludeFromCodeCoverage]
[ServiceTypeCollection(
    typeof(AuthorizationTypeBase<IGenericService, IAuthorizationFactory>),
    typeof(IAuthorizationType),
    typeof(AuthorizationServiceTypes),
    ServiceCategory = "Authorization")]
public partial class AuthorizationServiceTypes : ServiceTypeCollectionBase<
    AuthorizationTypeBase<IGenericService, IAuthorizationFactory>,
    IAuthorizationType>
{
    /// <summary>
    /// The connection this domain's configuration rows are read from and written to.
    /// </summary>
    public static string ConfigurationConnection { get; set; } = "PlatformConfiguration";

}
