using System.Diagnostics.CodeAnalysis;
using Fdw.Abstractions;
using Fdw.Collections;

namespace Fdw.Services.Authorization;

/// <summary>
/// ServiceTypeCollection for authorization service types.
/// Generated by ServiceTypeCollectionGenerator with high-performance lookups.
/// </summary>
[ExcludeFromCodeCoverage]
[ServiceTypeCollection(
    typeof(AuthorizationTypeBase<IGenericService, IAuthorizationFactory>),
    typeof(IAuthorizationType),
    typeof(AuthorizationTypes),
    ServiceCategory = "Authorization")]
public partial class AuthorizationTypes : ServiceTypeCollectionBase<
    AuthorizationTypeBase<IGenericService, IAuthorizationFactory>,
    IAuthorizationType>
{
}
