using System.Diagnostics.CodeAnalysis;
using Fdw.Collections;
using Fdw.Services;
using Fdw.Services.Abstractions;
using Fdw.ServiceTypes;
using Fdw.Services.DataVault.Abstractions;
using Fdw.ServiceTypes.Logging;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Logging.Abstractions;
using System;
using System.Linq;
using Fdw.Results;
using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.DependencyInjection.Extensions;
using Fdw.Services.Configuration;
using Fdw.Configuration;
using Fdw.Services.Data.Abstractions;

namespace Fdw.Services.DataVault;

/// <summary>
/// Collection of data vault service types.
/// Generated by ServiceTypeCollectionGenerator with high-performance lookups.
/// </summary>
[ExcludeFromCodeCoverage]
[ServiceTypeCollection(
    typeof(DataVaultTypeBase<IDataVault, IDataVaultFactory<IDataVault, IDataVaultImplementationConfiguration>, IDataVaultImplementationConfiguration>),
    typeof(IDataVaultType),
    typeof(DataVaultTypes),
    ServiceInterface = typeof(IDataVault),
    ProviderType = typeof(DataVaultProvider),
    ProviderInterface = typeof(IDataVaultProvider),
    ServiceCategory = "DataVault")]
public partial class DataVaultTypes : ServiceTypeCollectionBase<
    DataVaultTypeBase<IDataVault, IDataVaultFactory<IDataVault, IDataVaultImplementationConfiguration>, IDataVaultImplementationConfiguration>,
    IDataVaultType<IDataVault, IDataVaultFactory<IDataVault, IDataVaultImplementationConfiguration>, IDataVaultImplementationConfiguration>>
{
    /// <summary>
    /// The connection this domain's configuration rows are read from and written to.
    /// </summary>
    public static string ConfigurationConnection { get; set; } = "PlatformConfiguration";

    // Configure(), Register() and Initialize() are source-generated

    /// <summary>
    /// Sets this collection's Register body: the option collect, then this domain's provider.
    /// </summary>
    /// <remarks>
    /// The provider is one registration for the whole collection and this declaration already names it,
    /// so the body that registers it is written here beside the declaration. Setting it as the phase's
    /// body is what makes it replaceable: an application calling <c>Registration(...)</c> replaces the
    /// collect and this registration together, which is the correct semantic for a host taking over phase 2.
    /// </remarks>
    static DataVaultTypes()
    {
        var collectOptions = RegisterFunc;

        var providerService = typeof(IDataVaultProvider).ToString();

        Registration((builder, loggerFactory) =>
        {
            var log = loggerFactory?.CreateLogger<DataVaultTypes>() ?? NullLogger<DataVaultTypes>.Instance;

            var registered = collectOptions(builder, loggerFactory);
            if (registered.IsFailure)
                return registered;

            // The configuration provider for this domain, registered once here rather than by every
            // caller that happens to need it.
            builder.Services.TryAddSingleton<IDataVaultConfigurationProvider>(sp =>
                new DataVaultConfigurationProvider(
                    sp.GetService<ILogger<DataVaultConfigurationProvider>>()!,
                    sp.GetRequiredService<IConfigurationGatewayProvider>(),
                    ConfigurationConnection));
            builder.Services.TryAddSingleton<DataVaultConfigurationProvider>(
                sp => (DataVaultConfigurationProvider)sp.GetRequiredService<IDataVaultConfigurationProvider>());

            builder.Services.TryAddSingleton<ImplementationConfigurationProviderBase<DataVaultConfiguration, DataVaultConfigurationCommand>>(
                sp => sp.GetRequiredService<DataVaultConfigurationProvider>());

            builder.Services.TryAddSingleton<IServiceConfigurationProvider<DataVaultConfiguration>>(
                sp => sp.GetRequiredService<DataVaultConfigurationProvider>());

            var declaredOptions = Options;
            var optionNames = string.Join(", ", declaredOptions.Select(option => option.Name));

            ServiceTypeLog.DomainOptionsCollected(log, nameof(DataVaultTypes), declaredOptions.Length, optionNames);
            ServiceTypeLog.DomainProviderDeclared(log, nameof(DataVaultTypes), providerService);

            builder.Services.AddScoped<IDataVaultProvider>(sp =>
            {
                var provider = new DataVaultProvider(
                    sp,
                    sp.GetService<ILoggerFactory>()?.CreateLogger<DataVaultProvider>()
                    ?? NullLogger<DataVaultProvider>.Instance);

                var stLogger = sp.GetService<ILoggerFactory>()?.CreateLogger<DataVaultTypes>()
                    ?? NullLogger<DataVaultTypes>.Instance;
                ServiceTypeLog.DomainProviderConstructing(stLogger, nameof(DataVaultTypes), provider.GetType().Name);
                try
                {
                    if (sp.GetService<IDataVaultConfigurationProvider>() is { } cfgProvider)
                    {
                        var domainResult = provider.Register(cfgProvider);
                        if (domainResult.IsSuccess)
                            ServiceTypeLog.DomainConfigurationSourceAttached(stLogger, nameof(DataVaultTypes), provider.GetType().Name, cfgProvider.GetType().Name);
                        else
                            ServiceTypeLog.DomainConfigurationSourceRejected(stLogger, nameof(DataVaultTypes), provider.GetType().Name, cfgProvider.GetType().Name, domainResult.CurrentMessage);
                    }
                    else
                    {
                        ServiceTypeLog.DomainHasNoConfigurationSource(
                            stLogger,
                            nameof(DataVaultTypes),
                            provider.GetType().Name,
                            typeof(IServiceConfigurationProvider<DataVaultConfiguration>).ToString());
                    }
                }
                catch (Exception ex)
                {
                    ServiceTypeLog.FactoryRegistrationException(stLogger, ex, nameof(DataVaultTypes));
                    throw;
                }
                return provider;
            });

            if (declaredOptions.Length == 0)
                ServiceTypeLog.DomainRegisteredWithNoOptions(log, nameof(DataVaultTypes), providerService);
            else
                ServiceTypeLog.DomainRegistered(log, nameof(DataVaultTypes), declaredOptions.Length, optionNames, providerService);

            return GenericResult<IHostApplicationBuilder>.Success(builder);
        });
    }
}
