using System.Diagnostics.CodeAnalysis;
using Fdw.Collections;
using Fdw.Services;
using Fdw.Services.Abstractions;
using Fdw.ServiceTypes;
using Fdw.Services.DataVault.Abstractions;
using Fdw.ServiceTypes.Logging;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Logging.Abstractions;
using System;
using System.Linq;
using Fdw.Results;
using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.DependencyInjection.Extensions;
using Fdw.Services.Configuration;
using Fdw.Configuration;
using Fdw.Services.Data.Abstractions;

namespace Fdw.Services.DataVault;

/// <summary>
/// Collection of data vault service types.
/// Generated by ServiceTypeCollectionGenerator with high-performance lookups.
/// </summary>
[ExcludeFromCodeCoverage]
[ServiceTypeCollection(
    typeof(DataVaultTypeBase<IDataVault, IDataVaultFactory<IDataVault, IDataVaultImplementationConfiguration>, IDataVaultImplementationConfiguration>),
    typeof(IDataVaultType),
    typeof(DataVaultServiceTypes),
    ServiceInterface = typeof(IDataVault),
    ProviderType = typeof(DataVaultProvider),
    ProviderInterface = typeof(IDataVaultProvider),
    ServiceCategory = "DataVault")]
public partial class DataVaultServiceTypes : ServiceTypeCollectionBase<
    DataVaultTypeBase<IDataVault, IDataVaultFactory<IDataVault, IDataVaultImplementationConfiguration>, IDataVaultImplementationConfiguration>,
    IDataVaultType<IDataVault, IDataVaultFactory<IDataVault, IDataVaultImplementationConfiguration>, IDataVaultImplementationConfiguration>>
{
    /// <summary>
    /// The connection this domain's configuration rows are read from and written to.
    /// </summary>
    public static string ConfigurationConnection { get; set; } = "PlatformConfiguration";

    // Configure(), Register() and Initialize() are source-generated

    /// <summary>
    /// Sets this collection's Register body: the option collect, then this domain's provider.
    /// </summary>
    /// <remarks>
    /// The provider is one registration for the whole collection and this declaration already names it,
    /// so the body that registers it is written here beside the declaration. Setting it as the phase's
    /// body is what makes it replaceable: an application calling <c>Registration(...)</c> replaces the
    /// collect and this registration together, which is the correct semantic for a host taking over phase 2.
    /// </remarks>
    static DataVaultServiceTypes()
    {
        var collectOptions = RegisterFunc;

        // Why a local: this closed generic is the DI key a consumer injects, and it is reported at
        // three points below — the deferred declaration, the milestone, and the zero-option warning.
        // Written out three times it is three chances for them to disagree.
        var providerService = typeof(IDataVaultProvider).ToString();

        Registration((builder, loggerFactory) =>
        {
            var log = loggerFactory?.CreateLogger<DataVaultServiceTypes>() ?? NullLogger<DataVaultServiceTypes>.Instance;

            // Why the result is read: this replacement calls the func it captured, and discarding
            // what that returned meant an option that failed to register was followed by this body
            // registering the provider anyway and reporting success.
            var registered = collectOptions(builder, loggerFactory);
            if (registered.IsFailure)
                return registered;

            // The configuration provider for this domain, registered once here rather than by every
            // caller that happens to need it.
            // Why the domain interface and not only the concrete class: this collection resolves
            // IDataVaultConfigurationProvider to attach it to the domain provider, and a registration
            // of the concrete type alone leaves that lookup empty — the domain then fails every
            // lookup by name for the life of the scope. ConfigurationConnection is the one place that
            // names which store these rows live in.
            builder.Services.TryAddSingleton<IDataVaultConfigurationProvider>(sp =>
                new DataVaultConfigurationProvider(
                    sp.GetService<ILogger<DataVaultConfigurationProvider>>()!,
                    sp.GetRequiredService<Lazy<IConfigurationGateway>>(),
                    ConfigurationConnection));
            builder.Services.TryAddSingleton<DataVaultConfigurationProvider>(
                sp => (DataVaultConfigurationProvider)sp.GetRequiredService<IDataVaultConfigurationProvider>());

            // Why: consumers inject ImplementationConfigurationProviderBase<TConfig, TCommand> — forward to the
            // concrete subclass so injection by base type succeeds.
            builder.Services.TryAddSingleton<ImplementationConfigurationProviderBase<DataVaultConfiguration, DataVaultConfigurationCommand>>(
                sp => sp.GetRequiredService<DataVaultConfigurationProvider>());

            // Why: generated Initialize() links IServiceConfigurationProvider<T> as the parent on the
            // domain provider; this forward lets that lookup succeed.
            builder.Services.TryAddSingleton<IServiceConfigurationProvider<DataVaultConfiguration>>(
                sp => sp.GetRequiredService<DataVaultConfigurationProvider>());

            var declaredOptions = Options;
            var optionNames = string.Join(", ", declaredOptions.Select(option => option.Name));

            ServiceTypeLog.DomainOptionsCollected(log, nameof(DataVaultServiceTypes), declaredOptions.Length, optionNames);
            ServiceTypeLog.DomainProviderDeclared(log, nameof(DataVaultServiceTypes), providerService);

            builder.Services.AddScoped<IDataVaultProvider>(sp =>
            {
                var provider = new DataVaultProvider(
                    sp,
                    sp.GetService<ILoggerFactory>()?.CreateLogger<DataVaultProvider>()
                    ?? NullLogger<DataVaultProvider>.Instance);

                // Why ILogger<DataVaultServiceTypes> and not CreateLogger("DataVaultServiceTypes"): SourceContext then
                // carries the namespace-qualified collection, and the category cannot drift from the
                // type it claims to name. The provider logs its own lines under its own type, so the
                // two layers read base-then-derived rather than collapsing onto one category.
                var stLogger = sp.GetService<ILoggerFactory>()?.CreateLogger<DataVaultServiceTypes>()
                    ?? NullLogger<DataVaultServiceTypes>.Instance;
                ServiceTypeLog.DomainProviderConstructing(stLogger, nameof(DataVaultServiceTypes), provider.GetType().Name);
                try
                {
                    if (sp.GetService<IDataVaultConfigurationProvider>() is { } cfgProvider)
                    {
                        // Why the result is read: a provider that did not take its parent still constructs, and
                        // every later read silently misses. The failure has to be said out loud here or nowhere.
                        var domainResult = provider.Register(cfgProvider);
                        if (domainResult.IsSuccess)
                            ServiceTypeLog.DomainConfigurationSourceAttached(stLogger, nameof(DataVaultServiceTypes), provider.GetType().Name, cfgProvider.GetType().Name);
                        else
                            ServiceTypeLog.DomainConfigurationSourceRejected(stLogger, nameof(DataVaultServiceTypes), provider.GetType().Name, cfgProvider.GetType().Name, domainResult.CurrentMessage);
                    }
                    else
                    {
                        // Why Critical, and why the collection says it rather than the provider: from
                        // inside the provider a null parent is indistinguishable from a domain that needs
                        // none. This is the one place that knows one was meant to arrive, and without it
                        // the domain fails every lookup by name for the life of the scope with nothing
                        // pointing back here.
                        ServiceTypeLog.DomainHasNoConfigurationSource(
                            stLogger,
                            nameof(DataVaultServiceTypes),
                            provider.GetType().Name,
                            typeof(IServiceConfigurationProvider<DataVaultConfiguration>).ToString());
                    }
                }
                catch (Exception ex)
                {
                    // Why rethrow: a throw here was previously silent, and a provider that failed to take
                    // its parent is unusable in a way that only surfaces much later.
                    ServiceTypeLog.FactoryRegistrationException(stLogger, ex, nameof(DataVaultServiceTypes));
                    throw;
                }
                return provider;
            });

            // Why the milestone comes after the registration and not before: it states that the domain
            // finished phase 2, which is only true once the provider is actually in the container.
            if (declaredOptions.Length == 0)
                ServiceTypeLog.DomainRegisteredWithNoOptions(log, nameof(DataVaultServiceTypes), providerService);
            else
                ServiceTypeLog.DomainRegistered(log, nameof(DataVaultServiceTypes), declaredOptions.Length, optionNames, providerService);

            return GenericResult<IHostApplicationBuilder>.Success(builder);
        });
    }
}
