using System;
using System.Collections.Immutable;
using System.Linq;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Fdw.Configuration.UI.SourceGenerators.Analysis;
using Fdw.Configuration.UI.SourceGenerators.Generators;
using Fdw.Configuration.UI.SourceGenerators.Models;

namespace Fdw.Configuration.UI.SourceGenerators;

/// <summary>
/// Incremental source generator that creates Web, Blazor, and TUI components
/// for classes annotated with [ManagedConfiguration].
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class ConfigurationUISourceGenerator : IIncrementalGenerator
{
    private const string ManagedConfigurationAttribute = "Fdw.Configuration.ManagedConfigurationAttribute";

    /// <summary>
    /// Initializes the incremental generator.
    /// </summary>
    /// <param name="context">The initialization context.</param>
    // MA0051: Method length acceptable - generator initialization registers 4 separate outputs (Web/Blazor/TUI/FormModel)
#pragma warning disable MA0051 // Method is too long
    public void Initialize(IncrementalGeneratorInitializationContext context)
#pragma warning restore MA0051
    {
#if DEBUG
        // DEBUG: Always create a debug file to show the generator is being loaded
        context.RegisterPostInitializationOutput(static context =>
        {
            context.AddSource("ConfigurationUISourceGenerator.Init.g.cs", @"// <auto-generated/>
// ConfigurationUISourceGenerator is loaded and running
");
        });
#endif

        // Find all classes with [ManagedConfiguration] attribute
        var configurationClasses = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                ManagedConfigurationAttribute,
                predicate: static (node, _) => node is ClassDeclarationSyntax,
                transform: static (context, _) => GetConfigurationModel(context))
            .Where(static model => model != null);

        // Register Web component generation (only if GenerateWeb is true)
        context.RegisterSourceOutput(
            configurationClasses,
            static (context, model) =>
            {
                if (model == null || !model.GenerateWeb) return;

                try
                {
                    var source = WebComponentGenerator.Generate(model);
                    context.AddSource($"{model.ClassName}.Web.g.cs", source);
                }
                catch (Exception ex)
                {
                    // Report diagnostic for generation errors
                    var diagnostic = Diagnostic.Create(
                        new DiagnosticDescriptor(
                            "CFGUI001",
                            "Web Component Generation Failed",
                            "Failed to generate Web component for {0}: {1}",
                            "ConfigurationUI.SourceGenerator",
                            DiagnosticSeverity.Error,
                            isEnabledByDefault: true),
                        Location.None,
                        model.ClassName,
                        ex.Message);
                    context.ReportDiagnostic(diagnostic);
                }
            });

        // Register Blazor component generation (only if GenerateBlazor is true)
        context.RegisterSourceOutput(
            configurationClasses,
            static (context, model) =>
            {
                if (model == null || !model.GenerateBlazor) return;

                try
                {
                    var source = BlazorComponentGenerator.Generate(model);
                    context.AddSource($"{model.ClassName}.Blazor.g.cs", source);
                }
                catch (Exception ex)
                {
                    // Report diagnostic for generation errors
                    var diagnostic = Diagnostic.Create(
                        new DiagnosticDescriptor(
                            "CFGUI002",
                            "Blazor Component Generation Failed",
                            "Failed to generate Blazor component for {0}: {1}",
                            "ConfigurationUI.SourceGenerator",
                            DiagnosticSeverity.Error,
                            isEnabledByDefault: true),
                        Location.None,
                        model.ClassName,
                        ex.Message);
                    context.ReportDiagnostic(diagnostic);
                }
            });

        // Register TUI component generation (only if GenerateTui is true)
        context.RegisterSourceOutput(
            configurationClasses,
            static (context, model) =>
            {
                if (model == null || !model.GenerateTui) return;

                try
                {
                    var source = TUIComponentGenerator.Generate(model);
                    context.AddSource($"{model.ClassName}.TUI.g.cs", source);
                }
                catch (Exception ex)
                {
                    // Report diagnostic for generation errors
                    var diagnostic = Diagnostic.Create(
                        new DiagnosticDescriptor(
                            "CFGUI003",
                            "TUI Component Generation Failed",
                            "Failed to generate TUI component for {0}: {1}",
                            "ConfigurationUI.SourceGenerator",
                            DiagnosticSeverity.Error,
                            isEnabledByDefault: true),
                        Location.None,
                        model.ClassName,
                        ex.Message);
                    context.ReportDiagnostic(diagnostic);
                }
            });

        // Register ConfigurationFormModel generation
        context.RegisterSourceOutput(
            configurationClasses,
            static (context, model) =>
            {
                if (model == null) return;

                try
                {
                    var source = ConfigurationFormModelGenerator.Generate(model);
                    context.AddSource($"{model.ClassName}.FormModel.g.cs", source);
                }
                catch (Exception ex)
                {
                    // Report diagnostic for generation errors
                    var diagnostic = Diagnostic.Create(
                        new DiagnosticDescriptor(
                            "CFGUI004",
                            "ConfigurationFormModel Generation Failed",
                            "Failed to generate ConfigurationFormModel for {0}: {1}",
                            "ConfigurationUI.SourceGenerator",
                            DiagnosticSeverity.Error,
                            isEnabledByDefault: true),
                        Location.None,
                        model.ClassName,
                        ex.Message);
                    context.ReportDiagnostic(diagnostic);
                }
            });
    }

    private static ConfigurationModel? GetConfigurationModel(GeneratorAttributeSyntaxContext context)
    {
        if (context.TargetNode is not ClassDeclarationSyntax classDeclaration)
            return null;

        if (context.TargetSymbol is not INamedTypeSymbol classSymbol)
            return null;

        try
        {
            return ConfigurationAnalyzer.Analyze(classSymbol);
        }
        catch (Exception ex)
        {
            // Why: source generator analysis errors must not crash the generator pipeline;
            // return null so the caller skips this model and reports diagnostics during generation.
            // ex.Message observed to satisfy FDW022; no logger is available in a source generator.
            _ = ex.Message;
            return null;
        }
    }
}
