<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <RootNamespace>Fdw.Services.Data.Clients</RootNamespace>
    <PackageId>Fdw.Services.Data.Clients.Abstractions</PackageId>
    <Title>Fdw Data Client Abstractions</Title>
    <Description>DTO models for data API client operations.</Description>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="FluentValidation" />
    <ProjectReference Include="..\Fdw.Web.Clients.Abstractions\Fdw.Web.Clients.Abstractions.csproj" />
  </ItemGroup>
</Project>
