using System.Diagnostics.CodeAnalysis;
using Fdw.Collections;
using Fdw.Services;
using Fdw.Services.Abstractions;
using Fdw.ServiceTypes;
using Fdw.Services.DataVault.Abstractions;
using Fdw.ServiceTypes.Logging;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Logging.Abstractions;
using System;
using Fdw.Results;
using Microsoft.Extensions.Hosting;

namespace Fdw.Services.DataVault;

/// <summary>
/// Collection of data vault service types.
/// Generated by ServiceTypeCollectionGenerator with high-performance lookups.
/// </summary>
[ExcludeFromCodeCoverage]
[ServiceTypeCollection(
    typeof(DataVaultTypeBase<IDataVault, IDataVaultFactory<IDataVault, DataVaultConfiguration>, DataVaultConfiguration>),
    typeof(IDataVaultType),
    typeof(DataVaultServiceTypes),
    GenerateProvider = true,
    ServiceInterface = typeof(IDataVault),
    ConfigurationType = typeof(DataVaultConfiguration),
    ProviderType = typeof(DefaultDataVaultProvider),
    ProviderInterface = typeof(IDataVaultProvider),
    ServiceCategory = "DataVault",
    Group = 4)]
public partial class DataVaultServiceTypes : ServiceTypeCollectionBase<
    DataVaultTypeBase<IDataVault, IDataVaultFactory<IDataVault, DataVaultConfiguration>, DataVaultConfiguration>,
    IDataVaultType<IDataVault, IDataVaultFactory<IDataVault, DataVaultConfiguration>, DataVaultConfiguration>>
{
    // Configure(), Register() and Initialize() are source-generated

    /// <summary>
    /// Sets this collection's Register body: the option sweep, then this domain's provider.
    /// </summary>
    /// <remarks>
    /// The provider is one registration for the whole collection and this declaration already names it,
    /// so the body that registers it is written here beside the declaration. Setting it as the phase's
    /// body is what makes it replaceable: an application calling <c>Registration(...)</c> replaces the
    /// sweep and this registration together, which is the correct semantic for a host taking over phase 2.
    /// </remarks>
    static DataVaultServiceTypes()
    {
        var sweepOptions = RegisterFunc;
        Registration((builder, loggerFactory) =>
        {
            // Why the result is read: this replacement calls the func it captured, and discarding
            // what that returned meant an option that failed to register was followed by this body
            // registering the provider anyway and reporting success.
            var registered = sweepOptions(builder, loggerFactory);
            if (registered.IsFailure)
                return registered;

            builder.Services.AddScoped<IDataVaultProvider>(sp =>
            {
                var provider = new DefaultDataVaultProvider(
                    sp,
                    sp.GetService<ILoggerFactory>()?.CreateLogger<DefaultDataVaultProvider>()
                    ?? NullLogger<DefaultDataVaultProvider>.Instance);
                var stLogger = sp.GetService<ILoggerFactory>()?.CreateLogger("DataVaultServiceTypes");
                try
                {
                    if (sp.GetService<IServiceConfigurationProvider<DataVaultConfiguration>>() is { } cfgProvider)
                    {
                        // Why the result is read: a provider that did not take its parent still constructs, and
                        // every later read silently misses. The failure has to be said out loud here or nowhere.
                        var parentResult = provider.Register(cfgProvider);
                        if (!parentResult.IsSuccess && stLogger != null)
                            ServiceTypeLog.FactoryRegistrationFailed(stLogger, "DataVaultServiceTypes", parentResult.CurrentMessage ?? "DataVaultServiceTypes");
                    }
                }
                catch (Exception ex)
                {
                    // Why rethrow: a throw here was previously silent, and a provider that failed to take
                    // its parent is unusable in a way that only surfaces much later.
                    if (stLogger != null) ServiceTypeLog.FactoryRegistrationException(stLogger, ex, "DataVaultServiceTypes");
                    throw;
                }
                return provider;
            });
            return GenericResult<IHostApplicationBuilder>.Success(builder);
        });
    }
}
