<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <Content Include="xunit.runner.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\Fdw.Services.Etl\Fdw.Services.Etl.csproj" />
    <ProjectReference Include="..\..\src\Fdw.Messages\Fdw.Messages.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
  </ItemGroup>
  <PropertyGroup>
    <!-- Only include Fdw.Services.Etl in coverage -->
    <Include>[Fdw.Services.Etl]*</Include>
    <Exclude>[xunit.*]*,[Moq]*,[Shouldly]*</Exclude>
  </PropertyGroup>
</Project>
