<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <RootNamespace>Fdw.Web.Search.Clients</RootNamespace>
    <PackageId>Fdw.Web.Search.Clients</PackageId>
    <Title>Fdw Search API Clients</Title>
    <Description>API clients and DTOs for search operations.</Description>
    <PackageTags>api;clients;search</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../Fdw.Web.Clients/Fdw.Web.Clients.csproj" />
    <ProjectReference Include="..\Fdw.Web.Endpoints\Fdw.Web.Endpoints.csproj" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Http" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Fdw.Web.Search.Clients.Abstractions\Fdw.Web.Search.Clients.Abstractions.csproj" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Fdw.Collections.SourceGenerators\Fdw.Collections.SourceGenerators.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" PrivateAssets="all" />
    <ProjectReference Include="..\Fdw.Web.Http.Authentication\Fdw.Web.Http.Authentication.csproj" />
  </ItemGroup>

</Project>
