namespace Fdw.Collections.SourceGenerators.Shared;

/// <summary>
/// The kind of collection being generated.
/// </summary>
/// <remarks>
/// Pragma suppression required: source generators cannot use TypeCollections because TypeCollections
/// are themselves generated by source generators (bootstrapping problem).
/// </remarks>
#pragma warning disable FDW017 // Source generator internal enum — bootstrapping prevents TypeCollection usage
internal enum CollectionKind
{
    /// <summary>Immutable with FrozenDictionary.</summary>
    Immutable,

    /// <summary>Mutable with ConcurrentDictionary and Register() method.</summary>
    Mutable,

    /// <summary>Factory pattern returning new instances.</summary>
    Factory
}
#pragma warning restore FDW017