using Fdw.Abstractions;
using Fdw.Collections;
using Fdw.Configuration;
using Fdw.Results;
using Fdw.ServiceTypes;
using Fdw.ServiceTypes.Logging;
using Fdw.Services.Abstractions.Health;
using Fdw.Services.Abstractions;
using Fdw.Services.Configuration;
using Fdw.Services.Connections.Abstractions;
using Fdw.Services.Connections.Commands;
using Fdw.Services.Connections.Logging;
using Fdw.Services.Data.Abstractions;
using Microsoft.Extensions.DependencyInjection.Extensions;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.Logging.Abstractions;
using Microsoft.Extensions.Logging;
using System.Diagnostics.CodeAnalysis;
using System.Linq;
using System;

namespace Fdw.Services.Connections;

/// <summary>
/// Collection of connection service types.
/// Generated by ServiceTypeCollectionGenerator with high-performance lookups.
/// </summary>
/// <remarks>
/// <para>
/// This is the <b>reference implementation</b> for ServiceTypeCollections. New collections
/// should follow the same structure: open-generic base class, generic + marker interfaces,
/// and concrete options that resolve type parameters to unique types.
/// </para>
/// <para>
/// Cross-assembly options (e.g., <c>MsSqlConnectionType</c> in
/// <c>ReferenceConnections.MsSql.ServiceType</c>) are registered via a <c>[ModuleInitializer]</c>
/// generated by <c>Fdw.Registration.SourceGenerators</c> in the entry point project.
/// </para>
/// </remarks>
[ExcludeFromCodeCoverage]
[ServiceTypeCollection(
    typeof(ConnectionTypeBase<IGenericConnection, IConnectionFactory<IGenericConnection, ConnectionConfiguration>, ConnectionConfiguration>),
    typeof(IConnectionType),
    typeof(ConnectionTypes),
    GenerateProvider = true,
    ServiceInterface = typeof(IGenericConnection),
    ConfigurationType = typeof(ConnectionConfiguration),
    ProviderType = typeof(DefaultConnectionProvider),
    ProviderInterface = typeof(IConnectionProvider),
    ServiceCategory = "Connection",
    Group = 1)]
public partial class ConnectionTypes : ServiceTypeCollectionBase<
    ConnectionTypeBase<IGenericConnection, IConnectionFactory<IGenericConnection, ConnectionConfiguration>, ConnectionConfiguration>,
    IConnectionType<IGenericConnection, ConnectionConfiguration, IConnectionFactory<IGenericConnection, ConnectionConfiguration>>>
{
    /// <summary>
    /// Sets this collection's Register body: the option collect, then this domain's provider.
    /// </summary>
    /// <remarks>
    /// <para>
    /// The provider is one registration for the whole collection, and this declaration already names it
    /// — so the body that registers it is written here, beside the declaration, rather than emitted
    /// around the phase or folded into a per-option cascade. The phase is handed the builder, which is
    /// all the registration needs.
    /// </para>
    /// <para>
    /// Setting it as the phase's body is what makes it replaceable: an application calling
    /// <c>Registration(...)</c> in its own start-up replaces the collect and this registration together,
    /// which is the correct semantic — a host that supplies its own phase 2 is taking responsibility for
    /// the whole of it, and the phase reports that it is running a custom implementation.
    /// </para>
    /// <para>
    /// Why a static constructor: it runs when the generated <c>[ModuleInitializer]</c> — a member of this
    /// class — is invoked at assembly load, which is before anything can read the collection. Declaring
    /// it also removes <c>beforefieldinit</c>, so initialization is precise rather than merely eventual.
    /// </para>
    /// </remarks>
    static ConnectionTypes()
    {
        var collectOptions = RegisterFunc;

        // Why a local: this closed generic is the DI key a consumer injects, and it is reported at
        // three points below — the deferred declaration, the milestone, and the zero-option warning.
        // Written out three times it is three chances for them to disagree.
        var providerService = typeof(IConnectionProvider).ToString();

        Registration((builder, loggerFactory) =>
        {
            var log = loggerFactory?.CreateLogger<ConnectionTypes>() ?? NullLogger<ConnectionTypes>.Instance;

            // Why the collection registers the parent provider and does it before the options run:
            // the owner of a registration is the type that knows the thing exists. This collection
            // ships beside ConnectionConfigurationProvider, so it knows; a connection-kind option knows
            // only itself and registers its own component INTO this provider, so the provider has to
            // exist first. It used to exist because all six option types called a static on the provider
            // and leaned on TryAdd to make six calls behave like one.
            ConnectionProviderLogger.DomainConfigurationRegistering(
                loggerFactory?.CreateLogger<ConnectionConfigurationProvider>()
                ?? NullLogger<ConnectionConfigurationProvider>.Instance,
                nameof(ConnectionConfigurationProvider));

            builder.Services.TryAddSingleton<ConnectionConfigurationProvider>(sp =>
                new ConnectionConfigurationProvider(
                    sp.GetService<ILogger<ConnectionConfigurationProvider>>()!,
                    sp.GetRequiredService<Lazy<IConfigurationGateway>>(),
                    invalidator: new Lazy<ICacheInvalidator?>(() => sp.GetService<ICacheInvalidator>())));

            builder.Services.TryAddSingleton<DefaultConfigurationProvider<ConnectionConfiguration, ConnectionConfigurationCommand>>(
                sp => sp.GetRequiredService<ConnectionConfigurationProvider>());

            builder.Services.TryAddSingleton<IServiceConfigurationProvider<ConnectionConfiguration>>(
                sp => sp.GetRequiredService<ConnectionConfigurationProvider>());

            // Why one health checkable for the domain rather than one per connection: conn.Connection
            // rows are runtime data enumerated at check time, never per-row DI registrations.
            builder.Services.TryAddEnumerable(
                ServiceDescriptor.Singleton<IHealthCheckable, ConnectionsHealthCheckable>());

            // Why Scoped: ConnectionHealthService depends on the Scoped IDataGateway, and a Singleton
            // would pin the first-resolved scope's gateway forever.
            builder.Services.TryAddScoped<IConnectionHealthService, ConnectionHealthService>();

            builder.Services.AddHostedService<ConnectionHealthMonitorWorker>();

            // Why an alias and why Scoped: DefaultConnectionProvider implements both interfaces, and
            // IConnectionProvider is generated Scoped, so a Singleton alias over it would be a captive
            // dependency that throws under ValidateScopes.
            builder.Services.TryAddScoped<IDataConnectionProvider>(sp =>
                (IDataConnectionProvider)sp.GetRequiredService<IConnectionProvider>());

            // Why: IServiceConnectionProvider serves framework-internal connections such as ConfigurationDb.
            builder.Services.TryAddSingleton<IServiceConnectionProvider, DefaultServiceConnectionProvider>();

            // Why the result is read: this replacement calls the func it captured, and discarding
            // what that returned meant an option that failed to register was followed by this body
            // registering the provider anyway and reporting success.
            var registered = collectOptions(builder, loggerFactory);
            if (registered.IsFailure)
                return registered;

            var declaredOptions = Options;
            var optionNames = string.Join(", ", declaredOptions.Select(option => option.Name));

            ServiceTypeLog.DomainOptionsCollected(log, nameof(ConnectionTypes), declaredOptions.Length, optionNames);

            // Why the collection registers every option's factory, and ConnectionTypeBase no longer does:
            // DefaultConnectionProvider resolves a connection through its own factory registry, and the
            // need is identical for every connection kind. The collection already holds the option set and
            // each option already names its factory type, so this is one loop over what is in hand rather
            // than the same line repeated in six option bodies, where one of them can silently omit it -
            // which is what happened, and every connection create failed with "No factory registered".
            foreach (var option in declaredOptions)
            {
                // Why this fails loud rather than skipping: Options is IServiceTypeRegistration[], which
                // component and endpoint collections implement without ever naming a factory. A connection
                // option that cannot name one leaves its kind uncreatable, and skipping it would surface
                // much later as "No registered service type matches ServiceOptionType" on the first
                // authenticated request, where it reads as a row-level-security failure instead.
                if (option is not IServiceType serviceType)
                    return GenericResult<IHostApplicationBuilder>.Failure(
                        ServiceTypeLog.FactoryRegistrationFailed(
                            log,
                            option.Name,
                            FormattableString.Invariant($"'{option.GetType().Name}' does not implement IServiceType, so it cannot name a factory type")));

                // Why the type is read into a local before the closure: the func is deferred to the
                // provider's constructor, and capturing the loop variable's member access would re-read it
                // there rather than at the point the option was known.
                var factoryType = serviceType.FactoryType;
                DefaultConnectionProvider.Register(
                    option.Name,
                    sp => (IServiceFactory<IGenericConnection>)sp.GetRequiredService(factoryType));

                ServiceTypeLog.FactoryRegistered(log, nameof(ConnectionTypes), option.Name, factoryType.Name);
            }
            ServiceTypeLog.DomainProviderDeclared(log, nameof(ConnectionTypes), providerService);

            builder.Services.AddScoped<IConnectionProvider>(sp =>
            {
                var provider = new DefaultConnectionProvider(
                    sp,
                    sp.GetService<ILoggerFactory>()?.CreateLogger<DefaultConnectionProvider>()
                    ?? NullLogger<DefaultConnectionProvider>.Instance);

                // Why ILogger<ConnectionTypes> and not CreateLogger("ConnectionTypes"): SourceContext then
                // carries the namespace-qualified collection, and the category cannot drift from the
                // type it claims to name. The provider logs its own lines under its own type, so the
                // two layers read base-then-derived rather than collapsing onto one category.
                var stLogger = sp.GetService<ILoggerFactory>()?.CreateLogger<ConnectionTypes>()
                    ?? NullLogger<ConnectionTypes>.Instance;
                ServiceTypeLog.DomainProviderConstructing(stLogger, nameof(ConnectionTypes), provider.GetType().Name);
                try
                {
                    if (sp.GetService<IServiceConfigurationProvider<ConnectionConfiguration>>() is { } cfgProvider)
                    {
                        // Why the result is read: a provider that did not take its parent still constructs, and
                        // every later read silently misses. The failure has to be said out loud here or nowhere.
                        var parentResult = provider.Register(cfgProvider);
                        if (parentResult.IsSuccess)
                            ServiceTypeLog.DomainConfigurationSourceAttached(stLogger, nameof(ConnectionTypes), provider.GetType().Name, cfgProvider.GetType().Name);
                        else
                            ServiceTypeLog.DomainConfigurationSourceRejected(stLogger, nameof(ConnectionTypes), provider.GetType().Name, cfgProvider.GetType().Name, parentResult.CurrentMessage);
                    }
                    else
                    {
                        // Why Critical, and why the collection says it rather than the provider: from
                        // inside the provider a null parent is indistinguishable from a domain that needs
                        // none. This is the one place that knows one was meant to arrive, and without it
                        // the domain fails every lookup by name for the life of the scope with nothing
                        // pointing back here.
                        ServiceTypeLog.DomainHasNoConfigurationSource(
                            stLogger,
                            nameof(ConnectionTypes),
                            provider.GetType().Name,
                            typeof(IServiceConfigurationProvider<ConnectionConfiguration>).ToString());
                    }
                }
                catch (Exception ex)
                {
                    // Why rethrow: a throw here was previously silent, and a provider that failed to take
                    // its parent is unusable in a way that only surfaces much later.
                    ServiceTypeLog.FactoryRegistrationException(stLogger, ex, nameof(ConnectionTypes));
                    throw;
                }
                return provider;
            });

            // Why the milestone comes after the registration and not before: it states that the domain
            // finished phase 2, which is only true once the provider is actually in the container.
            if (declaredOptions.Length == 0)
                ServiceTypeLog.DomainRegisteredWithNoOptions(log, nameof(ConnectionTypes), providerService);
            else
                ServiceTypeLog.DomainRegistered(log, nameof(ConnectionTypes), declaredOptions.Length, optionNames, providerService);

            return GenericResult<IHostApplicationBuilder>.Success(builder);
        });
    }
}
