using System;
using System.Diagnostics.CodeAnalysis;
using Fdw.Collections;
using Fdw.Services.Abstractions;
using Fdw.Services.Connections.Abstractions;
using Fdw.ServiceTypes.Logging;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Logging.Abstractions;
using Fdw.Results;
using Microsoft.Extensions.Hosting;

namespace Fdw.Services.Connections;

/// <summary>
/// Collection of connection service types.
/// Generated by ServiceTypeCollectionGenerator with high-performance lookups.
/// </summary>
/// <remarks>
/// <para>
/// This is the <b>reference implementation</b> for ServiceTypeCollections. New collections
/// should follow the same structure: open-generic base class, generic + marker interfaces,
/// and concrete options that resolve type parameters to unique types.
/// </para>
/// <para>
/// Cross-assembly options (e.g., <c>MsSqlConnectionType</c> in
/// <c>ReferenceConnections.MsSql.ServiceType</c>) are registered via a <c>[ModuleInitializer]</c>
/// generated by <c>Fdw.Registration.SourceGenerators</c> in the entry point project.
/// </para>
/// </remarks>
[ExcludeFromCodeCoverage]
[ServiceTypeCollection(
    typeof(ConnectionTypeBase<IGenericConnection, IConnectionFactory<IGenericConnection, ConnectionConfiguration>, ConnectionConfiguration>),
    typeof(IConnectionType),
    typeof(ConnectionTypes),
    GenerateProvider = true,
    ServiceInterface = typeof(IGenericConnection),
    ConfigurationType = typeof(ConnectionConfiguration),
    ProviderType = typeof(DefaultConnectionProvider),
    ProviderInterface = typeof(IConnectionProvider),
    ServiceCategory = "Connection",
    Group = 1)]
public partial class ConnectionTypes : ServiceTypeCollectionBase<
    ConnectionTypeBase<IGenericConnection, IConnectionFactory<IGenericConnection, ConnectionConfiguration>, ConnectionConfiguration>,
    IConnectionType<IGenericConnection, ConnectionConfiguration, IConnectionFactory<IGenericConnection, ConnectionConfiguration>>>
{
    /// <summary>
    /// Sets this collection's Register body: the option sweep, then this domain's provider.
    /// </summary>
    /// <remarks>
    /// <para>
    /// The provider is one registration for the whole collection, and this declaration already names it
    /// — so the body that registers it is written here, beside the declaration, rather than emitted
    /// around the phase or folded into a per-option cascade. The phase is handed the builder, which is
    /// all the registration needs.
    /// </para>
    /// <para>
    /// Setting it as the phase's body is what makes it replaceable: an application calling
    /// <c>Registration(...)</c> in its own start-up replaces the sweep and this registration together,
    /// which is the correct semantic — a host that supplies its own phase 2 is taking responsibility for
    /// the whole of it, and the phase reports that it is running a custom implementation.
    /// </para>
    /// <para>
    /// Why a static constructor: it runs when the generated <c>[ModuleInitializer]</c> — a member of this
    /// class — is invoked at assembly load, which is before anything can read the collection. Declaring
    /// it also removes <c>beforefieldinit</c>, so initialization is precise rather than merely eventual.
    /// </para>
    /// </remarks>
    static ConnectionTypes()
    {
        var sweepOptions = RegisterFunc;
        Registration((builder, loggerFactory) =>
        {
            // Why the result is read: this replacement calls the func it captured, and discarding
            // what that returned meant an option that failed to register was followed by this body
            // registering the provider anyway and reporting success.
            var registered = sweepOptions(builder, loggerFactory);
            if (registered.IsFailure)
                return registered;

            builder.Services.AddScoped<IConnectionProvider>(sp =>
            {
                var provider = new DefaultConnectionProvider(
                    sp,
                    sp.GetService<ILoggerFactory>()?.CreateLogger<DefaultConnectionProvider>()
                    ?? NullLogger<DefaultConnectionProvider>.Instance);
                var stLogger = sp.GetService<ILoggerFactory>()?.CreateLogger("ConnectionTypes");
                try
                {
                    if (sp.GetService<IServiceConfigurationProvider<ConnectionConfiguration>>() is { } cfgProvider)
                    {
                        // Why the result is read: a provider that did not take its parent still constructs, and
                        // every later read silently misses. The failure has to be said out loud here or nowhere.
                        var parentResult = provider.Register(cfgProvider);
                        if (!parentResult.IsSuccess && stLogger != null)
                            ServiceTypeLog.FactoryRegistrationFailed(stLogger, "ConnectionTypes", parentResult.CurrentMessage ?? "ConnectionTypes");
                    }
                }
                catch (Exception ex)
                {
                    // Why rethrow: a throw here was previously silent, and a provider that failed to take
                    // its parent is unusable in a way that only surfaces much later.
                    if (stLogger != null) ServiceTypeLog.FactoryRegistrationException(stLogger, ex, "ConnectionTypes");
                    throw;
                }
                return provider;
            });
            return GenericResult<IHostApplicationBuilder>.Success(builder);
        });
    }
}