using Fdw.Abstractions;
using Fdw.Collections;
using Fdw.Configuration;
using Fdw.Results;
using Fdw.ServiceTypes;
using Fdw.ServiceTypes.Logging;
using Fdw.Services.Abstractions.Health;
using Fdw.Services.Abstractions;
using Fdw.Services.Configuration;
using Fdw.Services.Connections.Abstractions;
using Fdw.Services.Connections.Commands;
using Fdw.Services.Connections.Logging;
using Fdw.Services.Data.Abstractions;
using Microsoft.Extensions.DependencyInjection.Extensions;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.Logging.Abstractions;
using Microsoft.Extensions.Logging;
using System.Diagnostics.CodeAnalysis;
using System.Linq;
using System;

namespace Fdw.Services.Connections;

/// <summary>
/// Collection of connection service types.
/// Generated by ServiceTypeCollectionGenerator with high-performance lookups.
/// </summary>
/// <remarks>
/// <para>
/// This is the <b>reference implementation</b> for ServiceTypeCollections. New collections
/// should follow the same structure: open-generic base class, generic + marker interfaces,
/// and concrete options that resolve type parameters to unique types.
/// </para>
/// <para>
/// Cross-assembly options (e.g., <c>MsSqlConnectionType</c> in
/// <c>ReferenceConnections.MsSql.ServiceType</c>) are registered via a <c>[ModuleInitializer]</c>
/// generated by <c>Fdw.Registration.SourceGenerators</c> in the entry point project.
/// </para>
/// </remarks>
[ExcludeFromCodeCoverage]
[ServiceTypeCollection(
    typeof(ConnectionTypeBase<IGenericConnection, IConnectionFactory<IGenericConnection, ConnectionConfiguration>, ConnectionConfiguration>),
    typeof(IConnectionType),
    typeof(ConnectionTypes),
    ServiceInterface = typeof(IGenericConnection),
    ProviderType = typeof(ConnectionProvider),
    ProviderInterface = typeof(IConnectionProvider),
    ServiceCategory = "Connection")]
public partial class ConnectionTypes : ServiceTypeCollectionBase<
    ConnectionTypeBase<IGenericConnection, IConnectionFactory<IGenericConnection, ConnectionConfiguration>, ConnectionConfiguration>,
    IConnectionType<IGenericConnection, ConnectionConfiguration, IConnectionFactory<IGenericConnection, ConnectionConfiguration>>>
{
    /// <summary>
    /// Sets this collection's Register body: the option collect, then this domain's provider.
    /// </summary>
    /// <remarks>
    /// <para>
    /// The provider is one registration for the whole collection, and this declaration already names it
    /// — so the body that registers it is written here, beside the declaration, rather than emitted
    /// around the phase or folded into a per-option cascade. The phase is handed the builder, which is
    /// all the registration needs.
    /// </para>
    /// <para>
    /// Setting it as the phase's body is what makes it replaceable: an application calling
    /// <c>Registration(...)</c> in its own start-up replaces the collect and this registration together,
    /// which is the correct semantic — a host that supplies its own phase 2 is taking responsibility for
    /// the whole of it, and the phase reports that it is running a custom implementation.
    /// </para>
    /// <para>
    /// Why a static constructor: it runs when the generated <c>[ModuleInitializer]</c> — a member of this
    /// class — is invoked at assembly load, which is before anything can read the collection. Declaring
    /// it also removes <c>beforefieldinit</c>, so initialization is precise rather than merely eventual.
    /// </para>
    /// </remarks>
    /// <summary>
    /// The connection this domain's configuration rows are read from and written to.
    /// </summary>
    /// <remarks>
    /// Defaulted here and public so a host can point the whole domain at a different configuration
    /// store before registration runs. Every implementation of a connection lives in the same store as
    /// the connection row that owns it — the foreign key is declared on that row and cannot span
    /// connections — so this one value settles the domain and its implementations together.
    /// </remarks>
    public static string ConfigurationConnection { get; set; } = "PlatformConfiguration";

    static ConnectionTypes()
    {
        var collectOptions = RegisterFunc;

        var providerService = typeof(IConnectionProvider).ToString();

        Registration((builder, loggerFactory) =>
        {
            var log = loggerFactory?.CreateLogger<ConnectionTypes>() ?? NullLogger<ConnectionTypes>.Instance;

            ConnectionProviderLogger.DomainConfigurationRegistering(
                loggerFactory?.CreateLogger<ConnectionConfigurationProvider>()
                ?? NullLogger<ConnectionConfigurationProvider>.Instance,
                nameof(ConnectionConfigurationProvider));

            // The concrete type is registered as well as the interface, and the interface resolves
            // to it, so both are one instance. Endpoints take the concrete provider - 25 of them do
            // - and registering only the interface leaves every one of them unactivatable. That
            // surfaces as FastEndpoints failing at MapFastEndpoints rather than as a missing
            // registration, which points at the endpoint instead of at this line.
            builder.Services.TryAddSingleton<ConnectionConfigurationProvider>(sp =>
                new ConnectionConfigurationProvider(
                    sp.GetService<ILogger<ConnectionConfigurationProvider>>()!,
                    sp.GetRequiredService<IConfigurationGatewayProvider>(),
                    ConfigurationConnection));

            builder.Services.TryAddSingleton<IConnectionConfigurationProvider>(
                sp => sp.GetRequiredService<ConnectionConfigurationProvider>());

            builder.Services.TryAddEnumerable(
                ServiceDescriptor.Singleton<IHealthCheckable, ConnectionsHealthCheckable>());

            builder.Services.TryAddScoped<IConnectionHealthService, ConnectionHealthService>();

            builder.Services.AddHostedService<ConnectionHealthMonitorWorker>();

            builder.Services.TryAddScoped<IDataConnectionProvider>(sp =>
                (IDataConnectionProvider)sp.GetRequiredService<IConnectionProvider>());

            builder.Services.TryAddSingleton<IServiceConnectionProvider, ServiceConnectionProvider>();

            var registered = collectOptions(builder, loggerFactory);
            if (registered.IsFailure)
                return registered;

            var declaredOptions = Options;
            var optionNames = string.Join(", ", declaredOptions.Select(option => option.Name));

            ServiceTypeLog.DomainOptionsCollected(log, nameof(ConnectionTypes), declaredOptions.Length, optionNames);

            foreach (var option in declaredOptions)
            {
                if (option is not IServiceType serviceType)
                    return GenericResult<IHostApplicationBuilder>.Failure(
                        ServiceTypeLog.FactoryRegistrationFailed(
                            log,
                            option.Name,
                            FormattableString.Invariant($"'{option.GetType().Name}' does not implement IServiceType, so it cannot name a factory type")));

                var factoryType = serviceType.FactoryType;
                ConnectionProvider.Register(
                    option.Name,
                    sp => (IServiceFactory<IGenericConnection>)sp.GetRequiredService(factoryType));

                ServiceTypeLog.FactoryRegistered(log, nameof(ConnectionTypes), option.Name, factoryType.Name);
            }
            ServiceTypeLog.DomainProviderDeclared(log, nameof(ConnectionTypes), providerService);

            builder.Services.AddScoped<IConnectionProvider>(sp =>
            {
                var provider = new ConnectionProvider(
                    sp,
                    sp.GetService<ILoggerFactory>()?.CreateLogger<ConnectionProvider>()
                    ?? NullLogger<ConnectionProvider>.Instance);

                var stLogger = sp.GetService<ILoggerFactory>()?.CreateLogger<ConnectionTypes>()
                    ?? NullLogger<ConnectionTypes>.Instance;
                ServiceTypeLog.DomainProviderConstructing(stLogger, nameof(ConnectionTypes), provider.GetType().Name);
                try
                {
                    if (sp.GetService<IConnectionConfigurationProvider>() is { } cfgProvider)
                    {
                        var domainResult = provider.Register(cfgProvider);
                        if (domainResult.IsSuccess)
                            ServiceTypeLog.DomainConfigurationSourceAttached(stLogger, nameof(ConnectionTypes), provider.GetType().Name, cfgProvider.GetType().Name);
                        else
                            ServiceTypeLog.DomainConfigurationSourceRejected(stLogger, nameof(ConnectionTypes), provider.GetType().Name, cfgProvider.GetType().Name, domainResult.CurrentMessage);
                    }
                    else
                    {
                        ServiceTypeLog.DomainHasNoConfigurationSource(
                            stLogger,
                            nameof(ConnectionTypes),
                            provider.GetType().Name,
                            typeof(IServiceConfigurationProvider<ConnectionConfiguration>).ToString());
                    }
                }
                catch (Exception ex)
                {
                    ServiceTypeLog.FactoryRegistrationException(stLogger, ex, nameof(ConnectionTypes));
                    throw;
                }
                return provider;
            });

            if (declaredOptions.Length == 0)
                ServiceTypeLog.DomainRegisteredWithNoOptions(log, nameof(ConnectionTypes), providerService);
            else
                ServiceTypeLog.DomainRegistered(log, nameof(ConnectionTypes), declaredOptions.Length, optionNames, providerService);

            return GenericResult<IHostApplicationBuilder>.Success(builder);
        });
    }
}
