<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <RootNamespace>$namespace$.$serviceName$</RootNamespace>
    <Description>$serviceName$ service types and provider for Fdw</Description>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\$serviceName$.Abstractions\$serviceName$.Abstractions.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Fdw.Collections" Version="$$(FractalDataWorksVersion)" />
    <PackageReference Include="Fdw.Collections.SourceGenerators" Version="$$(FractalDataWorksVersion)" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
    <PackageReference Include="Fdw.Configuration" Version="$$(FractalDataWorksVersion)" />
    <PackageReference Include="Fdw.ServiceTypes" Version="$$(FractalDataWorksVersion)" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="9.0.0" />
  </ItemGroup>

</Project>
