using System;
using System.Diagnostics.CodeAnalysis;

namespace Fdw.Data;

/// <summary>
/// Marks a type to have a compile-time POCO mapper generated.
/// Eliminates reflection overhead for DbDataReader to POCO mapping.
/// </summary>
/// <remarks>
/// <para>
/// When applied to a class or struct, the <c>Fdw.Data.SourceGenerators</c>
/// package generates a mapper class that implements <see cref="Abstractions.Mappers.PocoMappers.IPocoMapper"/>.
/// </para>
/// <para>
/// The generated mapper is registered with <see cref="Abstractions.Mappers.PocoMappers.PocoMapperCollection"/>
/// via a module initializer generated by <c>Fdw.Registration.SourceGenerators</c>.
/// </para>
/// <para>
/// <b>Important:</b> The consuming application must reference both:
/// <list type="bullet">
///   <item><c>Fdw.Data.SourceGenerators</c> - generates the mapper classes</item>
///   <item><c>Fdw.Registration.SourceGenerators</c> - generates the module initializer</item>
/// </list>
/// </para>
/// </remarks>
/// <example>
/// <code>
/// [GenerateMapper]
/// public class Customer
/// {
///     public int Id { get; set; }
///     public string Name { get; set; }
///     public DateTime CreatedAt { get; set; }
/// }
/// </code>
/// </example>
// Why: pure attribute definition (declarative metadata only, consumed by the PocoMapperGenerator) — no logic to unit test.
[AttributeUsage(AttributeTargets.Class | AttributeTargets.Struct, AllowMultiple = false)]
[ExcludeFromCodeCoverage]
public sealed class GenerateMapperAttribute : Attribute
{
    /// <summary>
    /// Gets or sets the mapping direction(s) to generate.
    /// </summary>
    /// <value>
    /// <see cref="MapperDirection.Input"/> (default) generates read-side mapping only, preserving
    /// backward compatibility with all existing <c>[GenerateMapper]</c> sites.
    /// <see cref="MapperDirection.Output"/> generates write-side mapping only.
    /// <see cref="MapperDirection.Both"/> generates both directions.
    /// </value>
    public MapperDirection Direction { get; set; } = MapperDirection.Input;
}
