using System;
using System.Diagnostics.CodeAnalysis;
using System.Linq;
using Fdw.Collections;
using Fdw.Services.Data.Configuration;
using Fdw.Services.Multitenancy.Logging;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Logging.Abstractions;
using Fdw.Results;

namespace Fdw.Services.Multitenancy;

/// <summary>
/// ServiceTypeCollection for multitenancy service types.
/// Generated by ServiceTypeCollectionGenerator with high-performance lookups.
/// </summary>
/// <remarks>
/// <para>
/// Multitenancy is a "declared choice" domain, not a "many named instances" domain: exactly one
/// option (<c>SingleTenant</c> in this assembly, <c>Sql</c> in <c>Fdw.Services.Multitenancy.Sql</c>)
/// is active per host, selected by <see cref="ConfigurationSchema.Multitenancy"/> (the host's own
/// configurationSchema.json, alongside its Connections/SecretManagers/DataStores). Unlike
/// <c>HealthMonitorTypes</c> (which registers every option's factory so a shared provider can dispatch
/// by name at runtime), both options register the SAME interfaces (<c>ITenantProvider</c>,
/// <c>IOrganizationProvider</c>), so running both would leave the winner to non-deterministic discovery
/// order instead of host configuration.
/// </para>
/// <para>
/// This is why the static constructor below OVERRIDES the collection's generated Configure/Register/
/// Initialize via the mutable-phase mechanism (<c>Configuration</c>/<c>Registration</c>/
/// <c>Initialization</c> — see the "Overriding a phase" section of the TypeCollection Patterns wiki)
/// instead of hand-writing those three methods: <see cref="SelectAndConfigureSingleOption"/> resolves
/// the single configured choice and drives that ONE option's Configure/Register
/// directly, instead of the generated blanket Configure/Register that would iterate every discovered
/// option; Register/Initialize become no-ops since Configure already did the only work needed. This
/// makes the domain self-selecting — it is not excluded from the collect; it
/// participates in the ordinary PlatformServices Configure/Register/Initialize collects like every other
/// domain, and the "exactly one option runs" guarantee lives here instead of in each host's Program.cs.
/// </para>
/// </remarks>
[ExcludeFromCodeCoverage]
[ServiceTypeCollection(
    typeof(MultitenancyTypeBase<IMultitenancyFactory>),
    typeof(IMultitenancyType),
    typeof(MultitenancyTypes))]
public partial class MultitenancyTypes : ServiceTypeCollectionBase<MultitenancyTypeBase<IMultitenancyFactory>, IMultitenancyType>
{
    // Why [ModuleInitializer] rather than an explicit static constructor: the generator ALREADY emits
    // this type's static constructor (for the deferred-freeze RegisterMember discovery), and C# permits
    // only one `static ClassName()` per type across all partial declarations — a second one is a compile
    // error. A module initializer runs at ASSEMBLY LOAD, strictly before any static constructor in the
    // assembly can fire, so these overrides are guaranteed in place before PlatformServices' collect (or any
    // direct MultitenancyTypes.Configure/Register/Initialize call) could otherwise run the generated
    // default (iterate every discovered option), which this domain must never do. Accessing
    // MultitenancyTypes.Configuration(...) below also triggers this type's own static constructor first
    // (per ordinary C# static-init-on-first-access rules), so RegisterMember discovery still runs before
    // these overrides are set — the ordering this domain needs falls out naturally.
    // Why: CA2255 discourages [ModuleInitializer] in libraries, but selecting this domain's self-selecting
    // Configure/Register/Initialize overrides before the generated static constructor's discovery runs is
    // exactly the sanctioned "advanced" use — mirrors OpenIddictPocoMapperRegistration's identical rationale.
#pragma warning disable CA2255 // The 'ModuleInitializer' attribute should not be used in libraries
    [System.Runtime.CompilerServices.ModuleInitializer]
    internal static void RegisterOverrides()
    {
        Configuration(SelectAndConfigureSingleOption);
        // Why no-op: SelectAndConfigureSingleOption already ran the selected option's full
        // Configure/Register before Build(). These stay overridden (rather than left at
        // the generated default) so the ordinary PlatformServices collect does not ALSO iterate and
        // register every discovered option — this domain runs exactly one.
        Registration(static (builder, _) => GenericResult<IHostApplicationBuilder>.Success(builder));
        Initialization(static (host, _) => GenericResult<IHost>.Success(host));
    }
#pragma warning restore CA2255

    /// <summary>
    /// Self-selecting Configure: resolves the single active Multitenancy option from
    /// <see cref="ConfigurationSchema.Multitenancy"/> and drives its
    /// <c>Configure</c>/<c>Register</c> directly. See the type remarks for why this
    /// replaces the generated blanket Configure/Register for this domain.
    /// </summary>
    /// <param name="builder">The host application builder.</param>
    /// <param name="loggerFactory">Optional logger factory for startup diagnostics.</param>
    /// <returns>
    /// The builder on success. A failure when the host's <see cref="ConfigurationSchema.Multitenancy"/>
    /// choice is missing, or names a ServiceOptionType that does not match any registered option
    /// (NO FALLBACKS — never a silent default).
    /// </returns>
    // Why these are returned rather than thrown: both already build a logged message describing exactly
    // what is wrong, and wrapping that in an exception threw away the message object to carry only its
    // string. Returning the failure keeps the message — and lets the host decide whether a missing
    // multitenancy choice stops it, which is not this collection's call to make.
    private static IGenericResult<IHostApplicationBuilder> SelectAndConfigureSingleOption(IHostApplicationBuilder builder, ILoggerFactory? loggerFactory)
    {
        var logger = loggerFactory?.CreateLogger("MultitenancyTypes") ?? NullLogger.Instance;

        // Why: which Multitenancy option a host runs is per-host topology, declared once in
        // configurationSchema.json (ConfigurationSchema.Multitenancy) — not a shared ConfigurationDb row.
        // AddConfigurationGateway registers the deserialized ConfigurationSchema as a direct singleton
        // INSTANCE (TryAddSingleton(schema)), so it is resolvable straight off the pre-Build service
        // descriptor — no factory invocation, no partially-built ServiceProvider required.
        var schema = builder.Services
            .FirstOrDefault(d => d.ServiceType == typeof(ConfigurationSchema))
            ?.ImplementationInstance as ConfigurationSchema;
        var choice = schema?.Multitenancy;

        if (string.IsNullOrWhiteSpace(choice))
        {
            return GenericResult<IHostApplicationBuilder>.Failure(MultitenancyLog.ChoiceMissing(logger));
        }

        var option = ByName(choice);
        if (option == NotFound)
        {
            return GenericResult<IHostApplicationBuilder>.Failure(MultitenancyLog.ChoiceNotFound(logger, choice));
        }

        // Why this collection selects ONE option instead of collecting all of them: multitenancy is a
        // host-wide choice, so exactly the configured option runs its phases.
        var configured = option.Configure(builder);
        if (configured.IsFailure)
            return configured;

        var registered = option.Register(builder, loggerFactory);
        if (registered.IsFailure)
            return registered;

        builder.Services.AddSingleton<IMultitenancyType>(option);

        return GenericResult<IHostApplicationBuilder>.Success(builder);
    }
}
