using System;
using System.Collections.Generic;
using System.Globalization;
using System.Reflection;
using System.Text;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Logging.Abstractions;

namespace Fdw.Hosting.WebMcp;

/// <summary>
/// Generates the <c>webmcp.js</c> IIFE that registers AI-agent tools via
/// <c>document.modelContext.registerTool()</c> (WebMCP W3C standard).
/// </summary>
public sealed class WebMcpJsGenerator
{
    private readonly IWebMcpToolRegistry _registry;
    private readonly ILogger<WebMcpJsGenerator> _logger;
    private readonly WebMcpOptions? _options;

    /// <summary>
    /// Initializes a new instance of <see cref="WebMcpJsGenerator"/>.
    /// </summary>
    public WebMcpJsGenerator(
        IWebMcpToolRegistry registry,
        ILogger<WebMcpJsGenerator>? logger = null,
        WebMcpOptions? options = null)
    {
        _registry = registry;
        _logger = logger ?? NullLogger<WebMcpJsGenerator>.Instance;
        _options = options;
    }

    /// <summary>
    /// Builds and returns the full JavaScript source string.
    /// Returns a no-op script if no tools have been registered.
    /// </summary>
    public string Generate()
    {
        WebMcpLog.ServingWebMcpJs(_logger, _registry.Tools.Count);
        WebMcpLog.GeneratingScript(_logger, _registry.Tools.Count);

        // Why the decision is logged once here rather than per tool: it is a property of the served
        // script, not of any one tool, and the value itself must never reach a log sink — this
        // script is public, so the key's presence is the only auditable part.
        WebMcpLog.ClientKeyInjection(
            _logger,
            _options?.ApiKeyHeader ?? "X-Webmcp-Key",
            !string.IsNullOrEmpty(_options?.ClientApiKey));

        var sb = new StringBuilder();
        sb.AppendLine("// Generated by Fdw WebMCP");
        sb.AppendLine("// Registers AI agent tools via document.modelContext (WebMCP W3C standard).");
        sb.AppendLine("// The spec moved the API from navigator to document because tools belong to a");
        sb.AppendLine("// page, and Chrome 150 deprecated the navigator form while the Chrome 149");
        sb.AppendLine("// origin trial still serves it. Prefer document, accept navigator, so one");
        sb.AppendLine("// generated script works across the Chrome 149-156 trial window.");
        sb.AppendLine("(function() {");
        sb.AppendLine("  var modelContext =");
        sb.AppendLine("    (typeof document !== 'undefined' && document.modelContext) ||");
        sb.AppendLine("    (typeof navigator !== 'undefined' && navigator.modelContext) ||");
        sb.AppendLine("    null;");
        sb.AppendLine("  if (!modelContext) return;");
        sb.AppendLine();

        foreach (var tool in _registry.Tools)
        {
            AppendTool(sb, tool);
        }

        sb.AppendLine("})();");

        return sb.ToString();
    }

    // ── Per-tool JavaScript block ────────────────────────────────────────────

    private void AppendTool(StringBuilder sb, WebMcpToolDescriptor tool)
    {
        sb.AppendLine("  modelContext.registerTool({");
        sb.AppendLine(CultureInfo.InvariantCulture, $"    name: {JsonString(tool.Name)},");
        sb.AppendLine(CultureInfo.InvariantCulture, $"    description: {JsonString(tool.Description)},");

        if (tool.ReadOnly)
        {
            sb.AppendLine("    annotations: { readOnlyHint: true },");
        }

        var propertyCount = AppendInputSchema(sb, tool);
        AppendExecute(sb, tool);

        sb.AppendLine("  });");
        sb.AppendLine();

        WebMcpLog.ToolScriptEmitted(_logger, tool.Name, tool.HttpMethod, tool.Route, propertyCount);
    }

    private int AppendInputSchema(StringBuilder sb, WebMcpToolDescriptor tool)
    {
        // GET and DELETE with no request type get an empty schema
        var needsBody = NeedsRequestBody(tool.HttpMethod);

        if (!needsBody || tool.RequestType is null)
        {
            sb.AppendLine("    inputSchema: {");
            sb.AppendLine("      type: \"object\",");
            sb.AppendLine("      properties: {},");
            sb.AppendLine("      required: []");
            sb.AppendLine("    },");
            return 0;
        }

        var properties = GetSchemaProperties(tool.RequestType, tool.Name, _logger);

        sb.AppendLine("    inputSchema: {");
        sb.AppendLine("      type: \"object\",");
        sb.AppendLine("      properties: {");

        for (var i = 0; i < properties.Count; i++)
        {
            var (propName, jsonType, format) = properties[i];
            var comma = i < properties.Count - 1 ? "," : string.Empty;

            if (string.IsNullOrEmpty(format))
            {
                sb.AppendLine(CultureInfo.InvariantCulture, $"        {JsonKey(propName)}: {{ \"type\": {JsonString(jsonType)} }}{comma}");
            }
            else
            {
                sb.AppendLine(CultureInfo.InvariantCulture, $"        {JsonKey(propName)}: {{ \"type\": {JsonString(jsonType)}, \"format\": {JsonString(format)} }}{comma}");
            }
        }

        sb.AppendLine("      },");

        // All properties are treated as optional — required is empty unless you know better
        sb.AppendLine("      required: []");
        sb.AppendLine("    },");

        return properties.Count;
    }

    private void AppendExecute(StringBuilder sb, WebMcpToolDescriptor tool)
    {
        sb.AppendLine("    execute: async function(input) {");

        var clientApiKey = _options?.ClientApiKey;
        var apiKeyHeader = _options?.ApiKeyHeader ?? "X-Webmcp-Key";

        if (NeedsRequestBody(tool.HttpMethod))
        {
            sb.AppendLine(CultureInfo.InvariantCulture, $"      const r = await fetch({JsonString(tool.Route)}, {{");
            sb.AppendLine(CultureInfo.InvariantCulture, $"        method: {JsonString(tool.HttpMethod)},");

            if (!string.IsNullOrEmpty(clientApiKey))
            {
                sb.AppendLine(CultureInfo.InvariantCulture, $"        headers: {{ \"Accept\": \"application/json\", \"Content-Type\": \"application/json\", {JsonString(apiKeyHeader)}: {JsonString(clientApiKey)} }},");
            }
            else
            {
                sb.AppendLine("        headers: { \"Accept\": \"application/json\", \"Content-Type\": \"application/json\" },");
            }

            sb.AppendLine("        body: JSON.stringify(input)");
            sb.AppendLine("      });");
        }
        else
        {
            sb.AppendLine(CultureInfo.InvariantCulture, $"      const r = await fetch({JsonString(tool.Route)}, {{");
            sb.AppendLine(CultureInfo.InvariantCulture, $"        method: {JsonString(tool.HttpMethod)},");

            if (!string.IsNullOrEmpty(clientApiKey))
            {
                sb.AppendLine(CultureInfo.InvariantCulture, $"        headers: {{ \"Accept\": \"application/json\", {JsonString(apiKeyHeader)}: {JsonString(clientApiKey)} }}");
            }
            else
            {
                sb.AppendLine("        headers: { \"Accept\": \"application/json\" }");
            }

            sb.AppendLine("      });");
        }

        sb.AppendLine("      if (!r.ok) return { error: r.status + \" \" + r.statusText };");
        sb.AppendLine("      return await r.json();");
        sb.AppendLine("    }");
    }

    // ── Schema derivation ────────────────────────────────────────────────────

    private static List<(string Name, string JsonType, string Format)> GetSchemaProperties(
        Type requestType,
        string toolName,
        ILogger logger)
    {
        var result = new List<(string, string, string)>();

        foreach (var prop in requestType.GetProperties(BindingFlags.Public | BindingFlags.Instance))
        {
            if (!prop.CanWrite)
            {
                continue;
            }

            var (jsonType, format) = MapClrTypeToJsonSchema(prop.PropertyType);
            if (string.IsNullOrEmpty(jsonType))
            {
                // Why this is reported rather than skipped quietly: the property simply will not
                // appear in the tool's schema, so the agent cannot supply it and gets no hint that
                // the call it just made was structurally incomplete.
                WebMcpLog.SchemaPropertySkipped(
                    logger,
                    toolName,
                    prop.Name,
                    prop.PropertyType.FullName ?? prop.PropertyType.Name);
                continue;
            }

            WebMcpLog.SchemaPropertyMapped(logger, toolName, prop.Name, jsonType, format);
            result.Add((prop.Name, jsonType, format));
        }

        return result;
    }

    private static (string JsonType, string Format) MapClrTypeToJsonSchema(Type clrType)
    {
        // Unwrap Nullable<T>
        var underlying = Nullable.GetUnderlyingType(clrType);
        if (underlying is not null)
        {
            return MapClrTypeToJsonSchema(underlying);
        }

        if (clrType == typeof(string)) return ("string", string.Empty);
        if (clrType == typeof(bool)) return ("boolean", string.Empty);
        if (clrType == typeof(int)) return ("integer", string.Empty);
        if (clrType == typeof(long)) return ("integer", string.Empty);
        if (clrType == typeof(short)) return ("integer", string.Empty);
        if (clrType == typeof(double)) return ("number", string.Empty);
        if (clrType == typeof(float)) return ("number", string.Empty);
        if (clrType == typeof(decimal)) return ("number", string.Empty);
        if (clrType == typeof(Guid)) return ("string", "uuid");
        if (clrType == typeof(DateTime)) return ("string", "date-time");
        if (clrType == typeof(DateTimeOffset)) return ("string", "date-time");
        if (clrType == typeof(DateOnly)) return ("string", "date");
        if (clrType == typeof(TimeOnly)) return ("string", "time");

        // Skip arrays, collections, nested objects
        return (string.Empty, string.Empty);
    }

    // ── Helpers ──────────────────────────────────────────────────────────────

    private static bool NeedsRequestBody(string httpMethod)
        => string.Equals(httpMethod, "POST", StringComparison.OrdinalIgnoreCase)
            || string.Equals(httpMethod, "PUT", StringComparison.OrdinalIgnoreCase)
            || string.Equals(httpMethod, "PATCH", StringComparison.OrdinalIgnoreCase);

    private static string JsonString(string value)
    {
        // Minimal JSON string escaping for JS output
        return "\"" + value
            .Replace("\\", "\\\\", StringComparison.Ordinal)
            .Replace("\"", "\\\"", StringComparison.Ordinal)
            .Replace("\n", "\\n", StringComparison.Ordinal)
            .Replace("\r", "\\r", StringComparison.Ordinal)
            + "\"";
    }

    private static string JsonKey(string name)
        => JsonString(name);
}
