using Fdw.Collections;
using Fdw.Collections.Attributes;
using System.Diagnostics.CodeAnalysis;

namespace Fdw.Data.Abstractions;

/// <summary>
/// Collection of sort directions for data queries.
/// Generated by TypeCollectionGenerator with high-performance lookups.
/// </summary>
[ExcludeFromCodeCoverage]
[TypeCollection(typeof(SortDirectionBase), typeof(ISortDirection), typeof(SortDirections))]
public abstract partial class SortDirections : TypeCollectionBase<SortDirectionBase, ISortDirection>
{
}
