using System;
using System.Threading;
using System.Threading.Tasks;
using Fdw.Collections.Attributes;
using Fdw.Commands.Data;
using Fdw.Commands.Data.Abstractions;
using Fdw.Data.Abstractions;
using Fdw.Data.MsSql.Logging;
using Fdw.Data.MsSql.Results;
using Fdw.Data.MsSql.Translators;
using Fdw.Results;
using Fdw.Services.Connections.Abstractions;
using Microsoft.Data.SqlClient;
using Microsoft.Extensions.Logging.Abstractions;

namespace Fdw.Data.MsSql;

/// <summary>
/// Translates ConfigurationDeleteCommand to T-SQL version-on-write soft-delete transaction.
/// Marks the existing current row as non-current and inserts a deleted version.
/// </summary>
/// <remarks>
/// <para>
/// Generates a transaction that implements the version-on-write soft-delete pattern:
/// <list type="bullet">
/// <item>UPDATE: Sets IsCurrent = 0, ModifyDate = SYSDATETIMEOFFSET() WHERE Id = @LogicalId AND IsCurrent = 1</item>
/// <item>INSERT: Copies the last version with IsCurrent = 1, IsDeleted = 1 (RowId generated by DEFAULT)</item>
/// </list>
/// </para>
/// </remarks>
[TypeOption(typeof(MsSqlDataCommandTranslators), "ConfigurationDelete", RestrictToCurrentCompilation = true)]
public sealed class MsSqlConfigurationDeleteTranslator : MsSqlDataCommandTranslatorBase
{
    /// <summary>
    /// Initializes a new instance of the <see cref="MsSqlConfigurationDeleteTranslator"/> class.
    /// </summary>
    public MsSqlConfigurationDeleteTranslator()
        : base("ConfigurationDelete")
    {
    }

    /// <summary>
    /// Translates a ConfigurationDeleteCommand to a T-SQL version-on-write soft-delete transaction.
    /// </summary>
    /// <param name="command">The data command to translate.</param>
    /// <param name="container">The container with schema metadata.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>A result containing the SqlCommand.</returns>
    public override Task<IGenericResult<SqlCommand>> Translate(
        IDataCommand command,
        IStorageContainer container,
        CancellationToken cancellationToken = default)
    {
        MsSqlConfigurationDeleteTranslatorLog.Translating(
            NullLogger<MsSqlConfigurationDeleteTranslator>.Instance, container?.Name ?? "<null>");

        try
        {
            if (container == null)
            {
                MsSqlConfigurationDeleteTranslatorLog.ContainerNull(
                    NullLogger<MsSqlConfigurationDeleteTranslator>.Instance);
                return Task.FromResult(
                    GenericResult<SqlCommand>.Failure(MsSqlDataResultCodes.ByName("ContainerNull")));
            }

            if (container.Path is not IDatabasePath dbPath)
            {
                MsSqlConfigurationDeleteTranslatorLog.InvalidContainerPath(
                    NullLogger<MsSqlConfigurationDeleteTranslator>.Instance, container.Name);
                return Task.FromResult(
                    GenericResult<SqlCommand>.Failure(MsSqlDataResultCodes.ByName("InvalidContainerPath")));
            }

            var dataObj = GetCommandData(command);
            if (dataObj == null || dataObj is not Guid logicalId)
            {
                MsSqlConfigurationDeleteTranslatorLog.MissingInputData(
                    NullLogger<MsSqlConfigurationDeleteTranslator>.Instance,
                    "ConfigurationDeleteCommand", container.Name);
                return Task.FromResult(
                    GenericResult<SqlCommand>.Failure(
                        MsSqlDataResultCodes.ByName("MissingInputData"),
                        ResultDetails.Create("CommandType", "ConfigurationDeleteCommand")));
            }

            // Why: a scoped delete retires every row belonging to an owner rather than one row keyed by its
            // own [Id] — the only way to retire a KVP property-collection child, whose identity is
            // (owner, Name) and which therefore has no [Id] column to key on.
            var ownerFk = (command as ConfigurationDeleteCommand)?.OwnerForeignKeyColumn;
            MsSqlConfigurationDeleteTranslatorLog.ResolvedDeleteKind(
                NullLogger<MsSqlConfigurationDeleteTranslator>.Instance,
                container.Name,
                string.IsNullOrEmpty(ownerFk) ? "version-on-write" : "scoped");
            var sqlCommand = string.IsNullOrEmpty(ownerFk)
                ? BuildVersionOnWriteDeleteStatement(dbPath, container.Name, logicalId)
                : BuildScopedDeleteStatement(dbPath, container, ownerFk, logicalId);

            MsSqlConfigurationDeleteTranslatorLog.Translated(
                NullLogger<MsSqlConfigurationDeleteTranslator>.Instance, container.Name);

            return Task.FromResult(GenericResult<SqlCommand>.Success(sqlCommand));
        }
        catch (Exception ex)
        {
            MsSqlConfigurationDeleteTranslatorLog.DeleteTranslationFailed(
                NullLogger<MsSqlConfigurationDeleteTranslator>.Instance, ex, container?.Name ?? "<null>", ex.Message);
            return Task.FromResult(
                GenericResult<SqlCommand>.Failure(
                    MsSqlDataResultCodes.ByName("DeleteTranslationFailed"),
                    ResultDetails.Create("ErrorMessage", ex.Message)));
        }
    }

    /// <summary>
    /// Builds a soft-delete that retires every row belonging to one owner, resolved through the container's
    /// declared foreign key.
    /// </summary>
    /// <remarks>
    /// Why: the mirror of the save translator's FK handling. The caller supplies the LOGICAL owner FK name
    /// it stamped on the way in (e.g. <c>MsSqlConnectionId</c>); the physical column
    /// (<c>MsSqlConnectionRowId</c>) and the owner's table come from the container's own key metadata, and
    /// the owner's current RowId is resolved by the same subquery the INSERT uses. Nothing is guessed from
    /// a column-name convention, and an unresolvable FK throws rather than retiring the wrong rows.
    /// </remarks>
    private static SqlCommand BuildScopedDeleteStatement(
        IDatabasePath dbPath,
        IStorageContainer container,
        string ownerLogicalFkColumn,
        Guid ownerLogicalId)
    {
        if (string.IsNullOrEmpty(dbPath.Schema))
        {
            // Why: reported as a defect (FDW rule) — a translator should return IGenericResult, not
            // throw. Left in place per instructions; the caller's try/catch converts it to a Failure.
            MsSqlConfigurationDeleteTranslatorLog.NoSchemaDefined(
                NullLogger<MsSqlConfigurationDeleteTranslator>.Instance, container.Name);
            throw new InvalidOperationException(
                $"Container {container.Name} has no schema defined. ConfigurationDelete requires a schema-qualified table path.");
        }

        var dialect = dbPath.Dialect;
        Func<string, string> qi = dialect.QuoteIdentifier;
        var p = dialect.ParameterPrefix;

        if (!TryResolveOwnerForeignKey(container, ownerLogicalFkColumn, out var physicalColumn, out var parentSchema, out var parentTable))
        {
            // Why: same throw-instead-of-result defect as above — logged, not converted.
            MsSqlConfigurationDeleteTranslatorLog.UnresolvableOwnerForeignKey(
                NullLogger<MsSqlConfigurationDeleteTranslator>.Instance, container.Name, ownerLogicalFkColumn);
            throw new InvalidOperationException(
                $"Container {container.Name} declares no foreign key matching logical owner column '{ownerLogicalFkColumn}'. " +
                "A scoped configuration delete cannot resolve the owner without it.");
        }

        var sql = $@"UPDATE {qi(dbPath.Schema)}.{qi(container.Name)}
  SET {qi("IsCurrent")} = 0, {qi("IsDeleted")} = 1, {qi("ModifyDate")} = SYSDATETIMEOFFSET()
  WHERE {qi(physicalColumn)} = (SELECT {qi("RowId")} FROM {qi(parentSchema)}.{qi(parentTable)} WHERE {qi("Id")} = {p}LogicalId AND {qi("IsCurrent")} = 1)
    AND {qi("IsCurrent")} = 1";

        var sqlCommand = CreateCommand(sql);
        AddParameter(sqlCommand, "LogicalId", ownerLogicalId);

        return sqlCommand;
    }

    /// <summary>
    /// Resolves a container's declared foreign key from its LOGICAL name (e.g. <c>MsSqlConnectionId</c>)
    /// to the physical FK column and the referenced table, using the container's key metadata.
    /// </summary>
    private static bool TryResolveOwnerForeignKey(
        IStorageContainer container,
        string ownerLogicalFkColumn,
        out string physicalColumn,
        out string parentSchema,
        out string parentTable)
    {
        physicalColumn = string.Empty;
        parentSchema = string.Empty;
        parentTable = string.Empty;

        if (container is not IDataContainer dataContainer)
            return false;

        var keys = dataContainer.Keys;
        for (var i = 0; i < keys.Count; i++)
        {
            var key = keys[i];
            if (!string.Equals(key.KeyType.Name, "Foreign", StringComparison.Ordinal))
                continue;
            if (key.KeyFields.Count == 0 || key.ReferencedContainer is null)
                continue;

            var fkColumn = key.KeyFields[0].LocalField.Name;

            // Why: the same physical->logical mapping the save translator applies ({Owner}RowId -> {Owner}Id),
            // so both halves of the cascade address the FK by the identical name.
            var logicalName = fkColumn.EndsWith("RowId", StringComparison.Ordinal)
                ? string.Concat(fkColumn.AsSpan(0, fkColumn.Length - "RowId".Length), "Id")
                : fkColumn;

            if (!string.Equals(logicalName, ownerLogicalFkColumn, StringComparison.Ordinal))
                continue;

            physicalColumn = fkColumn;
            parentSchema = key.ReferencedContainer.Parent.Name;
            parentTable = key.ReferencedContainer.Name;
            return true;
        }

        return false;
    }

    /// <summary>
    /// Builds a version-on-write T-SQL transaction for configuration soft-delete.
    /// </summary>
    private static SqlCommand BuildVersionOnWriteDeleteStatement(
        IDatabasePath dbPath,
        string tableName,
        Guid logicalId)
    {
        var dialect = dbPath.Dialect;

        if (string.IsNullOrEmpty(dbPath.Schema))
        {
            // Why: reported as a defect (FDW rule) — a translator should return IGenericResult, not
            // throw. Left in place per instructions; the caller's try/catch converts it to a Failure.
            MsSqlConfigurationDeleteTranslatorLog.NoSchemaDefined(
                NullLogger<MsSqlConfigurationDeleteTranslator>.Instance, tableName);
            throw new InvalidOperationException(
                $"Container {tableName} has no schema defined. ConfigurationDelete requires a schema-qualified table path.");
        }

        var schema = dbPath.Schema;
        Func<string, string> qi = dialect.QuoteIdentifier;
        var p = dialect.ParameterPrefix;

        // Why: soft-delete by marking the current row IsDeleted=1 + IsCurrent=0 in a single
        // UPDATE. The earlier tombstone-INSERT pattern reproduced only (Id, Name, IsCurrent,
        // IsDeleted) which violated NOT NULL on columns like ServiceOptionType. Marking the
        // existing row is simpler and avoids replicating per-table required-column lists.
        var sql = $@"UPDATE {qi(schema)}.{qi(tableName)}
  SET {qi("IsCurrent")} = 0, {qi("IsDeleted")} = 1, {qi("ModifyDate")} = SYSDATETIMEOFFSET()
  WHERE {qi("Id")} = {p}LogicalId AND {qi("IsCurrent")} = 1";

        var sqlCommand = CreateCommand(sql);
        AddParameter(sqlCommand, "LogicalId", logicalId);

        return sqlCommand;
    }
}
