using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Fdw.Collections.Attributes;
using Fdw.Commands.Data.Abstractions;
using Fdw.Conventions;
using Fdw.Data.Abstractions;
using Fdw.Data.Abstractions.Mappers.PocoMappers;
using Fdw.Data.MsSql.Logging;
using Fdw.Data.MsSql.Results;
using Fdw.Data.MsSql.Translators;
using Fdw.Results;
using Fdw.Services.Connections.Abstractions;
using Microsoft.Data.SqlClient;
using Microsoft.Extensions.Logging.Abstractions;

namespace Fdw.Data.MsSql;

/// <summary>
/// Translates ConfigurationSaveCommand to T-SQL version-on-write transaction.
/// Marks the existing current row as non-current and inserts a new current version.
/// </summary>
/// <remarks>
/// <para>
/// Generates a transaction that implements the version-on-write pattern:
/// <list type="bullet">
/// <item>UPDATE: Sets IsCurrent = 0, ModifyDate = SYSDATETIMEOFFSET() WHERE Id = @LogicalId AND IsCurrent = 1</item>
/// <item>INSERT: Inserts new row with IsCurrent = 1, IsDeleted = 0 (RowId generated by DEFAULT)</item>
/// </list>
/// </para>
/// </remarks>
[TypeOption(typeof(MsSqlDataCommandTranslators), "ConfigurationSave", RestrictToCurrentCompilation = true)]
public sealed class MsSqlConfigurationSaveTranslator : MsSqlDataCommandTranslatorBase
{
    /// <summary>
    /// Initializes a new instance of the <see cref="MsSqlConfigurationSaveTranslator"/> class.
    /// </summary>
    public MsSqlConfigurationSaveTranslator()
        : base("ConfigurationSave")
    {
    }

    /// <summary>
    /// Translates a ConfigurationSaveCommand to a T-SQL version-on-write transaction.
    /// </summary>
    /// <param name="command">The data command to translate.</param>
    /// <param name="container">The container with schema metadata.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>A result containing the SqlCommand.</returns>
    // MA0051: Method length acceptable - sequential SQL transaction generation (reflection, UPDATE, INSERT, parameters)
#pragma warning disable MA0051 // Method is too long
    public override Task<IGenericResult<SqlCommand>> Translate(
        IDataCommand command,
        IStorageContainer container,
        CancellationToken cancellationToken = default)
#pragma warning restore MA0051
    {
        MsSqlConfigurationSaveTranslatorLog.Translating(
            NullLogger<MsSqlConfigurationSaveTranslator>.Instance, container?.Name ?? "<null>");

        try
        {
            if (container == null)
            {
                MsSqlConfigurationSaveTranslatorLog.ContainerNull(
                    NullLogger<MsSqlConfigurationSaveTranslator>.Instance);
                return Task.FromResult(
                    GenericResult<SqlCommand>.Failure(MsSqlDataResultCodes.ByName("ContainerNull")));
            }

            if (container.Path is not IDatabasePath dbPath)
            {
                MsSqlConfigurationSaveTranslatorLog.InvalidContainerPath(
                    NullLogger<MsSqlConfigurationSaveTranslator>.Instance, container.Name);
                return Task.FromResult(
                    GenericResult<SqlCommand>.Failure(MsSqlDataResultCodes.ByName("InvalidContainerPath")));
            }

            var dataObj = GetCommandData(command);
            if (dataObj == null)
            {
                MsSqlConfigurationSaveTranslatorLog.MissingInputData(
                    NullLogger<MsSqlConfigurationSaveTranslator>.Instance,
                    "ConfigurationSaveCommand", container.Name);
                return Task.FromResult(
                    GenericResult<SqlCommand>.Failure(
                        MsSqlDataResultCodes.ByName("MissingInputData"),
                        ResultDetails.Create("CommandType", "ConfigurationSaveCommand")));
            }

            var extra = (command as IConfigurationSaveCommand)?.AdditionalColumnValues;

            var sqlCommand = BuildVersionOnWriteSaveStatement(dbPath, container, dataObj, extra);

            MsSqlConfigurationSaveTranslatorLog.Translated(
                NullLogger<MsSqlConfigurationSaveTranslator>.Instance, container.Name, sqlCommand.Parameters.Count);

            return Task.FromResult(GenericResult<SqlCommand>.Success(sqlCommand));
        }
        catch (Exception ex)
        {
            MsSqlConfigurationSaveTranslatorLog.SaveTranslationFailed(
                NullLogger<MsSqlConfigurationSaveTranslator>.Instance, ex, container?.Name ?? "<null>", ex.Message);
            return Task.FromResult(
                GenericResult<SqlCommand>.Failure(
                    MsSqlDataResultCodes.ByName("InsertTranslationFailed"),
                    ResultDetails.Create("ErrorMessage", ex.Message)));
        }
    }

    /// <summary>
    /// Columns always excluded from INSERT — version-on-write managed or C#-only properties.
    /// </summary>
    private static readonly HashSet<string> AlwaysExcluded = new(StringComparer.Ordinal)
    {
        "IsCurrent", "IsDeleted", "ServiceType", "SectionName"
    };

    /// <summary>
    /// Fallback exclusions when container has no field metadata.
    /// </summary>
    private static readonly HashSet<string> FallbackExcluded = new(StringComparer.Ordinal)
    {
        "RowId", "IsCurrent", "IsDeleted", "ServiceType", "SectionName",
        "CreateDate", "CreateBy", "CreateOnBehalfOf",
        "ModifyDate", "ModifyBy", "ModifyOnBehalfOf", "SrcCreateDate"
    };

    /// <summary>
    /// Builds a version-on-write T-SQL transaction for configuration save.
    /// </summary>
    /// <remarks>
    /// Why: Intersects PocoMapper properties with container field metadata to determine
    /// which columns to INSERT. Only properties that exist in both the mapper AND the
    /// container's field list are included. This handles parent/child table splits
    /// automatically — the container defines exactly which columns it has.
    ///
    /// FK columns (e.g., ConnectionRowId) are NOT on the C# POCO — only the logical Id
    /// (ConnectionId) is. When the container carries FK resolution metadata, those columns
    /// are inserted via a subquery instead of a direct parameter, resolving the parent RowId
    /// at write time via the version-on-write pattern.
    /// </remarks>
    [ConventionOverride(MaxMethodLines = 70)]  // Sequential field-set calculation + version-on-write transaction; not possible to extract without breaking the logical flow
    private static SqlCommand BuildVersionOnWriteSaveStatement(
        IDatabasePath dbPath,
        IStorageContainer container,
        object data,
        IReadOnlyDictionary<string, object?>? extra)
    {
        var dialect = dbPath.Dialect;

        if (string.IsNullOrEmpty(dbPath.Schema))
        {
            MsSqlConfigurationSaveTranslatorLog.NoSchemaDefined(
                NullLogger<MsSqlConfigurationSaveTranslator>.Instance, container.Name);
            throw new InvalidOperationException(
                $"Container {container.Name} has no schema defined. ConfigurationSave requires a schema-qualified table path.");
        }

        var schema = dbPath.Schema;
        var table = container.Name;
        var dataType = data.GetType();

        // Shorthand helpers — keep quoting consistent throughout this method.
        Func<string, string> qi = dialect.QuoteIdentifier;
        var p = dialect.ParameterPrefix;

        var mapper = PocoMapperCollection.ByName(dataType.Name);
        if (mapper == PocoMapperCollection.NotFound)
        {
            MsSqlConfigurationSaveTranslatorLog.NoPocoMapperRegistered(
                NullLogger<MsSqlConfigurationSaveTranslator>.Instance, dataType.Name);
            throw new InvalidOperationException(
                $"No PocoMapper registered for type {dataType.Name}. Ensure it has [GenerateMapper].");
        }

        var allParameters = new Dictionary<string, object?>(mapper.MapToParameters(data), StringComparer.Ordinal);
        var allPropertyNames = new List<string>(mapper.GetPropertyNames());
        var mapperPropertySet = new HashSet<string>(allPropertyNames, StringComparer.Ordinal);
        MergeAdditionalColumns(extra, allParameters, allPropertyNames, mapperPropertySet);

        var containerFields = BuildInsertableFieldSet(container);

        var notNullFieldNames = BuildNotNullFieldSet(container);

        var columnNames = allPropertyNames
            .Where(n => !AlwaysExcluded.Contains(n)
                        && (containerFields == null || containerFields.Contains(n))
                        && !(notNullFieldNames.Contains(n) && IsParamValueNull(allParameters, n)))
            .ToList();

        var fkResolutions = ResolveForeignKeys(container, containerFields, mapperPropertySet);

        if (columnNames.Count == 0 && fkResolutions.Count == 0)
        {
            MsSqlConfigurationSaveTranslatorLog.NoInsertableColumns(
                NullLogger<MsSqlConfigurationSaveTranslator>.Instance, dataType.Name, table);
            throw new InvalidOperationException(
                $"No insertable columns for type {dataType.Name} in container {table}. " +
                $"Verify container field metadata is seeded and property names match column names.");
        }

        allParameters.TryGetValue("Id", out var logicalId);

        var tableHasIdColumn = containerFields is null
            || containerFields.Contains("Id", StringComparer.Ordinal);
        var hasIdInColumns = columnNames.Any(n => string.Equals(n, "Id", StringComparison.Ordinal));

        // Build column and value lists — mapper columns use @Param, FK columns use subquery
        var insertColumns = new List<string>(columnNames.Count + fkResolutions.Count + 1);
        var insertValues = new List<string>(columnNames.Count + fkResolutions.Count + 1);

        if (tableHasIdColumn && !hasIdInColumns)
        {
            insertColumns.Add(qi("Id"));
            insertValues.Add($"{p}LogicalId");
        }

        foreach (var name in columnNames)
        {
            insertColumns.Add(qi(name));
            insertValues.Add($"{p}{name}");
        }

        foreach (var fk in fkResolutions)
        {
            insertColumns.Add(qi(fk.FkColumnName));
            insertValues.Add(
                $"(SELECT {qi("RowId")} FROM {qi(fk.ParentSchema)}.{qi(fk.ParentTableName)} WHERE {qi("Id")} = {p}{fk.LogicalIdParameterName} AND {qi("IsCurrent")} = 1)");
        }

        var insertColumnList = string.Join(", ", insertColumns);
        var insertParamList = string.Join(", ", insertValues);

        // Version-on-write UPDATE predicate: use [Id] when the table has one; otherwise the logical FK
        // (or, for a KVP child, the FK+Name natural key) that identifies the row across versions.
        var updatePredicate = ResolveUpdatePredicate(
            container, columnNames, tableHasIdColumn, qi, p, dialect.AlwaysFalsePredicate);

        var sql = $@"BEGIN TRANSACTION
  UPDATE {qi(schema)}.{qi(table)} SET {qi("IsCurrent")} = 0, {qi("ModifyDate")} = SYSDATETIMEOFFSET()
    WHERE {updatePredicate} AND {qi("IsCurrent")} = 1
  INSERT INTO {qi(schema)}.{qi(table)} ({insertColumnList}, {qi("IsCurrent")}, {qi("IsDeleted")})
    VALUES ({insertParamList}, 1, 0)
COMMIT";

        var sqlCommand = CreateCommand(sql);

        AddParameter(sqlCommand, "LogicalId", logicalId);

        foreach (var name in columnNames)
        {
            allParameters.TryGetValue(name, out var value);
            AddParameter(sqlCommand, name, value);
        }

        return sqlCommand;
    }

    /// <summary>
    /// Resolves the version-on-write UPDATE predicate: <c>[Id]</c> when the table has one; the
    /// (ownerFk, Name) natural key for a KVP child (see <see cref="TryGetPropertyCollectionKeyField"/>);
    /// otherwise the first FK-style column identifying the row across versions.
    /// </summary>
    private static string ResolveUpdatePredicate(
        IStorageContainer container,
        List<string> columnNames,
        bool tableHasIdColumn,
        Func<string, string> qi,
        string p,
        string alwaysFalsePredicate)
    {
        if (tableHasIdColumn)
            return $"{qi("Id")} = {p}LogicalId";

        if (TryGetPropertyCollectionKeyField(container, out var ownerFkCol)
            && columnNames.Contains(ownerFkCol) && columnNames.Contains("Name"))
        {
            return $"{qi(ownerFkCol)} = {p}{ownerFkCol} AND {qi("Name")} = {p}Name";
        }

        if (columnNames.Count > 0)
        {
            // First FK-style column on a typed body acts as the logical identifier.
            // For conn.MsSqlConnection that's ConnectionId.
            var fkCol = columnNames.FirstOrDefault(n => n.EndsWith("Id", StringComparison.Ordinal)) ?? columnNames[0];
            return $"{qi(fkCol)} = {p}{fkCol}";
        }

        return alwaysFalsePredicate; // No identifying column — fall through to INSERT only.
    }

    /// <summary>
    /// Merges <see cref="IConfigurationSaveCommand.AdditionalColumnValues"/> into the mapper's candidate
    /// parameter/property sets BEFORE the container-field intersection, so an injected column (e.g. a
    /// KVP child's owner FK) flows through the same INSERT pipeline as mapped columns.
    /// </summary>
    private static void MergeAdditionalColumns(
        IReadOnlyDictionary<string, object?>? extra,
        Dictionary<string, object?> allParameters,
        List<string> allPropertyNames,
        HashSet<string> mapperPropertySet)
    {
        if (extra is not { Count: > 0 })
            return;

        foreach (var kv in extra)
        {
            allParameters[kv.Key] = kv.Value;
            if (mapperPropertySet.Add(kv.Key))
                allPropertyNames.Add(kv.Key);
        }
    }

    /// <summary>
    /// Finds FK columns in the container that are absent from the mapper and have a resolution entry.
    /// </summary>
    /// <remarks>
    /// Why: FK RowId columns are physical-only — no corresponding C# property exists on the POCO.
    /// The resolution record tells us which parent table to subquery and which logical Id to use.
    /// </remarks>
    private static List<ForeignKeyResolution> ResolveForeignKeys(
        IStorageContainer container,
        HashSet<string>? containerFields,
        HashSet<string> mapperPropertySet)
    {
        var result = new List<ForeignKeyResolution>();

        if (container is not IDataContainer dataContainer)
            return result;
        var keys = dataContainer.Keys;
        for (var i = 0; i < keys.Count; i++)
        {
            var key = keys[i];
            if (!string.Equals(key.KeyType.Name, "Foreign", StringComparison.Ordinal))
                continue;
            if (key.KeyFields.Count == 0)
                continue;
            var referencedContainer = key.ReferencedContainer;
            if (referencedContainer is null)
                continue;

            var fkColName = key.KeyFields[0].LocalField.Name;

            // Only include FK columns that actually exist in the insertable field set
            // and are genuinely absent from the mapper (so we emit subquery, not duplicate param).
            if (mapperPropertySet.Contains(fkColName))
                continue;
            if (containerFields != null && !containerFields.Contains(fkColName))
                continue;

            var logicalIdParam = fkColName.EndsWith("RowId", StringComparison.Ordinal)
                ? fkColName[..^"RowId".Length] + "Id"
                : fkColName;

            if (!mapperPropertySet.Contains(logicalIdParam))
                continue;

            result.Add(new ForeignKeyResolution(
                fkColName,
                referencedContainer.Parent.Name,
                referencedContainer.Name,
                logicalIdParam));
        }

        return result;
    }

    /// <summary>
    /// Finds the container's declared PropertyCollection key — the owner FK column that, together with
    /// <c>Name</c>, forms a KVP child row's natural key — via container key metadata (NO per-type branch).
    /// </summary>
    /// <remarks>
    /// Why: a KVP child table (e.g. <c>conn.MsSqlConnectionAuthentication</c>) has no single-column
    /// logical identity — its rows are versioned per (owner, Name), not per owner alone. Driving this
    /// off the <c>PropertyCollection</c> key-type metadata (rather than a hardcoded column-name guess)
    /// keeps the mechanism generic across every KVP child container.
    /// </remarks>
    private static bool TryGetPropertyCollectionKeyField(IStorageContainer container, out string field)
    {
        field = string.Empty;
        if (container is not IDataContainer dataContainer)
            return false;

        var keys = dataContainer.Keys;
        for (var i = 0; i < keys.Count; i++)
        {
            var key = keys[i];
            if (!string.Equals(key.KeyType.Name, "PropertyCollection", StringComparison.Ordinal))
                continue;
            if (key.KeyFields.Count == 0)
                continue;

            field = key.KeyFields[0].LocalField.Name;
            return true;
        }

        return false;
    }

    /// <summary>
    /// Returns the set of NOT NULL column names declared by the container's field metadata.
    /// Used to decide whether to omit a null-valued column from INSERT (so the DB default applies).
    /// </summary>
    private static HashSet<string> BuildNotNullFieldSet(IStorageContainer container)
    {
        var result = new HashSet<string>(StringComparer.Ordinal);
        var fields = container.Schema?.Fields;
        if (fields is not { Count: > 0 }) return result;
        foreach (var field in fields)
        {
            if (!field.IsNullable) result.Add(field.Name);
        }
        return result;
    }

    private static bool IsParamValueNull(Dictionary<string, object?> parameters, string name)
        => !parameters.TryGetValue(name, out var v) || v is null;

    /// <summary>
    /// Builds the set of insertable column names from container field metadata.
    /// Returns null when no metadata available (backward compat — falls back to excluding FallbackExcluded).
    /// </summary>
    private static HashSet<string>? BuildInsertableFieldSet(IStorageContainer container)
    {
        var fields = container.Schema?.Fields;
        if (fields is not { Count: > 0 })
        {
            return null;
        }

        var insertable = new HashSet<string>(StringComparer.Ordinal);

        foreach (var field in fields)
        {
            if (field.IsSystemProvided || field.IsIdentity || field.IsComputed)
                continue;

            insertable.Add(field.Name);
        }

        return insertable;
    }
}
