using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Fdw.Collections.Attributes;
using Fdw.Commands.Data.Abstractions;
using Fdw.Data.Abstractions;
using Fdw.Data.MsSql.Logging;
using Fdw.Data.MsSql.Results;
using Fdw.Data.MsSql.Translators;
using Fdw.Results;
using Fdw.Services.Connections.Abstractions;
using Microsoft.Data.SqlClient;
using Microsoft.Extensions.Logging.Abstractions;

namespace Fdw.Data.MsSql;

/// <summary>
/// Translates InsertCommand to T-SQL INSERT statement.
/// </summary>
/// <remarks>
/// <para>
/// Builds T-SQL INSERT statements with:
/// <list type="bullet">
/// <item>INSERT INTO - container's physical name</item>
/// <item>Column list - from container schema (excludes identity columns)</item>
/// <item>VALUES clause - parameterized values from command data</item>
/// <item>SELECT SCOPE_IDENTITY() - returns generated identity value</item>
/// </list>
/// </para>
/// <para>
/// Excludes identity columns from INSERT (auto-generated by database).
/// Returns the newly generated identity value or affected row count.
/// </para>
/// </remarks>
[TypeOption(typeof(MsSqlDataCommandTranslators), "Insert", RestrictToCurrentCompilation = true)]
public sealed class MsSqlInsertTranslator : MsSqlDataCommandTranslatorBase
{
    /// <summary>
    /// Initializes a new instance of the <see cref="MsSqlInsertTranslator"/> class.
    /// </summary>
    public MsSqlInsertTranslator()
        : base("Insert")
    {
    }

    /// <summary>
    /// Translates an InsertCommand to a T-SQL INSERT statement.
    /// </summary>
    /// <param name="command">The data command to translate.</param>
    /// <param name="container">The container with schema metadata.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>A result containing the SqlCommand.</returns>
    public override Task<IGenericResult<SqlCommand>> Translate(
        IDataCommand command,
        IStorageContainer container,
        CancellationToken cancellationToken = default)
    {
        MsSqlInsertTranslatorLog.Translating(
            NullLogger<MsSqlInsertTranslator>.Instance, container?.Name ?? "<null>");

        try
        {
            if (container == null)
            {
                MsSqlInsertTranslatorLog.ContainerNull(NullLogger<MsSqlInsertTranslator>.Instance);
                return Task.FromResult(
                    GenericResult<SqlCommand>.Failure(MsSqlDataResultCodes.ByName("ContainerNull")));
            }

            // Validate container path is a database path
            if (container.Path is not IDatabasePath dbPath)
            {
                MsSqlInsertTranslatorLog.InvalidContainerPath(
                    NullLogger<MsSqlInsertTranslator>.Instance, container.Name);
                return Task.FromResult(
                    GenericResult<SqlCommand>.Failure(MsSqlDataResultCodes.ByName("InvalidContainerPath")));
            }

            // Get entity data from command
            var dataObj = GetCommandData(command);
            if (dataObj == null)
            {
                MsSqlInsertTranslatorLog.MissingInputData(
                    NullLogger<MsSqlInsertTranslator>.Instance, "InsertCommand", container.Name);
                return Task.FromResult(
                    GenericResult<SqlCommand>.Failure(
                        MsSqlDataResultCodes.ByName("MissingInputData"),
                        ResultDetails.Create("CommandType", "InsertCommand")));
            }

            // Build INSERT statement
            var sqlCommand = BuildInsertStatement(container, dbPath, dataObj);

            MsSqlInsertTranslatorLog.Translated(
                NullLogger<MsSqlInsertTranslator>.Instance, container.Name, sqlCommand.Parameters.Count);

            return Task.FromResult(GenericResult<SqlCommand>.Success(sqlCommand));
        }
        catch (Exception ex)
        {
            MsSqlInsertTranslatorLog.InsertTranslationFailed(
                NullLogger<MsSqlInsertTranslator>.Instance, ex, container?.Name ?? "<null>", ex.Message);
            return Task.FromResult(
                GenericResult<SqlCommand>.Failure(
                    MsSqlDataResultCodes.ByName("InsertTranslationFailed"),
                    ResultDetails.Create("ErrorMessage", ex.Message)));
        }
    }

    /// <summary>
    /// Builds a complete T-SQL INSERT statement.
    /// </summary>
    private static SqlCommand BuildInsertStatement(
        IStorageContainer container,
        IDatabasePath dbPath,
        object data)
    {
        // Exclude system-provided columns (IDENTITY, COMPUTED, DEFAULT-filled like NEWSEQUENTIALID()).
        // IsSystemProvided is the superset; legacy IsIdentity / IsComputed retained for back-compat with
        // schemas that haven't been migrated to set IsSystemProvided.
        var fields = container.Schema.Fields
            .Where(f => !f.IsIdentity && !f.IsComputed && !f.IsSystemProvided)
            .ToList();

        if (fields.Count == 0)
        {
            // Why: reported as a defect (FDW rule) — a translator should return IGenericResult, not
            // throw. Left in place per instructions; the caller's try/catch converts it to a Failure.
            MsSqlInsertTranslatorLog.NoInsertableFields(
                NullLogger<MsSqlInsertTranslator>.Instance, container.Name);
            throw new InvalidOperationException($"Container {container.Name} has no insertable fields");
        }

        var allFieldNames = fields.Select(f => f.Name).ToList();

        // Only include fields that have matching properties on the data object
        var dataType = data.GetType();
        var fieldNames = allFieldNames.Where(f => dataType.GetProperty(f) != null).ToList();

        if (fieldNames.Count == 0)
        {
            // Why: same throw-instead-of-result defect as above — logged, not converted.
            MsSqlInsertTranslatorLog.NoMatchingProperties(
                NullLogger<MsSqlInsertTranslator>.Instance, container.Name);
            throw new InvalidOperationException(
                $"Data object has no properties matching insertable fields for container {container.Name}");
        }

        var dialect = dbPath.Dialect;

        // Build column list
        var columnList = string.Join(", ", fieldNames.Select(f => dialect.QuoteIdentifier(f)));

        // Build parameter list
        var prefix = dialect.ParameterPrefix;
        var paramList = string.Join(", ", fieldNames.Select(f => $"{prefix}{f}"));

        // Build INSERT statement with SCOPE_IDENTITY() to return generated ID
        // Why BIGINT: OpsDb identity columns are BIGINT IDENTITY; INT cast risks overflow on large tables.
        var sql = $"INSERT INTO {BuildQualifiedTableName(dbPath)} ({columnList}) VALUES ({paramList}); SELECT CAST(SCOPE_IDENTITY() AS BIGINT);";

        var command = CreateCommand(sql);
        AddParametersFromObject(data, fieldNames, (n, v) => AddParameter(command, n, v));

        return command;
    }
}
