using Fdw.Collections;
using Fdw.Collections.Attributes;
using System.Diagnostics.CodeAnalysis;

namespace Fdw.Web.Http.Abstractions.Policies;

/// <summary>
/// Collection of rate limit policies for HTTP operations.
/// Generated by TypeCollectionGenerator with high-performance lookups.
/// </summary>
[ExcludeFromCodeCoverage]
[TypeCollection(typeof(RateLimitPolicyBase), typeof(IRateLimitPolicy), typeof(RateLimitPolicies))]
public partial class RateLimitPolicies : TypeCollectionBase<RateLimitPolicyBase, IRateLimitPolicy>
{
}