<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net10.0;netstandard2.0</TargetFrameworks>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <RootNamespace>$namespace$.$serviceName$.Abstractions</RootNamespace>
    <Description>Abstractions for $serviceName$ services in Fdw</Description>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Fdw.Abstractions" Version="$$(FractalDataWorksVersion)" />
    <PackageReference Include="Fdw.Configuration.Abstractions" Version="$$(FractalDataWorksVersion)" />
    <PackageReference Include="Fdw.Results" Version="$$(FractalDataWorksVersion)" />
    <PackageReference Include="Fdw.ServiceTypes" Version="$$(FractalDataWorksVersion)" />
  </ItemGroup>

</Project>
