using System.Diagnostics.CodeAnalysis;
using Fdw.Collections;
using Fdw.Services;
using Fdw.Services.Abstractions;
using Fdw.ServiceTypes;
using Fdw.Services.SecretManagers.Abstractions;
using Fdw.ServiceTypes.Logging;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Logging.Abstractions;
using System;

namespace Fdw.Services.SecretManagers;

/// <summary>
/// Collection of secret manager service types.
/// Generated by ServiceTypeCollectionGenerator with high-performance lookups.
/// </summary>
[ExcludeFromCodeCoverage]
[ServiceTypeCollection(
    typeof(SecretManagerTypeBase<ISecretManager, ISecretManagerServiceFactory<ISecretManager, SecretManagerConfiguration>, SecretManagerConfiguration>),
    typeof(ISecretManagerType),
    typeof(SecretManagerTypes),
    GenerateProvider = true,
    ServiceInterface = typeof(ISecretManager),
    ConfigurationType = typeof(SecretManagerConfiguration),
    ProviderType = typeof(DefaultSecretManagerProvider),
    ProviderInterface = typeof(IFdwServiceProvider<ISecretManager, SecretManagerConfiguration>),
    ServiceCategory = "SecretManager",
    // Why there is no lifetime here any more: ProviderLifetime was removed from
    // ServiceTypeCollectionAttribute, and ServiceTypeCollectionGenerator now registers EVERY domain
    // provider AddScoped so factory lambdas may legally hold scoped dependencies. This domain
    // previously pinned Singleton so a Singleton connection factory could take
    // IFdwServiceProvider<ISecretManager, SecretManagerConfiguration> as a plain constructor
    // dependency; with the provider scoped, any Singleton consumer resolving it from the ROOT
    // container captures a scoped instance. Nothing in this domain is scoped, so the registration
    // itself is safe — the risk lives at the consumers, which is why secret resolution moved onto
    // the factory rather than staying a provider a factory holds.
    Group = 0)]
public partial class SecretManagerTypes : ServiceTypeCollectionBase<
    SecretManagerTypeBase<ISecretManager, ISecretManagerServiceFactory<ISecretManager, SecretManagerConfiguration>, SecretManagerConfiguration>,
    ISecretManagerType<ISecretManager, ISecretManagerServiceFactory<ISecretManager, SecretManagerConfiguration>, SecretManagerConfiguration>>
{
    // Configure(), Register() and Initialize() are source-generated

    /// <summary>
    /// Sets this collection's Register body: the option sweep, then this domain's provider.
    /// </summary>
    /// <remarks>
    /// The provider is one registration for the whole collection and this declaration already names it,
    /// so the body that registers it is written here beside the declaration. Setting it as the phase's
    /// body is what makes it replaceable: an application calling <c>Registration(...)</c> replaces the
    /// sweep and this registration together, which is the correct semantic for a host taking over phase 2.
    /// </remarks>
    static SecretManagerTypes()
    {
        var sweepOptions = RegisterFunc;
        Registration((builder, loggerFactory) =>
        {
            sweepOptions(builder, loggerFactory);
            builder.Services.AddScoped<IFdwServiceProvider<ISecretManager, SecretManagerConfiguration>>(sp =>
            {
                var provider = new DefaultSecretManagerProvider(
                    sp,
                    sp.GetService<ILoggerFactory>()?.CreateLogger<DefaultSecretManagerProvider>()
                    ?? NullLogger<DefaultSecretManagerProvider>.Instance);
                var stLogger = sp.GetService<ILoggerFactory>()?.CreateLogger("SecretManagerTypes");
                try
                {
                    if (sp.GetService<IServiceConfigurationProvider<SecretManagerConfiguration>>() is { } cfgProvider)
                    {
                        // Why the result is read: a provider that did not take its parent still constructs, and
                        // every later read silently misses. The failure has to be said out loud here or nowhere.
                        var parentResult = provider.Register(cfgProvider);
                        if (!parentResult.IsSuccess && stLogger != null)
                            ServiceTypeLog.FactoryRegistrationFailed(stLogger, "SecretManagerTypes", parentResult.CurrentMessage ?? "SecretManagerTypes");
                    }
                }
                catch (Exception ex)
                {
                    // Why rethrow: a throw here was previously silent, and a provider that failed to take
                    // its parent is unusable in a way that only surfaces much later.
                    if (stLogger != null) ServiceTypeLog.FactoryRegistrationException(stLogger, ex, "SecretManagerTypes");
                    throw;
                }
                return provider;
            });
            return builder;
        });
    }
}
