using System.Diagnostics.CodeAnalysis;
using Fdw.Collections;
using Fdw.Services;
using Fdw.Services.Abstractions;
using Fdw.ServiceTypes;
using Fdw.Services.SecretManagers.Abstractions;
using Fdw.ServiceTypes.Logging;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Logging.Abstractions;
using System;
using System.Linq;
using Fdw.Results;
using Microsoft.Extensions.Hosting;
using Fdw.Configuration;
using Fdw.Services.Configuration;
using Fdw.Services.Data.Abstractions;
using Fdw.Services.SecretManagers.Commands;
using Fdw.Services.SecretManagers.Logging;
using Microsoft.Extensions.DependencyInjection.Extensions;
using Microsoft.Extensions.Options;
using System.Collections.Concurrent;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Threading;

namespace Fdw.Services.SecretManagers;

/// <summary>
/// Collection of secret manager service types.
/// Generated by ServiceTypeCollectionGenerator with high-performance lookups.
/// </summary>
[ExcludeFromCodeCoverage]
[ServiceTypeCollection(
    typeof(SecretManagerTypeBase<ISecretManager, ISecretManagerServiceFactory<ISecretManager, SecretManagerConfiguration>, SecretManagerConfiguration>),
    typeof(ISecretManagerType),
    typeof(SecretManagerTypes),
    GenerateProvider = true,
    ServiceInterface = typeof(ISecretManager),
    ConfigurationType = typeof(SecretManagerConfiguration),
    ProviderType = typeof(DefaultSecretManagerProvider),
    ProviderInterface = typeof(IPlatformServiceProvider<ISecretManager, SecretManagerConfiguration>),
    ServiceCategory = "SecretManager",
    // Why there is no lifetime here any more: ProviderLifetime was removed from
    // ServiceTypeCollectionAttribute, and ServiceTypeCollectionGenerator now registers EVERY domain
    // provider AddScoped so factory lambdas may legally hold scoped dependencies. This domain
    // previously pinned Singleton so a Singleton connection factory could take
    // IPlatformServiceProvider<ISecretManager, SecretManagerConfiguration> as a plain constructor
    // dependency; with the provider scoped, any Singleton consumer resolving it from the ROOT
    // container captures a scoped instance. Nothing in this domain is scoped, so the registration
    // itself is safe — the risk lives at the consumers, which is why secret resolution moved onto
    // the factory rather than staying a provider a factory holds.
    Group = 0)]
public partial class SecretManagerTypes : ServiceTypeCollectionBase<
    SecretManagerTypeBase<ISecretManager, ISecretManagerServiceFactory<ISecretManager, SecretManagerConfiguration>, SecretManagerConfiguration>,
    ISecretManagerType<ISecretManager, ISecretManagerServiceFactory<ISecretManager, SecretManagerConfiguration>, SecretManagerConfiguration>>
{
    // Configure(), Register() and Initialize() are source-generated

    /// <summary>
    /// Sets this collection's Register body: the option collect, then this domain's provider.
    /// </summary>
    /// <remarks>
    /// The provider is one registration for the whole collection and this declaration already names it,
    /// so the body that registers it is written here beside the declaration. Setting it as the phase's
    /// body is what makes it replaceable: an application calling <c>Registration(...)</c> replaces the
    /// collect and this registration together, which is the correct semantic for a host taking over phase 2.
    /// </remarks>
    static SecretManagerTypes()
    {
        var collectOptions = RegisterFunc;

        // Why a local: this closed generic is the DI key a consumer injects, and it is reported at
        // three points below — the deferred declaration, the milestone, and the zero-option warning.
        // Written out three times it is three chances for them to disagree.
        var providerService = typeof(IPlatformServiceProvider<ISecretManager, SecretManagerConfiguration>).ToString();

        Registration((builder, loggerFactory) =>
        {
            var log = loggerFactory?.CreateLogger<SecretManagerTypes>() ?? NullLogger<SecretManagerTypes>.Instance;

            // Why the result is read: this replacement calls the func it captured, and discarding
            // what that returned meant an option that failed to register was followed by this body
            // registering the provider anyway and reporting success.
            var registered = collectOptions(builder, loggerFactory);
            if (registered.IsFailure)
                return registered;
            // SecretManager configuration, registered once for the domain here rather
            // than by every caller that needs it.

            builder.Services.TryAddSingleton<SecretManagerConfigurationProvider>(sp =>
                new SecretManagerConfigurationProvider(
                    sp.GetService<ILogger<SecretManagerConfigurationProvider>>()!,
                    sp.GetRequiredService<Lazy<IConfigurationGateway>>(),
                    invalidator: new Lazy<ICacheInvalidator?>(() => sp.GetService<ICacheInvalidator>())));
            // Why: Consumers inject DefaultConfigurationProvider<TConfig, TCommand> (the new base) —
            // forward to the concrete subclass.
            builder.Services.TryAddSingleton<DefaultConfigurationProvider<SecretManagerConfiguration, SecretManagerConfigurationCommand>>(
                sp => sp.GetRequiredService<SecretManagerConfigurationProvider>());
            // Why: Generated Initialize() links IServiceConfigurationProvider<T> as the parent on the
            // domain provider (SecretManagerProvider); this forward lets that lookup succeed.
            builder.Services.TryAddSingleton<IServiceConfigurationProvider<SecretManagerConfiguration>>(
                sp => sp.GetRequiredService<SecretManagerConfigurationProvider>());
            // Why: publishes the domain's own provider interface. The generated Register only registers the
            // provider under IPlatformServiceProvider<,>, which no factory may take by constructor (FDW045).
            // Consumers — the connection factories above all — depend on ISecretManagerProvider instead, and
            // this forward hands them the SAME instance, so its factory registrations and cache are shared.
            // The cast is deliberate and fail-loud: the generator constructs DefaultSecretManagerProvider,
            // and if anything ever replaces that registration with a type that is not the domain provider,
            // the composition root must break loudly rather than resolve a second, empty provider.
            builder.Services.TryAddSingleton<ISecretManagerProvider>(
                sp => (ISecretManagerProvider)sp.GetRequiredService<IPlatformServiceProvider<ISecretManager, SecretManagerConfiguration>>());

            var declaredOptions = Options;
            var optionNames = string.Join(", ", declaredOptions.Select(option => option.Name));

            ServiceTypeLog.DomainOptionsCollected(log, nameof(SecretManagerTypes), declaredOptions.Length, optionNames);
            ServiceTypeLog.DomainProviderDeclared(log, nameof(SecretManagerTypes), providerService);

            builder.Services.AddScoped<IPlatformServiceProvider<ISecretManager, SecretManagerConfiguration>>(sp =>
            {
                var provider = new DefaultSecretManagerProvider(
                    sp,
                    sp.GetService<ILoggerFactory>()?.CreateLogger<DefaultSecretManagerProvider>()
                    ?? NullLogger<DefaultSecretManagerProvider>.Instance);

                // Why ILogger<SecretManagerTypes> and not CreateLogger("SecretManagerTypes"): SourceContext then
                // carries the namespace-qualified collection, and the category cannot drift from the
                // type it claims to name. The provider logs its own lines under its own type, so the
                // two layers read base-then-derived rather than collapsing onto one category.
                var stLogger = sp.GetService<ILoggerFactory>()?.CreateLogger<SecretManagerTypes>()
                    ?? NullLogger<SecretManagerTypes>.Instance;
                ServiceTypeLog.DomainProviderConstructing(stLogger, nameof(SecretManagerTypes), provider.GetType().Name);
                try
                {
                    if (sp.GetService<IServiceConfigurationProvider<SecretManagerConfiguration>>() is { } cfgProvider)
                    {
                        // Why the result is read: a provider that did not take its parent still constructs, and
                        // every later read silently misses. The failure has to be said out loud here or nowhere.
                        var parentResult = provider.Register(cfgProvider);
                        if (parentResult.IsSuccess)
                            ServiceTypeLog.DomainConfigurationSourceAttached(stLogger, nameof(SecretManagerTypes), provider.GetType().Name, cfgProvider.GetType().Name);
                        else
                            ServiceTypeLog.DomainConfigurationSourceRejected(stLogger, nameof(SecretManagerTypes), provider.GetType().Name, cfgProvider.GetType().Name, parentResult.CurrentMessage);
                    }
                    else
                    {
                        // Why Critical, and why the collection says it rather than the provider: from
                        // inside the provider a null parent is indistinguishable from a domain that needs
                        // none. This is the one place that knows one was meant to arrive, and without it
                        // the domain fails every lookup by name for the life of the scope with nothing
                        // pointing back here.
                        ServiceTypeLog.DomainHasNoConfigurationSource(
                            stLogger,
                            nameof(SecretManagerTypes),
                            provider.GetType().Name,
                            typeof(IServiceConfigurationProvider<SecretManagerConfiguration>).ToString());
                    }
                }
                catch (Exception ex)
                {
                    // Why rethrow: a throw here was previously silent, and a provider that failed to take
                    // its parent is unusable in a way that only surfaces much later.
                    ServiceTypeLog.FactoryRegistrationException(stLogger, ex, nameof(SecretManagerTypes));
                    throw;
                }
                return provider;
            });

            // Why the milestone comes after the registration and not before: it states that the domain
            // finished phase 2, which is only true once the provider is actually in the container.
            if (declaredOptions.Length == 0)
                ServiceTypeLog.DomainRegisteredWithNoOptions(log, nameof(SecretManagerTypes), providerService);
            else
                ServiceTypeLog.DomainRegistered(log, nameof(SecretManagerTypes), declaredOptions.Length, optionNames, providerService);

            return GenericResult<IHostApplicationBuilder>.Success(builder);
        });
    }
}
