using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Fdw.SourceGenerators.Helpers;

namespace __RootNamespace__.__Name__.SourceGenerators;

/// <summary>
/// Generates a provider that discovers all __Name__ types decorated with [__Name__Option].
/// </summary>
[Generator]
public sealed class __Name__ProviderGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
#if DEBUG
        // Debug output to confirm generator is loaded
        context.RegisterPostInitializationOutput(static context =>
        {
            context.AddSource("__Name__ProviderGenerator.Init.g.cs",
                @"// <auto-generated/>
// __Name__ProviderGenerator is loaded and running
");
        });
#endif

        // Use CompilationProvider to scan for decorated types
        context.RegisterSourceOutput(context.CompilationProvider, static (context, compilation) =>
        {
            var debugInfo = new StringBuilder();
            debugInfo.AppendLine($"// DEBUG: Compilation assembly: {compilation.AssemblyName}");

            // Find the [__Name__Option] attribute type
            var attributeType = compilation.GetTypeByMetadataName("__RootNamespace__.__Name__.Attributes.__Name__OptionAttribute");
            if (attributeType == null)
            {
                debugInfo.AppendLine("// DEBUG: __Name__OptionAttribute not found");
                context.AddSource("__Name__ProviderGenerator.Debug.g.cs", debugInfo.ToString());
                return;
            }

            // Scan all types for the attribute
            var decoratedTypes = new Dictionary<string, INamedTypeSymbol>(StringComparer.Ordinal);
            ScanAssembly(compilation.Assembly, attributeType, decoratedTypes, debugInfo);

            debugInfo.Insert(0, $"// DEBUG: Found {decoratedTypes.Count} unique __Name__Options via manual scan\n");

            // Always output debug info
            context.AddSource("__Name__ProviderGenerator.Debug.g.cs", debugInfo.ToString());

            if (decoratedTypes.Count == 0)
            {
                return;
            }

            // TODO: Generate your provider class here
            // var code = Generate__Name__Provider(decoratedTypes.Values.ToList());
            // context.AddSource("__Name__Provider.g.cs", code);
        });
    }

    private static void ScanAssembly(
        IAssemblySymbol assembly,
        INamedTypeSymbol attributeType,
        Dictionary<string, INamedTypeSymbol> results,
        StringBuilder debugInfo)
    {
        ScanNamespace(assembly.GlobalNamespace, attributeType, results, debugInfo);

        foreach (var referencedAssembly in assembly.Modules.SelectMany(m => m.ReferencedAssemblySymbols))
        {
            ScanNamespace(referencedAssembly.GlobalNamespace, attributeType, results, debugInfo);
        }
    }

    private static void ScanNamespace(
        INamespaceSymbol ns,
        INamedTypeSymbol attributeType,
        Dictionary<string, INamedTypeSymbol> results,
        StringBuilder debugInfo)
    {
        foreach (var type in ns.GetTypeMembers())
        {
            if (HasAttribute(type, attributeType))
            {
                var fullName = type.ToDisplayString();
                if (!results.ContainsKey(fullName))
                {
                    debugInfo.AppendLine($"// DEBUG: Found {type.Name}");
                    results[fullName] = type;
                }
            }

            foreach (var nestedType in type.GetTypeMembers())
            {
                if (HasAttribute(nestedType, attributeType))
                {
                    var fullName = nestedType.ToDisplayString();
                    if (!results.ContainsKey(fullName))
                    {
                        debugInfo.AppendLine($"// DEBUG: Found {nestedType.Name}");
                        results[fullName] = nestedType;
                    }
                }
            }
        }

        foreach (var childNamespace in ns.GetNamespaceMembers())
        {
            ScanNamespace(childNamespace, attributeType, results, debugInfo);
        }
    }

    private static bool HasAttribute(INamedTypeSymbol type, INamedTypeSymbol attributeType)
    {
        return type.GetAttributes().Any(a =>
            SymbolEqualityComparer.Default.Equals(a.AttributeClass, attributeType));
    }
}
