using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Reflection;
using System.Text;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Logging.Abstractions;

namespace Fdw.WebMcp.Hosting;

/// <summary>
/// Generates the <c>webmcp.js</c> IIFE that registers AI-agent tools via
/// <c>document.modelContext.registerTool()</c> (WebMCP W3C standard).
/// </summary>
public sealed class WebMcpJsGenerator
{
    private readonly IWebMcpToolRegistry _registry;
    private readonly ILogger<WebMcpJsGenerator> _logger;
    private readonly WebMcpOptions? _options;

    /// <summary>
    /// Initializes a new instance of <see cref="WebMcpJsGenerator"/>.
    /// </summary>
    public WebMcpJsGenerator(
        IWebMcpToolRegistry registry,
        ILogger<WebMcpJsGenerator>? logger = null,
        WebMcpOptions? options = null)
    {
        _registry = registry;
        _logger = logger ?? NullLogger<WebMcpJsGenerator>.Instance;
        _options = options;
    }

    /// <summary>
    /// Builds and returns the full JavaScript source string.
    /// Returns a no-op script if no tools have been registered.
    /// </summary>
    public string Generate()
    {
        WebMcpLog.ServingWebMcpJs(_logger, _registry.Tools.Count);
        WebMcpLog.GeneratingScript(_logger, _registry.Tools.Count);

        WebMcpLog.ClientKeyInjection(
            _logger,
            _options?.ApiKeyHeader ?? "X-Webmcp-Key",
            !string.IsNullOrEmpty(_options?.ClientApiKey));

        var sb = new StringBuilder();
        sb.AppendLine("// Generated by Fdw WebMCP");
        sb.AppendLine("// Registers AI agent tools via document.modelContext (WebMCP W3C standard).");
        sb.AppendLine("// The spec moved the API from navigator to document because tools belong to a");
        sb.AppendLine("// page, and Chrome 150 deprecated the navigator form while the Chrome 149");
        sb.AppendLine("// origin trial still serves it. Prefer document, accept navigator, so one");
        sb.AppendLine("// generated script works across the Chrome 149-156 trial window.");
        sb.AppendLine("(function() {");
        sb.AppendLine("  var modelContext =");
        sb.AppendLine("    (typeof document !== 'undefined' && document.modelContext) ||");
        sb.AppendLine("    (typeof navigator !== 'undefined' && navigator.modelContext) ||");
        sb.AppendLine("    null;");
        sb.AppendLine("  if (!modelContext) return;");
        sb.AppendLine();
        sb.AppendLine("  // Path parameters travel in the URL, so they are removed from the body a tool sends.");
        sb.AppendLine("  function strip(input, names) {");
        sb.AppendLine("    const out = {};");
        sb.AppendLine("    for (const k of Object.keys(input || {})) if (!names.includes(k)) out[k] = input[k];");
        sb.AppendLine("    return out;");
        sb.AppendLine("  }");
        sb.AppendLine();
        sb.AppendLine("  // Only values the agent actually supplied are sent: an omitted filter must widen");
        sb.AppendLine("  // the result, not narrow it to the empty string.");
        sb.AppendLine("  function query(input, names) {");
        sb.AppendLine("    const parts = [];");
        sb.AppendLine("    for (const n of names) {");
        sb.AppendLine("      const v = (input || {})[n];");
        sb.AppendLine("      if (v === undefined || v === null || v === \"\") continue;");
        sb.AppendLine("      parts.push(encodeURIComponent(n) + \"=\" + encodeURIComponent(v));");
        sb.AppendLine("    }");
        sb.AppendLine("    return parts.join(\"&\");");
        sb.AppendLine("  }");
        sb.AppendLine();

        foreach (var tool in _registry.Tools)
        {
            AppendTool(sb, tool);
        }

        sb.AppendLine("})();");

        return sb.ToString();
    }

    // ── Per-tool JavaScript block ────────────────────────────────────────────

    private void AppendTool(StringBuilder sb, WebMcpToolDescriptor tool)
    {
        sb.AppendLine("  modelContext.registerTool({");
        sb.AppendLine(CultureInfo.InvariantCulture, $"    name: {JsonString(tool.Name)},");
        sb.AppendLine(CultureInfo.InvariantCulture, $"    description: {JsonString(tool.Description)},");

        if (tool.ReadOnly)
        {
            sb.AppendLine("    annotations: { readOnlyHint: true },");
        }

        var propertyCount = AppendInputSchema(sb, tool);
        AppendExecute(sb, tool);

        sb.AppendLine("  });");
        sb.AppendLine();

        WebMcpLog.ToolScriptEmitted(_logger, tool.Name, tool.HttpMethod, tool.Route, propertyCount);
    }

    private int AppendInputSchema(StringBuilder sb, WebMcpToolDescriptor tool)
    {
        // Gated on the request type alone. Gating on the verb, as this did, gave every GET and DELETE
        // an empty schema even when the endpoint declared a request DTO — so a path parameter had no
        // field to arrive through and a list tool could not be filtered. "Has a body" and "has inputs"
        // are different questions.
        if (tool.RequestType is null)
        {
            sb.AppendLine("    inputSchema: {");
            sb.AppendLine("      type: \"object\",");
            sb.AppendLine("      properties: {},");
            sb.AppendLine("      required: []");
            sb.AppendLine("    },");
            return 0;
        }

        var properties = GetSchemaProperties(tool.RequestType, tool.Name, _logger);

        sb.AppendLine("    inputSchema: {");
        sb.AppendLine("      type: \"object\",");
        sb.AppendLine("      properties: {");

        for (var i = 0; i < properties.Count; i++)
        {
            var (propName, jsonType, format) = properties[i];
            var comma = i < properties.Count - 1 ? "," : string.Empty;

            if (string.IsNullOrEmpty(format))
            {
                sb.AppendLine(CultureInfo.InvariantCulture, $"        {JsonKey(propName)}: {{ \"type\": {JsonString(jsonType)} }}{comma}");
            }
            else
            {
                sb.AppendLine(CultureInfo.InvariantCulture, $"        {JsonKey(propName)}: {{ \"type\": {JsonString(jsonType)}, \"format\": {JsonString(format)} }}{comma}");
            }
        }

        sb.AppendLine("      },");

        // Path parameters are the one set whose requiredness is structural rather than a matter of
        // validation policy: the URL cannot be built without them. Everything else stays optional and
        // is the endpoint's own validation to enforce.
        var pathParameters = WebMcpRouteTemplate.ParameterNames(tool.Route);
        if (pathParameters.Count == 0)
        {
            sb.AppendLine("      required: []");
        }
        else
        {
            sb.AppendLine(
                CultureInfo.InvariantCulture,
                $"      required: [{string.Join(", ", pathParameters.Select(p => JsonString(MatchProperty(tool.RequestType, p))))}]");
        }

        sb.AppendLine("    },");

        return properties.Count;
    }

    private void AppendExecute(StringBuilder sb, WebMcpToolDescriptor tool)
    {
        var pathParameters = WebMcpRouteTemplate.ParameterNames(tool.Route);
        var headers = HeaderLiteral(NeedsRequestBody(tool.HttpMethod));
        var recoveryHeaders = HeaderLiteral(withBody: false);

        sb.AppendLine("    execute: async function(input) {");
        sb.AppendLine(CultureInfo.InvariantCulture, $"      let url = {UrlExpression(tool, pathParameters)};");

        if (!NeedsRequestBody(tool.HttpMethod) && tool.RequestType is not null)
        {
            AppendQueryString(sb, tool, pathParameters);
        }

        sb.AppendLine("      const init = {");
        sb.AppendLine(CultureInfo.InvariantCulture, $"        method: {JsonString(tool.HttpMethod)},");
        if (NeedsRequestBody(tool.HttpMethod))
        {
            sb.AppendLine(CultureInfo.InvariantCulture, $"        headers: {headers},");

            // Path parameters are stripped from the body: they are already in the URL, and an endpoint
            // that receives the same value twice can disagree with itself about which one binds.
            sb.AppendLine(CultureInfo.InvariantCulture,
                $"        body: JSON.stringify(strip(input, {PathParameterArray(tool, pathParameters)}))");
        }
        else
        {
            sb.AppendLine(CultureInfo.InvariantCulture, $"        headers: {headers}");
        }

        sb.AppendLine("      };");
        sb.AppendLine("      const r = await fetch(url, init);");
        AppendFailureHandling(sb, tool, pathParameters, recoveryHeaders);
        sb.AppendLine("      return await r.json();");
        sb.AppendLine("    }");
    }

    /// <summary>Emits the JS expression that builds the request URL.</summary>
    private static string UrlExpression(WebMcpToolDescriptor tool, IReadOnlyList<string> pathParameters)
    {
        if (pathParameters.Count == 0)
        {
            return JsonString(tool.Route);
        }

        // Concatenated rather than string-replaced so each value is encoded on the way in. A value
        // carrying '/' or '?' would otherwise reshape the path it was substituted into.
        var parts = new List<string>();
        var remaining = tool.Route;

        foreach (var parameter in pathParameters)
        {
            var open = remaining.IndexOf('{', StringComparison.Ordinal);
            var close = remaining.IndexOf('}', StringComparison.Ordinal);
            if (open < 0 || close < open)
            {
                break;
            }

            parts.Add(JsonString(remaining[..open]));
            parts.Add($"encodeURIComponent(input[{JsonString(MatchProperty(tool.RequestType, parameter))}])");
            remaining = remaining[(close + 1)..];
        }

        if (remaining.Length > 0)
        {
            parts.Add(JsonString(remaining));
        }

        return string.Join(" + ", parts);
    }

    /// <summary>Emits the query-string assembly for a verb that carries no body.</summary>
    private void AppendQueryString(
        StringBuilder sb,
        WebMcpToolDescriptor tool,
        IReadOnlyList<string> pathParameters)
    {
        var queryProperties = GetSchemaProperties(tool.RequestType!, tool.Name, _logger)
            .Select(p => p.Name)
            .Where(name => !pathParameters.Any(
                p => string.Equals(MatchProperty(tool.RequestType, p), name, StringComparison.OrdinalIgnoreCase)))
            .ToList();

        if (queryProperties.Count == 0)
        {
            return;
        }

        // Without this a GET tool could be called but never narrowed — every list tool would return
        // the unfiltered collection whatever the agent asked for.
        sb.AppendLine(CultureInfo.InvariantCulture,
            $"      const q = query(input, [{string.Join(", ", queryProperties.Select(JsonString))}]);");
        sb.AppendLine("      if (q) url += \"?\" + q;");
    }

    /// <summary>Emits the non-OK branch, including the valid-values recovery when one is available.</summary>
    private static void AppendFailureHandling(
        StringBuilder sb,
        WebMcpToolDescriptor tool,
        IReadOnlyList<string> pathParameters,
        string recoveryHeaders)
    {
        if (tool.ParentListRoute is null || pathParameters.Count != 1)
        {
            sb.AppendLine("      if (!r.ok) return { error: r.status + \" \" + r.statusText };");
            return;
        }

        // A bare 404 is a dead end for an agent: it cannot tell a wrong identifier from an empty
        // result, and nothing in the response says what a right one would look like. Answering with
        // the collection the parameter selects from turns that into one more round trip.
        //
        // The recovery call reuses these headers, so it runs as the same principal — an agent can
        // never be handed values it could not have listed itself.
        var parameterName = MatchProperty(tool.RequestType, pathParameters[0]);

        sb.AppendLine("      if (!r.ok) {");
        sb.AppendLine("        const failure = { error: r.status + \" \" + r.statusText };");
        sb.AppendLine("        try {");
        sb.AppendLine(CultureInfo.InvariantCulture,
            $"          const alt = await fetch({JsonString(tool.ParentListRoute)}, {{ method: \"GET\", headers: {recoveryHeaders} }});");
        sb.AppendLine("          if (alt.ok) {");
        sb.AppendLine("            failure.validValues = await alt.json();");
        sb.AppendLine(CultureInfo.InvariantCulture,
            $"            failure.hint = {JsonString($"'{parameterName}' did not match. failure.validValues lists what is available; '{tool.ParentListToolName}' returns the same set.")};");
        sb.AppendLine("          }");
        sb.AppendLine("        } catch (e) { /* recovery is best-effort; the original failure still returns */ }");
        sb.AppendLine("        return failure;");
        sb.AppendLine("      }");
    }

    /// <summary>Returns the request property a route parameter binds to, or the parameter name itself.</summary>
    /// <remarks>
    /// Route parameters bind case-insensitively but the generated JS reads <c>input</c> by exact key,
    /// so the schema and the URL must both use the property's own casing or the value silently
    /// arrives undefined. The registry has already refused any tool where no property matches.
    /// </remarks>
    private static string MatchProperty(Type? requestType, string parameter)
        => requestType?.GetProperty(
               parameter,
               BindingFlags.Public | BindingFlags.Instance | BindingFlags.IgnoreCase)?.Name
           ?? parameter;

    private static string PathParameterArray(WebMcpToolDescriptor tool, IReadOnlyList<string> pathParameters)
        => "[" + string.Join(", ", pathParameters.Select(p => JsonString(MatchProperty(tool.RequestType, p)))) + "]";

    /// <summary>Builds the header literal for a request.</summary>
    /// <param name="withBody">Whether the request carries a JSON body.</param>
    /// <remarks>
    /// Takes the shape it needs rather than reading the tool's verb, because the recovery call is
    /// always a GET even on a tool that writes. Reusing a writing tool's headers put
    /// Content-Type on a bodyless GET.
    /// </remarks>
    private string HeaderLiteral(bool withBody)
    {
        var apiKeyHeader = _options?.ApiKeyHeader ?? "X-Webmcp-Key";
        var clientApiKey = _options?.ClientApiKey;
        var parts = new List<string> { "\"Accept\": \"application/json\"" };

        if (withBody)
        {
            parts.Add("\"Content-Type\": \"application/json\"");
        }

        if (!string.IsNullOrEmpty(clientApiKey))
        {
            parts.Add($"{JsonString(apiKeyHeader)}: {JsonString(clientApiKey)}");
        }

        return "{ " + string.Join(", ", parts) + " }";
    }

    // ── Schema derivation ────────────────────────────────────────────────────

    private static List<(string Name, string JsonType, string Format)> GetSchemaProperties(
        Type requestType,
        string toolName,
        ILogger logger)
    {
        var result = new List<(string, string, string)>();

        foreach (var prop in requestType.GetProperties(BindingFlags.Public | BindingFlags.Instance))
        {
            if (!prop.CanWrite)
            {
                continue;
            }

            var (jsonType, format) = MapClrTypeToJsonSchema(prop.PropertyType);
            if (string.IsNullOrEmpty(jsonType))
            {
                WebMcpLog.SchemaPropertySkipped(
                    logger,
                    toolName,
                    prop.Name,
                    prop.PropertyType.FullName ?? prop.PropertyType.Name);
                continue;
            }

            WebMcpLog.SchemaPropertyMapped(logger, toolName, prop.Name, jsonType, format);
            result.Add((prop.Name, jsonType, format));
        }

        return result;
    }

    private static (string JsonType, string Format) MapClrTypeToJsonSchema(Type clrType)
    {
        // Unwrap Nullable<T>
        var underlying = Nullable.GetUnderlyingType(clrType);
        if (underlying is not null)
        {
            return MapClrTypeToJsonSchema(underlying);
        }

        if (clrType == typeof(string)) return ("string", string.Empty);
        if (clrType == typeof(bool)) return ("boolean", string.Empty);
        if (clrType == typeof(int)) return ("integer", string.Empty);
        if (clrType == typeof(long)) return ("integer", string.Empty);
        if (clrType == typeof(short)) return ("integer", string.Empty);
        if (clrType == typeof(double)) return ("number", string.Empty);
        if (clrType == typeof(float)) return ("number", string.Empty);
        if (clrType == typeof(decimal)) return ("number", string.Empty);
        if (clrType == typeof(Guid)) return ("string", "uuid");
        if (clrType == typeof(DateTime)) return ("string", "date-time");
        if (clrType == typeof(DateTimeOffset)) return ("string", "date-time");
        if (clrType == typeof(DateOnly)) return ("string", "date");
        if (clrType == typeof(TimeOnly)) return ("string", "time");

        // Skip arrays, collections, nested objects
        return (string.Empty, string.Empty);
    }

    // ── Helpers ──────────────────────────────────────────────────────────────

    private static bool NeedsRequestBody(string httpMethod)
        => string.Equals(httpMethod, "POST", StringComparison.OrdinalIgnoreCase)
            || string.Equals(httpMethod, "PUT", StringComparison.OrdinalIgnoreCase)
            || string.Equals(httpMethod, "PATCH", StringComparison.OrdinalIgnoreCase);

    private static string JsonString(string value)
    {
        // Minimal JSON string escaping for JS output
        return "\"" + value
            .Replace("\\", "\\\\", StringComparison.Ordinal)
            .Replace("\"", "\\\"", StringComparison.Ordinal)
            .Replace("\n", "\\n", StringComparison.Ordinal)
            .Replace("\r", "\\r", StringComparison.Ordinal)
            + "\"";
    }

    private static string JsonKey(string name)
        => JsonString(name);
}
