using System.Diagnostics.CodeAnalysis;
using Fdw.Abstractions;
using Fdw.Collections;

namespace Fdw.Services.Agents;

/// <summary>
/// ServiceTypeCollection for agent action service types.
/// Generated by ServiceTypeCollectionGenerator with high-performance lookups.
/// </summary>
[ExcludeFromCodeCoverage]
[ServiceTypeCollection(
    typeof(AgentActionTypeBase<IGenericService, IAgentActionFactory>),
    typeof(IAgentActionType),
    typeof(AgentActionTypes),
    ServiceCategory = "AgentAction")]
public partial class AgentActionTypes : ServiceTypeCollectionBase<
    AgentActionTypeBase<IGenericService, IAgentActionFactory>,
    IAgentActionType>
{
}
