using System.Collections.Generic;
using System.IO;
using System.Text;
using Fdw.UI.Components.RazorConsole.SourceGenerators.CodeGenerators;
using Microsoft.AspNetCore.Razor.Language;

namespace Fdw.UI.Components.RazorConsole.SourceGenerators;

/// <summary>
/// Generates C# code from parsed Razor document.
/// </summary>
internal sealed class CodeGenerator
{
    public static string Generate(RazorCodeDocument document)
    {
        var builder = new StringBuilder();

        builder.AppendLine("// <auto-generated/>");
        builder.AppendLine("#nullable enable");
        builder.AppendLine();

        // Extract directives
        var inheritsDirective = CodeGenerator.ExtractInherits(document);
        var usings = CodeGenerator.ExtractUsings(document);

        // Add usings
        builder.AppendLine("using System;");
        builder.AppendLine("using System.Threading.Tasks;");
        builder.AppendLine("using Spectre.Console;");
        builder.AppendLine("using Fdw.UI.Components.RazorConsole;");
        foreach (var usingDirective in usings)
        {
            builder.AppendLine($"using {usingDirective};");
        }
        builder.AppendLine();

        // Extract class name from file
        var className = Path.GetFileNameWithoutExtension(document.Source.FilePath);

        // Generate class
        builder.AppendLine($"public partial class {className} : {inheritsDirective}");
        builder.AppendLine("{");

        // Generate Prompt method
        builder.AppendLine(PromptMethodGenerator.Generate(document));

        builder.AppendLine();

        // Generate Render method
        builder.AppendLine(RenderMethodGenerator.Generate(document));

        // Generate parameters
        var paramCode = ParameterGenerator.Generate(document);
        if (!string.IsNullOrEmpty(paramCode))
        {
            builder.AppendLine();
            builder.AppendLine(paramCode);
        }

        builder.AppendLine("}");

        return builder.ToString();
    }

    private static string ExtractInherits(RazorCodeDocument document)
    {
        // Default to RazorConsoleComponent<object>
        return "RazorConsoleComponent<object>";
    }

    private static List<string> ExtractUsings(RazorCodeDocument document)
    {
        return new List<string>();
    }
}