using System;
using System.Diagnostics.CodeAnalysis;
using System.Linq;
using Fdw.Collections;
using Fdw.Services;
using Fdw.Services.Abstractions;
using Fdw.ServiceTypes;
using Fdw.Services.Etl.Abstractions;
using Fdw.Services.Pipelines.Abstractions;
using Fdw.Services.Etl.Abstractions.Execution;
using Fdw.Services.Etl.Execution;
using Fdw.Services.Pipelines;
using Fdw.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.DependencyInjection.Extensions;
using Fdw.ServiceTypes.Logging;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Logging.Abstractions;
using Fdw.Results;
using Microsoft.Extensions.Hosting;
using Fdw.Services.Configuration;
using Fdw.Services.Data.Abstractions;
using Fdw.Services.Etl.Commands;
using Microsoft.Extensions.Options;
using System.Collections.Generic;

namespace Fdw.Services.Etl;

/// <summary>
/// Collection of ETL pipeline service types.
/// Generated by ServiceTypeCollectionGenerator with high-performance lookups.
/// </summary>
/// <remarks>
/// This ServiceTypeCollection manages ETL pipeline ENGINE types (BatchCopy, Streaming).
/// Engine types are services with behavior - they register factories and the two-level configuration
/// typed-body chain (Pipeline → Etl → engine). Each engine type registers its own engine configuration
/// body (e.g., BatchCopyPipelineConfiguration : IEtlPipelineTypedConfiguration) plus the ETL-kind header
/// provider (EtlPipelineConfiguration, the "Etl" kind of PipelineConfiguration).
/// </remarks>
[ExcludeFromCodeCoverage]
[ServiceTypeCollection(
    typeof(EtlPipelineTypeBase<IEtlPipeline, IEtlPipelineFactory<IEtlPipeline, EtlPipelineConfiguration>, EtlPipelineConfiguration>),
    typeof(IEtlPipelineType),
    typeof(EtlPipelineTypes),
    ServiceInterface = typeof(IEtlPipeline),
    ProviderType = typeof(EtlPipelineProvider),
    ProviderInterface = typeof(IEtlPipelineProvider),
    ServiceCategory = "Pipeline")]
public partial class EtlPipelineTypes : ServiceTypeCollectionBase<
    EtlPipelineTypeBase<IEtlPipeline, IEtlPipelineFactory<IEtlPipeline, EtlPipelineConfiguration>, EtlPipelineConfiguration>,
    IEtlPipelineType<IEtlPipeline, EtlPipelineConfiguration, IEtlPipelineFactory<IEtlPipeline, EtlPipelineConfiguration>>>
{
    /// <summary>
    /// The connection this domain's configuration rows are read from and written to.
    /// </summary>
    public static string ConfigurationConnection { get; set; } = "PlatformConfiguration";

    // Configure(), Register() and Initialize() are source-generated.
    // Each pipeline type (BatchCopy, Streaming) registers its own configuration via its ServiceTypeOption.

    /// <summary>
    /// Registers execution-inspection singletons consumed by test-mode endpoints.
    /// Call this BEFORE any endpoint-activation path that injects these interfaces.
    /// </summary>
    /// <remarks>
    /// Why: IPipelineExecutionInspector / IPipelineTestController are consumed by
    /// InspectEdgeEndpoint, StepExecutionEndpoint, and ResumeTestExecutionEndpoint at
    /// FastEndpoints activation time. They have no ServiceTypeOption of their own — they
    /// are cross-cutting singletons that belong to the ETL execution subsystem, not to a
    /// pipeline type variant. RegisterAdditionalServices is the canonical home for
    /// non-variant singletons inside a ServiceTypeCollection.
    /// </remarks>
    public static void RegisterAdditionalServices(IServiceCollection services)
    {
        services.TryAddSingleton<IPipelineExecutionInspector, PipelineExecutionInspector>();
        services.TryAddSingleton<IPipelineTestController, PipelineTestController>();
    }

    /// <summary>
    /// Registers the pipeline execution queue (<see cref="IPipelineExecutionQueue"/>) and its
    /// background consumer (<see cref="PipelineExecutionBackgroundService"/>).
    /// </summary>
    /// <remarks>
    /// Why a shared helper: OrchestrationNodeOrchestrator (Fdw.Services.Etl.Projects) takes
    /// IPipelineExecutionQueue as a hard (non-nullable) constructor dependency to dispatch
    /// leaf-node pipeline runs. Every host that registers OrchestrationTypes must get a working
    /// queue, not just hosts that separately opt into the background executor — this is the
    /// canonical, option-owned home for that registration (same domain as PipelineExecutionQueue
    /// itself), mirroring RegisterAdditionalServices above.
    /// <para>
    /// Idempotent by design: safe to call from multiple registration paths (both
    /// the pipeline options and OrchestrationTypes.Register call this) regardless
    /// of call order — the first caller's queueCapacity wins.
    /// </para>
    /// </remarks>
    /// <param name="services">The service collection.</param>
    /// <param name="queueCapacity">Maximum pending execution requests (default: 100).</param>
    public static void RegisterPipelineExecutionQueue(IServiceCollection services, int queueCapacity = 100)
    {
        if (services.Any(d => d.ServiceType == typeof(IPipelineExecutionQueue)))
            return;

        var queue = new PipelineExecutionQueue(queueCapacity);
        services.AddSingleton(queue);
        services.AddSingleton<IPipelineExecutionQueue>(queue);
        services.AddHostedService<PipelineExecutionBackgroundService>();
    }

    /// <summary>
    /// Sets this collection's Register body: the option collect, then this domain's provider.
    /// </summary>
    /// <remarks>
    /// The provider is one registration for the whole collection and this declaration already names it,
    /// so the body that registers it is written here beside the declaration. Setting it as the phase's
    /// body is what makes it replaceable: an application calling <c>Registration(...)</c> replaces the
    /// collect and this registration together, which is the correct semantic for a host taking over phase 2.
    /// </remarks>
    static EtlPipelineTypes()
    {
        var collectOptions = RegisterFunc;

        var providerService = typeof(IEtlPipelineProvider).ToString();

        Registration((builder, loggerFactory) =>
        {
            var log = loggerFactory?.CreateLogger<EtlPipelineTypes>() ?? NullLogger<EtlPipelineTypes>.Instance;

            var registered = collectOptions(builder, loggerFactory);
            if (registered.IsFailure)
                return registered;
            // EtlPipeline configuration, registered once for the domain here rather
            // than by every caller that needs it.

            builder.Services.TryAddSingleton<EtlPipelineConfigurationProvider>(sp =>
                new EtlPipelineConfigurationProvider(
                    sp.GetService<ILogger<EtlPipelineConfigurationProvider>>()!,
                    sp.GetRequiredService<IConfigurationGatewayProvider>(),
                        EtlPipelineTypes.ConfigurationConnection));
            builder.Services.TryAddSingleton<ImplementationConfigurationProviderBase<EtlPipelineConfiguration, EtlPipelineConfigurationCommand>>(
                sp => sp.GetRequiredService<EtlPipelineConfigurationProvider>());
            builder.Services.TryAddSingleton<IServiceConfigurationProvider<EtlPipelineConfiguration>>(
                sp => sp.GetRequiredService<EtlPipelineConfigurationProvider>());

            var declaredOptions = Options;
            var optionNames = string.Join(", ", declaredOptions.Select(option => option.Name));

            ServiceTypeLog.DomainOptionsCollected(log, nameof(EtlPipelineTypes), declaredOptions.Length, optionNames);
            ServiceTypeLog.DomainProviderDeclared(log, nameof(EtlPipelineTypes), providerService);

            builder.Services.AddScoped<IEtlPipelineProvider>(sp =>
            {
                var provider = new EtlPipelineProvider(
                    sp,
                    sp.GetService<ILoggerFactory>()?.CreateLogger<EtlPipelineProvider>()
                    ?? NullLogger<EtlPipelineProvider>.Instance);

                var stLogger = sp.GetService<ILoggerFactory>()?.CreateLogger<EtlPipelineTypes>()
                    ?? NullLogger<EtlPipelineTypes>.Instance;
                ServiceTypeLog.DomainProviderConstructing(stLogger, nameof(EtlPipelineTypes), provider.GetType().Name);
                try
                {
                    if (sp.GetService<IPipelineConfigurationProvider>() is { } cfgProvider)
                    {
                        var domainResult = provider.Register(cfgProvider);
                        if (domainResult.IsSuccess)
                            ServiceTypeLog.DomainConfigurationSourceAttached(stLogger, nameof(EtlPipelineTypes), provider.GetType().Name, cfgProvider.GetType().Name);
                        else
                            ServiceTypeLog.DomainConfigurationSourceRejected(stLogger, nameof(EtlPipelineTypes), provider.GetType().Name, cfgProvider.GetType().Name, domainResult.CurrentMessage);
                    }
                    else
                    {
                        ServiceTypeLog.DomainHasNoConfigurationSource(
                            stLogger,
                            nameof(EtlPipelineTypes),
                            provider.GetType().Name,
                            typeof(IServiceConfigurationProvider<PipelineConfiguration>).ToString());
                    }
                }
                catch (Exception ex)
                {
                    ServiceTypeLog.FactoryRegistrationException(stLogger, ex, nameof(EtlPipelineTypes));
                    throw;
                }
                return provider;
            });

            if (declaredOptions.Length == 0)
                ServiceTypeLog.DomainRegisteredWithNoOptions(log, nameof(EtlPipelineTypes), providerService);
            else
                ServiceTypeLog.DomainRegistered(log, nameof(EtlPipelineTypes), declaredOptions.Length, optionNames, providerService);

            return GenericResult<IHostApplicationBuilder>.Success(builder);
        });
    }
}
