using System;
using System.Diagnostics.CodeAnalysis;
using System.Linq;
using Fdw.Collections;
using Fdw.Services;
using Fdw.Services.Abstractions;
using Fdw.ServiceTypes;
using Fdw.Services.Etl.Abstractions;
using Fdw.Services.Etl.Abstractions.Execution;
using Fdw.Services.Etl.Execution;
using Fdw.Services.Pipelines;
using Fdw.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.DependencyInjection.Extensions;
using Fdw.ServiceTypes.Logging;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Logging.Abstractions;

namespace Fdw.Services.Etl;

/// <summary>
/// Collection of ETL pipeline service types.
/// Generated by ServiceTypeCollectionGenerator with high-performance lookups.
/// </summary>
/// <remarks>
/// This ServiceTypeCollection manages ETL pipeline ENGINE types (BatchCopy, Streaming).
/// Engine types are services with behavior - they register factories and the two-level configuration
/// typed-body chain (Pipeline → Etl → engine). Each engine type registers its own engine configuration
/// body (e.g., BatchCopyPipelineConfiguration : IEtlPipelineTypedConfiguration) plus the ETL-kind header
/// provider (EtlPipelineConfiguration, the "Etl" kind of PipelineConfiguration).
/// </remarks>
[ExcludeFromCodeCoverage]
[ServiceTypeCollection(
    typeof(EtlPipelineTypeBase<IEtlPipeline, IEtlPipelineFactory<IEtlPipeline, EtlPipelineConfiguration>, EtlPipelineConfiguration>),
    typeof(IEtlPipelineType),
    typeof(EtlPipelineTypes),
    GenerateProvider = true,
    ServiceInterface = typeof(IEtlPipeline),
    // Why: the runtime service provider name-resolves via the ROOT header (pipe.Pipeline /
    // PipelineConfiguration, which owns Name + ServiceOptionType), then composes the kind/engine
    // typed bodies and downcasts in the factory. ConfigurationType therefore is the header config —
    // it drives the generated parent-provider lookup + IOptions binding. The ENGINE type-options
    // (BatchCopy/Streaming) keep EtlPipelineConfiguration as their base config (positional arg above).
    ConfigurationType = typeof(PipelineConfiguration),
    ProviderType = typeof(DefaultServiceProvider<IEtlPipeline, PipelineConfiguration, IEtlPipelineFactory<IEtlPipeline, EtlPipelineConfiguration>, IServiceConfigurationProvider<PipelineConfiguration>>),
    ProviderInterface = typeof(IFdwServiceProvider<IEtlPipeline, PipelineConfiguration>),
    ServiceCategory = "Pipeline")]
public partial class EtlPipelineTypes : ServiceTypeCollectionBase<
    EtlPipelineTypeBase<IEtlPipeline, IEtlPipelineFactory<IEtlPipeline, EtlPipelineConfiguration>, EtlPipelineConfiguration>,
    IEtlPipelineType<IEtlPipeline, EtlPipelineConfiguration, IEtlPipelineFactory<IEtlPipeline, EtlPipelineConfiguration>>>
{
    // Configure(), Register() and Initialize() are source-generated.
    // Each pipeline type (BatchCopy, Streaming) registers its own configuration via its ServiceTypeOption.

    /// <summary>
    /// Registers execution-inspection singletons consumed by test-mode endpoints.
    /// Call this BEFORE any endpoint-activation path that injects these interfaces.
    /// </summary>
    /// <remarks>
    /// Why: IPipelineExecutionInspector / IPipelineTestController are consumed by
    /// InspectEdgeEndpoint, StepExecutionEndpoint, and ResumeTestExecutionEndpoint at
    /// FastEndpoints activation time. They have no ServiceTypeOption of their own — they
    /// are cross-cutting singletons that belong to the ETL execution subsystem, not to a
    /// pipeline type variant. RegisterAdditionalServices is the canonical home for
    /// non-variant singletons inside a ServiceTypeCollection.
    /// </remarks>
    public static void RegisterAdditionalServices(IServiceCollection services)
    {
        services.TryAddSingleton<IPipelineExecutionInspector, PipelineExecutionInspector>();
        services.TryAddSingleton<IPipelineTestController, PipelineTestController>();
    }

    /// <summary>
    /// Registers the pipeline execution queue (<see cref="IPipelineExecutionQueue"/>) and its
    /// background consumer (<see cref="PipelineExecutionBackgroundService"/>).
    /// </summary>
    /// <remarks>
    /// Why a shared helper: OrchestrationNodeOrchestrator (Fdw.Services.Etl.Projects) takes
    /// IPipelineExecutionQueue as a hard (non-nullable) constructor dependency to dispatch
    /// leaf-node pipeline runs. Every host that registers OrchestrationTypes must get a working
    /// queue, not just hosts that separately opt into the background executor — this is the
    /// canonical, option-owned home for that registration (same domain as PipelineExecutionQueue
    /// itself), mirroring RegisterAdditionalServices above.
    /// <para>
    /// Idempotent by design: safe to call from multiple registration paths (both
    /// the pipeline options and OrchestrationTypes.Register call this) regardless
    /// of call order — the first caller's queueCapacity wins.
    /// </para>
    /// </remarks>
    /// <param name="services">The service collection.</param>
    /// <param name="queueCapacity">Maximum pending execution requests (default: 100).</param>
    public static void RegisterPipelineExecutionQueue(IServiceCollection services, int queueCapacity = 100)
    {
        if (services.Any(d => d.ServiceType == typeof(IPipelineExecutionQueue)))
            return;

        var queue = new PipelineExecutionQueue(queueCapacity);
        services.AddSingleton(queue);
        services.AddSingleton<IPipelineExecutionQueue>(queue);
        services.AddHostedService<PipelineExecutionBackgroundService>();
    }

    /// <summary>
    /// Sets this collection's Register body: the option sweep, then this domain's provider.
    /// </summary>
    /// <remarks>
    /// The provider is one registration for the whole collection and this declaration already names it,
    /// so the body that registers it is written here beside the declaration. Setting it as the phase's
    /// body is what makes it replaceable: an application calling <c>Registration(...)</c> replaces the
    /// sweep and this registration together, which is the correct semantic for a host taking over phase 2.
    /// </remarks>
    static EtlPipelineTypes()
    {
        var sweepOptions = RegisterFunc;
        Registration((builder, loggerFactory) =>
        {
            sweepOptions(builder, loggerFactory);
            builder.Services.AddScoped<IFdwServiceProvider<IEtlPipeline, PipelineConfiguration>>(sp =>
            {
                var provider = new DefaultServiceProvider<IEtlPipeline, PipelineConfiguration, IEtlPipelineFactory<IEtlPipeline, EtlPipelineConfiguration>, IServiceConfigurationProvider<PipelineConfiguration>>(
                    sp,
                    sp.GetService<ILoggerFactory>()?.CreateLogger<DefaultServiceProvider<IEtlPipeline, PipelineConfiguration, IEtlPipelineFactory<IEtlPipeline, EtlPipelineConfiguration>, IServiceConfigurationProvider<PipelineConfiguration>>>()
                    ?? NullLogger<DefaultServiceProvider<IEtlPipeline, PipelineConfiguration, IEtlPipelineFactory<IEtlPipeline, EtlPipelineConfiguration>, IServiceConfigurationProvider<PipelineConfiguration>>>.Instance);
                var stLogger = sp.GetService<ILoggerFactory>()?.CreateLogger("EtlPipelineTypes");
                try
                {
                    if (sp.GetService<IServiceConfigurationProvider<PipelineConfiguration>>() is { } cfgProvider)
                    {
                        // Why the result is read: a provider that did not take its parent still constructs, and
                        // every later read silently misses. The failure has to be said out loud here or nowhere.
                        var parentResult = provider.Register(cfgProvider);
                        if (!parentResult.IsSuccess && stLogger != null)
                            ServiceTypeLog.FactoryRegistrationFailed(stLogger, "EtlPipelineTypes", parentResult.CurrentMessage ?? "EtlPipelineTypes");
                    }
                }
                catch (Exception ex)
                {
                    // Why rethrow: a throw here was previously silent, and a provider that failed to take
                    // its parent is unusable in a way that only surfaces much later.
                    if (stLogger != null) ServiceTypeLog.FactoryRegistrationException(stLogger, ex, "EtlPipelineTypes");
                    throw;
                }
                return provider;
            });
            return builder;
        });
    }
}
