using Fdw.Collections;
using Fdw.Collections.Attributes;
using System.Diagnostics.CodeAnalysis;

namespace Fdw.Services.Authentication.Abstractions.Methods;

/// <summary>
/// Collection of authentication protocol types.
/// Generated by TypeCollectionGenerator with high-performance lookups.
/// Provides unified access to all authentication protocols in the domain.
/// </summary>
[ExcludeFromCodeCoverage]
[TypeCollection(typeof(AuthenticationProtocolBase), typeof(IAuthenticationProtocol), typeof(AuthenticationProtocols))]
public abstract partial class AuthenticationProtocols : TypeCollectionBase<AuthenticationProtocolBase, IAuthenticationProtocol>
{
}
