using Fdw.Collections;
using Fdw.Collections.Attributes;
using System.Diagnostics.CodeAnalysis;

namespace Fdw.Services.Authentication.Abstractions.Methods;

/// <summary>
/// Collection of authentication flow types.
/// Generated by TypeCollectionGenerator with high-performance lookups.
/// Provides unified access to all authentication flows in the domain.
/// </summary>
[ExcludeFromCodeCoverage]
[TypeCollection(typeof(AuthenticationFlowBase), typeof(IAuthenticationFlow), typeof(AuthenticationFlows))]
public abstract partial class AuthenticationFlows : TypeCollectionBase<AuthenticationFlowBase, IAuthenticationFlow>
{
}
