using System.Diagnostics.CodeAnalysis;

namespace Fdw.Configuration.SourceGenerators.EmbeddedSources;

/// <summary>
/// Provides the embedded source for ConfigurationOptionAttribute.
/// </summary>
/// <remarks>Excluded from coverage: const string holder with no logic.</remarks>
[ExcludeFromCodeCoverage]
public static class ConfigurationOptionAttributeSource
{
    /// <summary>The generated file name.</summary>
    public const string FileName = "ConfigurationOptionAttribute.g.cs";

    /// <summary>The embedded source code.</summary>
    public const string Source = @"// <auto-generated/>
#nullable enable

namespace Fdw.Configuration
{
    /// <summary>
    /// Marks a property as referencing a TypeCollection.
    /// Generates validation that the value exists in the collection.
    /// </summary>
    [global::System.AttributeUsage(
        global::System.AttributeTargets.Property,
        AllowMultiple = false,
        Inherited = true)]
    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    internal sealed class ConfigurationOptionAttribute : global::System.Attribute
    {
        /// <summary>
        /// Gets the TypeCollection type this property references.
        /// </summary>
        public global::System.Type TypeCollection { get; }

        /// <summary>
        /// Gets or sets whether to validate against ById() instead of ByName().
        /// Default: false (validates against ByName)
        /// </summary>
        public bool ById { get; set; }

        /// <summary>
        /// Gets or sets the table name for the TypeCollection lookup table.
        /// Default: TypeCollection name (e.g., ""RetryPolicies"" for typeof(RetryPolicies))
        /// </summary>
        public string? TableName { get; set; }

        /// <summary>
        /// Gets or sets the database schema for the TypeCollection lookup table.
        /// Default: ""cfg""
        /// </summary>
        public string Schema { get; set; } = ""cfg"";

        /// <summary>
        /// Initializes a new instance of the ConfigurationOptionAttribute.
        /// </summary>
        /// <param name=""typeCollection"">The TypeCollection type this property references.</param>
        public ConfigurationOptionAttribute(global::System.Type typeCollection)
        {
            TypeCollection = typeCollection;
        }
    }
}
";
}
