using System.Diagnostics.CodeAnalysis;

namespace Fdw.Configuration.SourceGenerators.EmbeddedSources;

/// <summary>
/// Provides the embedded source for DbTypeAttribute.
/// </summary>
/// <remarks>Excluded from coverage: const string holder with no logic.</remarks>
[ExcludeFromCodeCoverage]
public static class DbTypeAttributeSource
{
    /// <summary>The generated file name.</summary>
    public const string FileName = "DbTypeAttribute.g.cs";

    /// <summary>The embedded source code.</summary>
    public const string Source = @"// <auto-generated/>
#nullable enable

namespace Fdw.Configuration
{
    /// <summary>
    /// Overrides the default SQL type mapping for a property.
    /// Default string type is varchar(500). Use this to specify nvarchar, different lengths, or decimal precision.
    /// </summary>
    [global::System.AttributeUsage(
        global::System.AttributeTargets.Property,
        AllowMultiple = false,
        Inherited = true)]
    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    internal sealed class DbTypeAttribute : global::System.Attribute
    {
        /// <summary>
        /// Gets the SQL data type (e.g., ""varchar"", ""nvarchar"", ""decimal"").
        /// </summary>
        public string SqlType { get; }

        /// <summary>
        /// Gets or sets the max length for string/binary types. Default: -1 (use type default)
        /// </summary>
        public int MaxLength { get; set; } = -1;

        /// <summary>
        /// Gets or sets the precision for decimal types. Default: -1 (use type default)
        /// </summary>
        public int Precision { get; set; } = -1;

        /// <summary>
        /// Gets or sets the scale for decimal types. Default: -1 (use type default)
        /// </summary>
        public int Scale { get; set; } = -1;

        /// <summary>
        /// Initializes a new instance of the DbTypeAttribute.
        /// </summary>
        /// <param name=""sqlType"">The SQL data type.</param>
        public DbTypeAttribute(string sqlType)
        {
            SqlType = sqlType;
        }
    }
}
";
}
