using System.Diagnostics.CodeAnalysis;

namespace Fdw.Configuration.SourceGenerators.EmbeddedSources;

/// <summary>
/// Provides the embedded source for ManagedConfigurationAttribute.
/// </summary>
/// <remarks>Excluded from coverage: const string holder with no logic.</remarks>
[ExcludeFromCodeCoverage]
public static class ManagedConfigurationAttributeSource
{
    /// <summary>The generated file name.</summary>
    public const string FileName = "ManagedConfigurationAttribute.g.cs";

    /// <summary>The embedded source code.</summary>
    public const string Source = @"// <auto-generated/>
#nullable enable

namespace Fdw.Configuration
{
    /// <summary>
    /// Marks a configuration class for management by the Fdw framework.
    /// Generates DDL definitions, ConfigurationTypes collection entry, and FluentValidation validator.
    /// Database-structural metadata (schema, table name, parent relationships) is now owned by
    /// the IDataNode object model and is no longer carried on this attribute.
    /// </summary>
    [global::System.AttributeUsage(global::System.AttributeTargets.Class,
        AllowMultiple = false,
        Inherited = false)]
    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    internal sealed class ManagedConfigurationAttribute : global::System.Attribute
    {
        /// <summary>
        /// Gets or sets the display name for UI.
        /// </summary>
        public string? DisplayName { get; set; }

        /// <summary>
        /// Gets or sets the description for UI help text.
        /// </summary>
        public string? Description { get; set; }

        /// <summary>
        /// Gets or sets the service category (e.g., ""Connection"", ""Workflow"").
        /// Inferred from class name suffix if not set.
        /// </summary>
        public string? ServiceCategory { get; set; }

        /// <summary>
        /// Gets or sets the service type (e.g., ""MsSql"", ""Customer"").
        /// Inferred from class name prefix if not set.
        /// </summary>
        public string? ServiceType { get; set; }

        /// <summary>
        /// Gets or sets whether to generate DDL definition. Default: true
        /// </summary>
        public bool GenerateDdl { get; set; } = true;

        /// <summary>
        /// Gets or sets whether to generate FluentValidation validator. Default: true
        /// </summary>
        public bool GenerateValidator { get; set; } = true;

        /// <summary>
        /// Gets or sets whether to generate UI form models. Default: true
        /// </summary>
        public bool GenerateUi { get; set; } = true;

        /// <summary>
        /// Gets or sets the foreign key delete behavior for child configurations.
        /// Valid values: ""Cascade"", ""SetNull"", ""NoAction"". Default: ""Cascade""
        /// </summary>
        public string OnDelete { get; set; } = ""Cascade"";

        /// <summary>
        /// Gets or sets the database provider for DDL generation.
        /// Valid values: ""MsSql"", ""PostgreSql"". Default: ""MsSql""
        /// </summary>
        public string DatabaseProvider { get; set; } = ""MsSql"";

        /// <summary>
        /// Gets or sets whether this configuration is effective-dated (valid-time versioned),
        /// adding EffectiveStart/EffectiveEnd columns and enabling as-of reads. Default: false
        /// </summary>
        /// <remarks>
        /// Opt in only where the BUSINESS period a record governs differs from when it was edited.
        /// Every configuration already carries transaction-time history — version-on-write retains
        /// superseded rows with CreateDate/ModifyDate, which answers ""what did we believe on
        /// date X"". Valid-time answers a different question: ""what was in force FOR period X"".
        /// Those diverge the moment someone edits on the 20th a rate that must apply from the 1st,
        /// which is exactly the case a settlement restatement hits — transaction-time would hand
        /// back the pre-edit version, which is the wrong answer.
        /// Rates, tariffs, and calculation definitions want this; connections and themes do not,
        /// and imposing it on them would add two columns and a whole temporal read path to records
        /// whose only meaningful version is the current one.
        /// </remarks>
        public bool Temporal { get; set; }

    }
}
";
}
