using System.Diagnostics.CodeAnalysis;
using Fdw.Abstractions;
using Fdw.Collections;
using Fdw.Configuration;
using Fdw.Services;
using Fdw.Services.Abstractions;
using Fdw.ServiceTypes;
using Fdw.Services.Scheduling.Abstractions;
using Fdw.ServiceTypes.Logging;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Logging.Abstractions;
using System;

namespace Fdw.Services.Scheduling;

/// <summary>
/// Collection of scheduler service types.
/// Generated by ServiceTypeCollectionGenerator with high-performance lookups.
/// </summary>
[ExcludeFromCodeCoverage]
[ServiceTypeCollection(
    typeof(SchedulerTypeBase<IFrameworkSchedulingService, SchedulerConfiguration, ISchedulingFactory<IFrameworkSchedulingService, SchedulerConfiguration>>),
    typeof(ISchedulerType),
    typeof(SchedulerTypes),
    GenerateProvider = true,
    ServiceInterface = typeof(IFrameworkSchedulingService),
    ConfigurationType = typeof(SchedulerConfiguration),
    ProviderType = typeof(DefaultServiceProvider<IFrameworkSchedulingService, SchedulerConfiguration, ISchedulingFactory<IFrameworkSchedulingService, SchedulerConfiguration>, IServiceConfigurationProvider<SchedulerConfiguration>>),
    ProviderInterface = typeof(IFdwServiceProvider<IFrameworkSchedulingService, SchedulerConfiguration>),
    ServiceCategory = "Scheduler")]
public partial class SchedulerTypes : ServiceTypeCollectionBase<
    SchedulerTypeBase<IFrameworkSchedulingService, SchedulerConfiguration, ISchedulingFactory<IFrameworkSchedulingService, SchedulerConfiguration>>,
    ISchedulerType>
{
    // Configure(), Register() and Initialize() are source-generated

    /// <summary>
    /// Sets this collection's Register body: the option sweep, then this domain's provider.
    /// </summary>
    /// <remarks>
    /// The provider is one registration for the whole collection and this declaration already names it,
    /// so the body that registers it is written here beside the declaration. Setting it as the phase's
    /// body is what makes it replaceable: an application calling <c>Registration(...)</c> replaces the
    /// sweep and this registration together, which is the correct semantic for a host taking over phase 2.
    /// </remarks>
    static SchedulerTypes()
    {
        var sweepOptions = RegisterFunc;
        Registration((builder, loggerFactory) =>
        {
            sweepOptions(builder, loggerFactory);
            builder.Services.AddScoped<IFdwServiceProvider<IFrameworkSchedulingService, SchedulerConfiguration>>(sp =>
            {
                var provider = new DefaultServiceProvider<IFrameworkSchedulingService, SchedulerConfiguration, ISchedulingFactory<IFrameworkSchedulingService, SchedulerConfiguration>, IServiceConfigurationProvider<SchedulerConfiguration>>(
                    sp,
                    sp.GetService<ILoggerFactory>()?.CreateLogger<DefaultServiceProvider<IFrameworkSchedulingService, SchedulerConfiguration, ISchedulingFactory<IFrameworkSchedulingService, SchedulerConfiguration>, IServiceConfigurationProvider<SchedulerConfiguration>>>()
                    ?? NullLogger<DefaultServiceProvider<IFrameworkSchedulingService, SchedulerConfiguration, ISchedulingFactory<IFrameworkSchedulingService, SchedulerConfiguration>, IServiceConfigurationProvider<SchedulerConfiguration>>>.Instance);
                var stLogger = sp.GetService<ILoggerFactory>()?.CreateLogger("SchedulerTypes");
                try
                {
                    if (sp.GetService<IServiceConfigurationProvider<SchedulerConfiguration>>() is { } cfgProvider)
                    {
                        // Why the result is read: a provider that did not take its parent still constructs, and
                        // every later read silently misses. The failure has to be said out loud here or nowhere.
                        var parentResult = provider.Register(cfgProvider);
                        if (!parentResult.IsSuccess && stLogger != null)
                            ServiceTypeLog.FactoryRegistrationFailed(stLogger, "SchedulerTypes", parentResult.CurrentMessage ?? "SchedulerTypes");
                    }
                }
                catch (Exception ex)
                {
                    // Why rethrow: a throw here was previously silent, and a provider that failed to take
                    // its parent is unusable in a way that only surfaces much later.
                    if (stLogger != null) ServiceTypeLog.FactoryRegistrationException(stLogger, ex, "SchedulerTypes");
                    throw;
                }
                return provider;
            });
            return builder;
        });
    }
}
