using System.Diagnostics.CodeAnalysis;
using Fdw.Abstractions;
using Fdw.Collections;
using Fdw.Configuration;
using Fdw.Services;
using Fdw.Services.Abstractions;
using Fdw.ServiceTypes;
using Fdw.Services.Configuration;
using Fdw.Services.Data.Abstractions;
using Fdw.Services.Scheduling.Abstractions;
using Fdw.Services.Scheduling.Abstractions.Configuration;
using Fdw.Services.Scheduling.Commands;
using Fdw.ServiceTypes.Logging;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.DependencyInjection.Extensions;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Logging.Abstractions;
using System;
using System.Linq;
using Fdw.Results;
using Microsoft.Extensions.Hosting;

namespace Fdw.Services.Scheduling;

/// <summary>
/// Collection of scheduler service types.
/// Generated by ServiceTypeCollectionGenerator with high-performance lookups.
/// </summary>
[ExcludeFromCodeCoverage]
[ServiceTypeCollection(
    typeof(SchedulerTypeBase<IFrameworkSchedulingService, ISchedulerImplementationConfiguration, ISchedulingFactory<IFrameworkSchedulingService, ISchedulerImplementationConfiguration>>),
    typeof(ISchedulerType),
    typeof(SchedulerTypes),
    ServiceInterface = typeof(IFrameworkSchedulingService),
    ProviderType = typeof(SchedulerServiceProvider),
    ProviderInterface = typeof(ISchedulerServiceProvider),
    ServiceCategory = "Scheduler")]
public partial class SchedulerTypes : ServiceTypeCollectionBase<
    SchedulerTypeBase<IFrameworkSchedulingService, ISchedulerImplementationConfiguration, ISchedulingFactory<IFrameworkSchedulingService, ISchedulerImplementationConfiguration>>,
    ISchedulerType>
{
    /// <summary>
    /// The connection this domain's configuration rows are read from and written to.
    /// </summary>
    public static string ConfigurationConnection { get; set; } = "PlatformConfiguration";

    // Configure(), Register() and Initialize() are source-generated

    /// <summary>
    /// Sets this collection's Register body: the option collect, then this domain's provider.
    /// </summary>
    /// <remarks>
    /// The provider is one registration for the whole collection and this declaration already names it,
    /// so the body that registers it is written here beside the declaration. Setting it as the phase's
    /// body is what makes it replaceable: an application calling <c>Registration(...)</c> replaces the
    /// collect and this registration together, which is the correct semantic for a host taking over phase 2.
    /// </remarks>
    static SchedulerTypes()
    {
        var collectOptions = RegisterFunc;

        var providerService = typeof(ISchedulerServiceProvider).ToString();

        Registration((builder, loggerFactory) =>
        {
            var log = loggerFactory?.CreateLogger<SchedulerTypes>() ?? NullLogger<SchedulerTypes>.Instance;

            var registered = collectOptions(builder, loggerFactory);
            if (registered.IsFailure)
                return registered;

            var declaredOptions = Options;
            var optionNames = string.Join(", ", declaredOptions.Select(option => option.Name));

            ServiceTypeLog.DomainOptionsCollected(log, nameof(SchedulerTypes), declaredOptions.Length, optionNames);
            ServiceTypeLog.DomainProviderDeclared(log, nameof(SchedulerTypes), providerService);

            builder.Services.TryAddSingleton<ISchedulerConfigurationProvider>(sp =>
                new SchedulerConfigurationProvider(
                    sp.GetService<ILogger<SchedulerConfigurationProvider>>()!,
                    sp.GetRequiredService<IConfigurationGatewayProvider>(),
                    ConfigurationConnection));
            builder.Services.TryAddSingleton<SchedulerConfigurationProvider>(
                sp => (SchedulerConfigurationProvider)sp.GetRequiredService<ISchedulerConfigurationProvider>());
            builder.Services.TryAddSingleton<ImplementationConfigurationProviderBase<SchedulerConfiguration, SchedulerConfigurationCommand>>(
                sp => sp.GetRequiredService<SchedulerConfigurationProvider>());
            builder.Services.TryAddSingleton<IServiceConfigurationProvider<SchedulerConfiguration>>(
                sp => sp.GetRequiredService<SchedulerConfigurationProvider>());

            builder.Services.TryAddSingleton<ScheduleConfigurationProvider>(sp =>
                new ScheduleConfigurationProvider(
                    sp.GetService<ILogger<ScheduleConfigurationProvider>>()!,
                    sp.GetRequiredService<IConfigurationGatewayProvider>(),
                        SchedulerTypes.ConfigurationConnection));
            builder.Services.TryAddSingleton<ImplementationConfigurationProviderBase<ScheduleConfiguration, ScheduleConfigurationCommand>>(
                sp => sp.GetRequiredService<ScheduleConfigurationProvider>());
            builder.Services.TryAddSingleton<IServiceConfigurationProvider<ScheduleConfiguration>>(
                sp => sp.GetRequiredService<ScheduleConfigurationProvider>());

            builder.Services.AddScoped<ISchedulerServiceProvider>(sp =>
            {
                var provider = new SchedulerServiceProvider(
                    sp,
                    sp.GetService<ILoggerFactory>()?.CreateLogger<SchedulerServiceProvider>()
                    ?? NullLogger<SchedulerServiceProvider>.Instance);

                var stLogger = sp.GetService<ILoggerFactory>()?.CreateLogger<SchedulerTypes>()
                    ?? NullLogger<SchedulerTypes>.Instance;
                ServiceTypeLog.DomainProviderConstructing(stLogger, nameof(SchedulerTypes), provider.GetType().Name);
                try
                {
                    if (sp.GetService<ISchedulerConfigurationProvider>() is { } cfgProvider)
                    {
                        var domainResult = provider.Register(cfgProvider);
                        if (domainResult.IsSuccess)
                            ServiceTypeLog.DomainConfigurationSourceAttached(stLogger, nameof(SchedulerTypes), provider.GetType().Name, cfgProvider.GetType().Name);
                        else
                            ServiceTypeLog.DomainConfigurationSourceRejected(stLogger, nameof(SchedulerTypes), provider.GetType().Name, cfgProvider.GetType().Name, domainResult.CurrentMessage);
                    }
                    else
                    {
                        ServiceTypeLog.DomainHasNoConfigurationSource(
                            stLogger,
                            nameof(SchedulerTypes),
                            provider.GetType().Name,
                            typeof(IServiceConfigurationProvider<SchedulerConfiguration>).ToString());
                    }
                }
                catch (Exception ex)
                {
                    ServiceTypeLog.FactoryRegistrationException(stLogger, ex, nameof(SchedulerTypes));
                    throw;
                }
                return provider;
            });

            if (declaredOptions.Length == 0)
                ServiceTypeLog.DomainRegisteredWithNoOptions(log, nameof(SchedulerTypes), providerService);
            else
                ServiceTypeLog.DomainRegistered(log, nameof(SchedulerTypes), declaredOptions.Length, optionNames, providerService);

            return GenericResult<IHostApplicationBuilder>.Success(builder);
        });
    }
}
