using System.Diagnostics.CodeAnalysis;
using Fdw.Abstractions;
using Fdw.Collections;
using Fdw.Configuration;
using Fdw.Services;
using Fdw.Services.Abstractions;
using Fdw.ServiceTypes;
using Fdw.Services.Configuration;
using Fdw.Services.Data.Abstractions;
using Fdw.Services.Scheduling.Abstractions;
using Fdw.Services.Scheduling.Abstractions.Configuration;
using Fdw.Services.Scheduling.Commands;
using Fdw.ServiceTypes.Logging;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.DependencyInjection.Extensions;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Logging.Abstractions;
using System;
using System.Linq;
using Fdw.Results;
using Microsoft.Extensions.Hosting;

namespace Fdw.Services.Scheduling;

/// <summary>
/// Collection of scheduler service types.
/// Generated by ServiceTypeCollectionGenerator with high-performance lookups.
/// </summary>
[ExcludeFromCodeCoverage]
[ServiceTypeCollection(
    typeof(SchedulerTypeBase<IFrameworkSchedulingService, ISchedulerImplementationConfiguration, ISchedulingFactory<IFrameworkSchedulingService, ISchedulerImplementationConfiguration>>),
    typeof(ISchedulerType),
    typeof(SchedulerTypes),
    ServiceInterface = typeof(IFrameworkSchedulingService),
    ProviderType = typeof(SchedulerServiceProvider),
    ProviderInterface = typeof(ISchedulerServiceProvider),
    ServiceCategory = "Scheduler")]
public partial class SchedulerTypes : ServiceTypeCollectionBase<
    SchedulerTypeBase<IFrameworkSchedulingService, ISchedulerImplementationConfiguration, ISchedulingFactory<IFrameworkSchedulingService, ISchedulerImplementationConfiguration>>,
    ISchedulerType>
{
    /// <summary>
    /// The connection this domain's configuration rows are read from and written to.
    /// </summary>
    public static string ConfigurationConnection { get; set; } = "PlatformConfiguration";

    // Configure(), Register() and Initialize() are source-generated

    /// <summary>
    /// Sets this collection's Register body: the option collect, then this domain's provider.
    /// </summary>
    /// <remarks>
    /// The provider is one registration for the whole collection and this declaration already names it,
    /// so the body that registers it is written here beside the declaration. Setting it as the phase's
    /// body is what makes it replaceable: an application calling <c>Registration(...)</c> replaces the
    /// collect and this registration together, which is the correct semantic for a host taking over phase 2.
    /// </remarks>
    static SchedulerTypes()
    {
        var collectOptions = RegisterFunc;

        // Why a local: this closed generic is the DI key a consumer injects, and it is reported at
        // three points below — the deferred declaration, the milestone, and the zero-option warning.
        // Written out three times it is three chances for them to disagree.
        var providerService = typeof(ISchedulerServiceProvider).ToString();

        Registration((builder, loggerFactory) =>
        {
            var log = loggerFactory?.CreateLogger<SchedulerTypes>() ?? NullLogger<SchedulerTypes>.Instance;

            // Why the result is read: this replacement calls the func it captured, and discarding
            // what that returned meant an option that failed to register was followed by this body
            // registering the provider anyway and reporting success.
            var registered = collectOptions(builder, loggerFactory);
            if (registered.IsFailure)
                return registered;

            var declaredOptions = Options;
            var optionNames = string.Join(", ", declaredOptions.Select(option => option.Name));

            ServiceTypeLog.DomainOptionsCollected(log, nameof(SchedulerTypes), declaredOptions.Length, optionNames);
            ServiceTypeLog.DomainProviderDeclared(log, nameof(SchedulerTypes), providerService);

            // Why the collection registers the configuration providers, and under the domain interface:
            // this collection is what resolves ISchedulerConfigurationProvider to attach it, and the
            // owner of a registration is the type that knows the thing exists. Registered on an option
            // instead, the whole domain loses name resolution whenever that option is not referenced.
            // ConfigurationConnection is the one place that names which store these rows live in.
            builder.Services.TryAddSingleton<ISchedulerConfigurationProvider>(sp =>
                new SchedulerConfigurationProvider(
                    sp.GetService<ILogger<SchedulerConfigurationProvider>>()!,
                    sp.GetRequiredService<IConfigurationGatewayProvider>(),
                    ConfigurationConnection));
            builder.Services.TryAddSingleton<SchedulerConfigurationProvider>(
                sp => (SchedulerConfigurationProvider)sp.GetRequiredService<ISchedulerConfigurationProvider>());
            builder.Services.TryAddSingleton<ImplementationConfigurationProviderBase<SchedulerConfiguration, SchedulerConfigurationCommand>>(
                sp => sp.GetRequiredService<SchedulerConfigurationProvider>());
            builder.Services.TryAddSingleton<IServiceConfigurationProvider<SchedulerConfiguration>>(
                sp => sp.GetRequiredService<SchedulerConfigurationProvider>());

            builder.Services.TryAddSingleton<ScheduleConfigurationProvider>(sp =>
                new ScheduleConfigurationProvider(
                    sp.GetService<ILogger<ScheduleConfigurationProvider>>()!,
                    sp.GetRequiredService<IConfigurationGatewayProvider>()));
            builder.Services.TryAddSingleton<ImplementationConfigurationProviderBase<ScheduleConfiguration, ScheduleConfigurationCommand>>(
                sp => sp.GetRequiredService<ScheduleConfigurationProvider>());
            builder.Services.TryAddSingleton<IServiceConfigurationProvider<ScheduleConfiguration>>(
                sp => sp.GetRequiredService<ScheduleConfigurationProvider>());

            builder.Services.AddScoped<ISchedulerServiceProvider>(sp =>
            {
                var provider = new SchedulerServiceProvider(
                    sp,
                    sp.GetService<ILoggerFactory>()?.CreateLogger<SchedulerServiceProvider>()
                    ?? NullLogger<SchedulerServiceProvider>.Instance);

                // Why ILogger<SchedulerTypes> and not CreateLogger("SchedulerTypes"): SourceContext then
                // carries the namespace-qualified collection, and the category cannot drift from the type
                // it claims to name. The provider logs its own lines under its own type, so the two layers
                // read base-then-derived rather than collapsing onto one category.
                var stLogger = sp.GetService<ILoggerFactory>()?.CreateLogger<SchedulerTypes>()
                    ?? NullLogger<SchedulerTypes>.Instance;
                ServiceTypeLog.DomainProviderConstructing(stLogger, nameof(SchedulerTypes), provider.GetType().Name);
                try
                {
                    if (sp.GetService<ISchedulerConfigurationProvider>() is { } cfgProvider)
                    {
                        // Why the result is read: a provider that did not take its parent still constructs, and
                        // every later read silently misses. The failure has to be said out loud here or nowhere.
                        var domainResult = provider.Register(cfgProvider);
                        if (domainResult.IsSuccess)
                            ServiceTypeLog.DomainConfigurationSourceAttached(stLogger, nameof(SchedulerTypes), provider.GetType().Name, cfgProvider.GetType().Name);
                        else
                            ServiceTypeLog.DomainConfigurationSourceRejected(stLogger, nameof(SchedulerTypes), provider.GetType().Name, cfgProvider.GetType().Name, domainResult.CurrentMessage);
                    }
                    else
                    {
                        // Why Critical, and why the collection says it rather than the provider: from inside
                        // the provider a null parent is indistinguishable from a domain that needs none. This
                        // is the one place that knows one was meant to arrive, and without it the domain fails
                        // every lookup by name for the life of the scope with nothing pointing back here.
                        ServiceTypeLog.DomainHasNoConfigurationSource(
                            stLogger,
                            nameof(SchedulerTypes),
                            provider.GetType().Name,
                            typeof(IServiceConfigurationProvider<SchedulerConfiguration>).ToString());
                    }
                }
                catch (Exception ex)
                {
                    // Why rethrow: a throw here was previously silent, and a provider that failed to take
                    // its parent is unusable in a way that only surfaces much later.
                    ServiceTypeLog.FactoryRegistrationException(stLogger, ex, nameof(SchedulerTypes));
                    throw;
                }
                return provider;
            });

            // Why the milestone comes after the registration and not before: it states that the domain
            // finished phase 2, which is only true once the provider is actually in the container.
            if (declaredOptions.Length == 0)
                ServiceTypeLog.DomainRegisteredWithNoOptions(log, nameof(SchedulerTypes), providerService);
            else
                ServiceTypeLog.DomainRegistered(log, nameof(SchedulerTypes), declaredOptions.Length, optionNames, providerService);

            return GenericResult<IHostApplicationBuilder>.Success(builder);
        });
    }
}
