using System.Diagnostics.CodeAnalysis;

namespace Fdw.Services;

/// <summary>
/// Extension methods for registering service types with the dependency injection container.
/// Note: The actual registration methods that use the generated ConnectionTypes and NotificationTypes
/// collections will be generated by the Enhanced Enums source generator at compile time.
/// </summary>
[ExcludeFromCodeCoverage]
public static class ServiceCollectionExtensions
{
    // The following extension methods will be generated by Enhanced Enums source generator:
    // - AddConnectionTypes(this IServiceCollection services)
    // - AddNotificationTypes(this IServiceCollection services)
    // - AddAllServiceTypes(this IServiceCollection services)

    // These methods will be available at runtime after the Enhanced Enums generator
    // processes the ConnectionTypeBase and NotificationTypeBase classes.
}
