using System.Diagnostics.CodeAnalysis;
using Fdw.Collections;
using Fdw.Services.Abstractions;
using Fdw.Services.Data.Abstractions;
using Fdw.Services.Abstractions.Health.Monitoring;
using Fdw.ServiceTypes;
using Fdw.ServiceTypes.Logging;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Logging.Abstractions;
using System;
using System.Linq;
using Fdw.Results;
using Microsoft.Extensions.DependencyInjection.Extensions;
using Microsoft.Extensions.Hosting;

namespace Fdw.Services.HealthChecks.Monitoring;

/// <summary>
/// ServiceTypeCollection for health monitor service types.
/// Generated by ServiceTypeCollectionGenerator with high-performance lookups.
/// </summary>
/// <remarks>
/// <para>
/// The health monitor is a full service domain: options ("Local" in this assembly, "HttpClient" in
/// <c>Fdw.Web.Analytics.Clients</c>) register factories with the domain provider, and consumers depend
/// on the provider (<see cref="IPlatformServiceProvider{TService,TConfiguration}"/> of
/// <see cref="IHealthMonitorService"/>/<see cref="HealthMonitorConfiguration"/>) — never on a direct
/// <see cref="IHealthMonitorService"/> registration. Which implementation a host runs is that host's
/// <c>HealthMonitors</c> appsettings row (<c>ServiceOptionType</c>), resolved at first use — not a
/// registration-order race.
/// </para>
/// <para>
/// Cross-assembly options are registered via the <c>[ModuleInitializer]</c> generated by
/// <c>Fdw.Registration.SourceGenerators</c> in the entry-point project.
/// </para>
/// </remarks>
[ExcludeFromCodeCoverage]
[ServiceTypeCollection(
    typeof(HealthMonitorTypeBase<IHealthMonitorService, IHealthMonitorFactory<IHealthMonitorService, HealthMonitorConfiguration>, HealthMonitorConfiguration>),
    typeof(IHealthMonitorType),
    typeof(HealthMonitorTypes),
    ServiceInterface = typeof(IHealthMonitorService),
    ProviderType = typeof(HealthMonitorProvider),
    ProviderInterface = typeof(IHealthMonitorProvider),
    ServiceCategory = "HealthMonitor")]
public partial class HealthMonitorTypes : ServiceTypeCollectionBase<
    HealthMonitorTypeBase<IHealthMonitorService, IHealthMonitorFactory<IHealthMonitorService, HealthMonitorConfiguration>, HealthMonitorConfiguration>,
    IHealthMonitorType>
{

    /// <summary>
    /// Sets this collection's Register body: the option collect, then this domain's provider.
    /// </summary>
    /// <remarks>
    /// The provider is one registration for the whole collection and this declaration already names it,
    /// so the body that registers it is written here beside the declaration. Setting it as the phase's
    /// body is what makes it replaceable: an application calling <c>Registration(...)</c> replaces the
    /// collect and this registration together, which is the correct semantic for a host taking over phase 2.
    /// </remarks>
    /// <summary>
    /// The connection this domain's configuration rows are read from and written to.
    /// </summary>
    /// <remarks>
    /// Which monitor a host runs is per-host rather than shared across hosts, so this domain defaults
    /// to <c>ServerConfiguration</c> — the store for boot-time and near-static server values — where a
    /// domain whose rows are shared defaults to <c>PlatformConfiguration</c>.
    /// </remarks>
    public static string ConfigurationConnection { get; set; } = "PlatformConfiguration";

    static HealthMonitorTypes()
    {
        var collectOptions = RegisterFunc;

        var providerService = typeof(IHealthMonitorProvider).ToString();

        Registration((builder, loggerFactory) =>
        {
            var log = loggerFactory?.CreateLogger<HealthMonitorTypes>() ?? NullLogger<HealthMonitorTypes>.Instance;

            builder.Services.TryAddSingleton<IHealthMonitorConfigurationProvider>(sp =>
                new HealthMonitorConfigurationProvider(
                    sp.GetService<ILogger<HealthMonitorConfigurationProvider>>()!,
                    sp.GetRequiredService<IConfigurationGatewayProvider>(),
                    ConfigurationConnection));
            builder.Services.TryAddSingleton<IServiceConfigurationProvider<HealthMonitorConfiguration>>(
                sp => sp.GetRequiredService<HealthMonitorConfigurationProvider>());

            var collected = collectOptions(builder, loggerFactory);
            if (collected.IsFailure)
                return collected;

            var declaredOptions = Options;
            var optionNames = string.Join(", ", declaredOptions.Select(option => option.Name));

            ServiceTypeLog.DomainOptionsCollected(log, nameof(HealthMonitorTypes), declaredOptions.Length, optionNames);
            ServiceTypeLog.DomainProviderDeclared(log, nameof(HealthMonitorTypes), providerService);

            builder.Services.AddScoped<IHealthMonitorProvider>(sp =>
            {
                var provider = new HealthMonitorProvider(
                    sp,
                    sp.GetService<ILoggerFactory>()?.CreateLogger<HealthMonitorProvider>()
                    ?? NullLogger<HealthMonitorProvider>.Instance);

                var stLogger = sp.GetService<ILoggerFactory>()?.CreateLogger<HealthMonitorTypes>()
                    ?? NullLogger<HealthMonitorTypes>.Instance;
                ServiceTypeLog.DomainProviderConstructing(stLogger, nameof(HealthMonitorTypes), provider.GetType().Name);
                try
                {
                    if (sp.GetService<IHealthMonitorConfigurationProvider>() is { } cfgProvider)
                    {
                        var domainResult = provider.Register(cfgProvider);
                        if (domainResult.IsSuccess)
                            ServiceTypeLog.DomainConfigurationSourceAttached(stLogger, nameof(HealthMonitorTypes), provider.GetType().Name, cfgProvider.GetType().Name);
                        else
                            ServiceTypeLog.DomainConfigurationSourceRejected(stLogger, nameof(HealthMonitorTypes), provider.GetType().Name, cfgProvider.GetType().Name, domainResult.CurrentMessage);
                    }
                    else
                    {
                        ServiceTypeLog.DomainHasNoConfigurationSource(
                            stLogger,
                            nameof(HealthMonitorTypes),
                            provider.GetType().Name,
                            typeof(IServiceConfigurationProvider<HealthMonitorConfiguration>).ToString());
                    }
                }
                catch (Exception ex)
                {
                    ServiceTypeLog.FactoryRegistrationException(stLogger, ex, nameof(HealthMonitorTypes));
                    throw;
                }
                return provider;
            });

            if (declaredOptions.Length == 0)
                ServiceTypeLog.DomainRegisteredWithNoOptions(log, nameof(HealthMonitorTypes), providerService);
            else
                ServiceTypeLog.DomainRegistered(log, nameof(HealthMonitorTypes), declaredOptions.Length, optionNames, providerService);

            return GenericResult<IHostApplicationBuilder>.Success(builder);
        });
    }
}
