using System.Diagnostics.CodeAnalysis;
using Fdw.Collections;
using Fdw.Services.Abstractions;
using Fdw.Services.Abstractions.Health.Monitoring;
using Fdw.ServiceTypes;
using Fdw.ServiceTypes.Logging;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Logging.Abstractions;
using System;
using System.Linq;
using Fdw.Results;
using Microsoft.Extensions.DependencyInjection.Extensions;
using Microsoft.Extensions.Hosting;

namespace Fdw.Services.HealthChecks.Monitoring;

/// <summary>
/// ServiceTypeCollection for health monitor service types.
/// Generated by ServiceTypeCollectionGenerator with high-performance lookups.
/// </summary>
/// <remarks>
/// <para>
/// The health monitor is a full service domain: options ("Local" in this assembly, "HttpClient" in
/// <c>Fdw.Web.Analytics.Clients</c>) register factories with the domain provider, and consumers depend
/// on the provider (<see cref="IPlatformServiceProvider{TService,TConfiguration}"/> of
/// <see cref="IHealthMonitorService"/>/<see cref="HealthMonitorConfiguration"/>) — never on a direct
/// <see cref="IHealthMonitorService"/> registration. Which implementation a host runs is that host's
/// <c>HealthMonitors</c> appsettings row (<c>ServiceOptionType</c>), resolved at first use — not a
/// registration-order race.
/// </para>
/// <para>
/// Cross-assembly options are registered via the <c>[ModuleInitializer]</c> generated by
/// <c>Fdw.Registration.SourceGenerators</c> in the entry-point project.
/// </para>
/// </remarks>
[ExcludeFromCodeCoverage]
[ServiceTypeCollection(
    typeof(HealthMonitorTypeBase<IHealthMonitorService, IHealthMonitorFactory<IHealthMonitorService, HealthMonitorConfiguration>, HealthMonitorConfiguration>),
    typeof(IHealthMonitorType),
    typeof(HealthMonitorTypes),
    ServiceInterface = typeof(IHealthMonitorService),
    // Why: the concrete domain provider + domain-named interface, exactly like ConnectionTypes
    // (DefaultConnectionProvider/IConnectionProvider) — consumers inject IHealthMonitorProvider,
    // so the generated Register must bind THAT interface, not the generic IPlatformServiceProvider<,>.
    ProviderType = typeof(DefaultHealthMonitorProvider),
    ProviderInterface = typeof(IHealthMonitorProvider),
    ServiceCategory = "HealthMonitor")]
public partial class HealthMonitorTypes : ServiceTypeCollectionBase<
    HealthMonitorTypeBase<IHealthMonitorService, IHealthMonitorFactory<IHealthMonitorService, HealthMonitorConfiguration>, HealthMonitorConfiguration>,
    IHealthMonitorType>
{

    /// <summary>
    /// Sets this collection's Register body: the option collect, then this domain's provider.
    /// </summary>
    /// <remarks>
    /// The provider is one registration for the whole collection and this declaration already names it,
    /// so the body that registers it is written here beside the declaration. Setting it as the phase's
    /// body is what makes it replaceable: an application calling <c>Registration(...)</c> replaces the
    /// collect and this registration together, which is the correct semantic for a host taking over phase 2.
    /// </remarks>
    static HealthMonitorTypes()
    {
        var collectOptions = RegisterFunc;

        // Why a local: this closed generic is the DI key a consumer injects, and it is reported at
        // three points below — the deferred declaration, the milestone, and the zero-option warning.
        // Written out three times it is three chances for them to disagree.
        var providerService = typeof(IHealthMonitorProvider).ToString();

        Registration((builder, loggerFactory) =>
        {
            var log = loggerFactory?.CreateLogger<HealthMonitorTypes>() ?? NullLogger<HealthMonitorTypes>.Instance;

            // Why this collection registers the provider and the provider does not register itself: the
            // owner of a registration is the type that knows the thing exists, and this collection ships
            // beside it. It goes before the collect because each monitor option registers itself against
            // this provider, so it has to be there when the member cycle runs.
            builder.Services.TryAddSingleton<HealthMonitorConfigurationProvider>();
            builder.Services.TryAddSingleton<IServiceConfigurationProvider<HealthMonitorConfiguration>>(
                sp => sp.GetRequiredService<HealthMonitorConfigurationProvider>());

            // Why the collect's result is read and returned: this body composes ONTO the default collect,
            // and it used to discard what the collect returned — so an option that failed to register was
            // followed by this method registering the provider anyway and reporting success. The
            // provider would then resolve and serve a collection that is missing a member. Stopping
            // here means the caller learns about the first failure instead of a later, stranger one.
            var collected = collectOptions(builder, loggerFactory);
            if (collected.IsFailure)
                return collected;

            var declaredOptions = Options;
            var optionNames = string.Join(", ", declaredOptions.Select(option => option.Name));

            ServiceTypeLog.DomainOptionsCollected(log, nameof(HealthMonitorTypes), declaredOptions.Length, optionNames);
            ServiceTypeLog.DomainProviderDeclared(log, nameof(HealthMonitorTypes), providerService);

            builder.Services.AddScoped<IHealthMonitorProvider>(sp =>
            {
                var provider = new DefaultHealthMonitorProvider(
                    sp,
                    sp.GetService<ILoggerFactory>()?.CreateLogger<DefaultHealthMonitorProvider>()
                    ?? NullLogger<DefaultHealthMonitorProvider>.Instance);

                // Why ILogger<HealthMonitorTypes> and not CreateLogger("HealthMonitorTypes"): SourceContext then
                // carries the namespace-qualified collection, and the category cannot drift from the
                // type it claims to name. The provider logs its own lines under its own type, so the
                // two layers read base-then-derived rather than collapsing onto one category.
                var stLogger = sp.GetService<ILoggerFactory>()?.CreateLogger<HealthMonitorTypes>()
                    ?? NullLogger<HealthMonitorTypes>.Instance;
                ServiceTypeLog.DomainProviderConstructing(stLogger, nameof(HealthMonitorTypes), provider.GetType().Name);
                try
                {
                    if (sp.GetService<IServiceConfigurationProvider<HealthMonitorConfiguration>>() is { } cfgProvider)
                    {
                        // Why the result is read: a provider that did not take its parent still constructs, and
                        // every later read silently misses. The failure has to be said out loud here or nowhere.
                        var domainResult = provider.Register(cfgProvider);
                        if (domainResult.IsSuccess)
                            ServiceTypeLog.DomainConfigurationSourceAttached(stLogger, nameof(HealthMonitorTypes), provider.GetType().Name, cfgProvider.GetType().Name);
                        else
                            ServiceTypeLog.DomainConfigurationSourceRejected(stLogger, nameof(HealthMonitorTypes), provider.GetType().Name, cfgProvider.GetType().Name, domainResult.CurrentMessage);
                    }
                    else
                    {
                        // Why Critical, and why the collection says it rather than the provider: from
                        // inside the provider a null parent is indistinguishable from a domain that needs
                        // none. This is the one place that knows one was meant to arrive, and without it
                        // the domain fails every lookup by name for the life of the scope with nothing
                        // pointing back here.
                        ServiceTypeLog.DomainHasNoConfigurationSource(
                            stLogger,
                            nameof(HealthMonitorTypes),
                            provider.GetType().Name,
                            typeof(IServiceConfigurationProvider<HealthMonitorConfiguration>).ToString());
                    }
                }
                catch (Exception ex)
                {
                    // Why rethrow: a throw here was previously silent, and a provider that failed to take
                    // its parent is unusable in a way that only surfaces much later.
                    ServiceTypeLog.FactoryRegistrationException(stLogger, ex, nameof(HealthMonitorTypes));
                    throw;
                }
                return provider;
            });

            // Why the milestone comes after the registration and not before: it states that the domain
            // finished phase 2, which is only true once the provider is actually in the container.
            if (declaredOptions.Length == 0)
                ServiceTypeLog.DomainRegisteredWithNoOptions(log, nameof(HealthMonitorTypes), providerService);
            else
                ServiceTypeLog.DomainRegistered(log, nameof(HealthMonitorTypes), declaredOptions.Length, optionNames, providerService);

            return GenericResult<IHostApplicationBuilder>.Success(builder);
        });
    }
}
