<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <Content Include="xunit.runner.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\Fdw.MessageLogging.Abstractions\Fdw.MessageLogging.Abstractions.csproj" />
  </ItemGroup>
  <PropertyGroup>
    <!-- Only include Fdw.MessageLogging.Abstractions in coverage -->
    <Include>[Fdw.MessageLogging.Abstractions]*</Include>
    <!-- Exclude everything else -->
    <Exclude>[xunit.*]*,[Moq]*,[Shouldly]*</Exclude>
  </PropertyGroup>
</Project>
