<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <LangVersion>preview</LangVersion>
    <RootNamespace>Fdw.Data.Serialization</RootNamespace>
    <AssemblyName>Fdw.Data.Serialization</AssemblyName>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Fdw.Data.Abstractions\Fdw.Data.Abstractions.csproj" />
    <ProjectReference Include="..\Fdw.Data.Builders\Fdw.Data.Builders.csproj" />
    <ProjectReference Include="..\Fdw.Data.Files\Fdw.Data.Files.csproj" />
  </ItemGroup>

</Project>
