using System.Diagnostics.CodeAnalysis;
using Fdw.Collections;
using Fdw.VsCodeShell.Abstractions;

namespace Fdw.VsCodeShell;

/// <summary>
/// ServiceTypeCollection of every VS Code command contributed by the host and its referenced packages.
/// The manifest served at <c>GET /vscode/manifest</c> is projected from this collection.
/// </summary>
/// <remarks>
/// <para>
/// Commands declared in downstream packages are registered by a <c>[ModuleInitializer]</c> generated by
/// <c>Fdw.Registration.SourceGenerators</c> in the entry-point host, so referencing a package that
/// declares commands is itself the intent to contribute them — no host-side wiring per command.
/// </para>
/// <para>
/// No <c>ConfigurationType</c>, <c>ConfigurationInterface</c>, or <c>ProviderType</c>: commands ship in code
/// and have no configuration records, so the generator emits no IOptions binding and no provider. This is
/// the same config-free shape as <c>ApiClientTypes</c>.
/// </para>
/// </remarks>
[ExcludeFromCodeCoverage]
[ServiceTypeCollection(
    typeof(VsCodeCommandTypeBase<IVsCodeCommandHandler>),
    typeof(IVsCodeCommandType),
    typeof(VsCodeCommandTypes),
    ServiceCategory = "VsCodeCommand")]
public partial class VsCodeCommandTypes
    : ServiceTypeCollectionBase<VsCodeCommandTypeBase<IVsCodeCommandHandler>, IVsCodeCommandType> { }
