using Fdw.Collections;
using Fdw.Collections.Attributes;
using Fdw.Commands.Data.Abstractions;
using Fdw.Services.Connections.Abstractions;
using System.Diagnostics.CodeAnalysis;

namespace Fdw.Services.Connections.Abstractions;

/// <summary>
/// Collection of connection command types.
/// Generated by TypeCollectionGenerator with high-performance lookups.
/// Provides unified access to all connection commands in the domain.
/// </summary>
[ExcludeFromCodeCoverage]
[TypeCollection(typeof(IConnectionCommand), typeof(IConnectionCommand), typeof(ConnectionCommands))]
public abstract partial class ConnectionCommands : TypeCollectionBase<IConnectionCommand>
{
}