namespace Fdw.Collections.SourceGenerators.Tests.Mocks;

using System.Linq;

/// <summary>
/// Mock generated code templates that define expected behavior.
/// These serve as the specification for what the real generator should produce.
/// </summary>
internal static class MockGeneratedCode
{
    public static string GenerateMutableCollection(string className, string returnType)
    {
        return $@"// <auto-generated/>
using System;
using System.Collections.Concurrent;
using System.Collections.Generic;
using System.Linq;

namespace Test;

public partial class {className}
{{
    private static readonly ConcurrentDictionary<int, {returnType}> _byId = new();
    private static readonly ConcurrentDictionary<string, {returnType}> _byName = new();

    public static void Register({returnType} item)
    {{
        if (item == null) throw new ArgumentNullException(nameof(item));
        _byId.TryAdd(item.Id, item);
        _byName.TryAdd(item.Name, item);
    }}

    public static {returnType} ById(int id) =>
        _byId.GetValueOrDefault(id) ?? Empty;

    public static {returnType} ByName(string name) =>
        _byName.GetValueOrDefault(name) ?? Empty;

    public static IReadOnlyCollection<{returnType}> All() => _byId.Values;

    private static readonly {returnType} _empty = new Empty{returnType}();
    public static {returnType} Empty => _empty;
}}
";
    }

    public static string GenerateFactoryCollection(string className, string returnType, string[] optionNames)
    {
        var createMethods = string.Join("\n\n    ", optionNames.Select(name =>
            $"public static {returnType} Create{name}() => new {name}Type();"));

        var factoryEntries = string.Join(",\n        ", optionNames.Select(name =>
            $"[\"{name}\"] = () => new {name}Type()"));

        return $@"// <auto-generated/>
using System;
using System.Collections.Generic;

namespace Test;

public partial class {className}
{{
    {createMethods}

    private static readonly Dictionary<string, Func<{returnType}>> _factories = new()
    {{
        {factoryEntries}
    }};

    public static void Register({returnType} item)
    {{
        if (item == null) throw new ArgumentNullException(nameof(item));
        _factories[item.Name] = () => item;
    }}

    public static {returnType} CreateByName(string name)
    {{
        return _factories.TryGetValue(name, out var factory) ? factory() : throw new KeyNotFoundException();
    }}

    private static readonly {returnType} _empty = new Empty{returnType}();
    public static {returnType} Empty => _empty;
}}
";
    }

    public static string GenerateImmutableCollection(string className, string returnType, string[] optionNames)
    {
        var staticProperties = string.Join("\n\n    ", optionNames.Select(name =>
            $@"private static {returnType}? _{name.ToLower()};
    public static {returnType} {name} => _{name.ToLower()} ??= new {name}Type();"));

        var staticCtorItems = string.Join(", ", optionNames.Select(n => n));

        return $@"// <auto-generated/>
using System;
using System.Collections.Frozen;
using System.Collections.Generic;
using System.Linq;

namespace Test;

public partial class {className}
{{
    {staticProperties}

    private static readonly FrozenDictionary<int, {returnType}> _byId;
    private static readonly FrozenDictionary<string, {returnType}> _byName;

    static {className}()
    {{
        var items = new[] {{ {staticCtorItems} }};
        _byId = items.ToFrozenDictionary(x => x.Id);
        _byName = items.ToFrozenDictionary(x => x.Name);
    }}

    public static {returnType} ById(int id) =>
        _byId.GetValueOrDefault(id) ?? Empty;

    public static {returnType} ByName(string name) =>
        _byName.GetValueOrDefault(name) ?? Empty;

    public static IReadOnlyCollection<{returnType}> All() => _byId.Values;

    private static readonly {returnType} _empty = new Empty{returnType}();
    public static {returnType} Empty => _empty;
}}
";
    }

    public static string GenerateParentCollection(string className, string returnType, (string Name, string TypeName)[] children)
    {
        var childProperties = string.Join("\n\n    ", children.Select(child =>
            $@"private static {returnType}? _{child.Name.ToLower()};
    public static {returnType} {child.Name} => _{child.Name.ToLower()} ??= {child.TypeName}.Empty();"));

        var childNames = string.Join(", ", children.Select(c => c.Name));

        return $@"// <auto-generated/>
using System;
using System.Collections.Frozen;
using System.Collections.Generic;
using System.Linq;

namespace Test;

public partial class {className}
{{
    {childProperties}

    private static readonly FrozenDictionary<string, {returnType}> _byName;

    static {className}()
    {{
        var items = new[] {{ {childNames} }};
        _byName = items.ToFrozenDictionary(x => x.Id);
    }}

    public static {returnType} ByName(string name) =>
        _byName.GetValueOrDefault(name) ?? Empty;

    public static IReadOnlyCollection<{returnType}> All() => _byName.Values;

    private static readonly {returnType} _empty = new Empty{className}();
    public static {returnType} Empty => _empty;
}}
";
    }
}
