<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <Content Include="xunit.runner.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="FluentValidation" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\Fdw.Data.DataSets\Fdw.Data.DataSets.csproj" />
  </ItemGroup>
  <PropertyGroup>
    <Include>[Fdw.Data.DataSets]*;[Fdw.Data.Transformers.Abstractions]*</Include>
    <Exclude>[Fdw.*.Abstractions]*;[Fdw.Messages]*;[Fdw.Results]*;[Fdw.Collections]*</Exclude>
  </PropertyGroup>
</Project>
