using System.Diagnostics.CodeAnalysis;
using Fdw.Collections;
using Fdw.Services;
using Fdw.Services.Abstractions;
using Fdw.ServiceTypes;
using Fdw.Services.Credentials.Abstractions;
using Fdw.ServiceTypes.Logging;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Logging.Abstractions;
using System;
using System.Linq;
using Fdw.Results;
using Microsoft.Extensions.Hosting;

namespace Fdw.Services.Credentials;

/// <summary>
/// Collection of credential service types.
/// Generated by ServiceTypeCollectionGenerator with high-performance lookups.
/// </summary>
/// <remarks>
/// <para>
/// <c>RestrictToCurrentCompilation</c> is <c>true</c>: the credential domain default
/// (the SQL option) lives in a SIBLING assembly (<c>Fdw.Services.Credentials.Sql</c>),
/// not here. There is no same-assembly option, so this collection compiles with an empty option
/// set (generator emits the <c>NotFound</c> sentinel). The cross-assembly Sql option is registered
/// at the entry-point app via its Registration.SourceGenerators module initializer — package
/// reference IS the registration intent.
/// </para>
/// </remarks>
[ExcludeFromCodeCoverage]
[ServiceTypeCollection(
    typeof(CredentialServiceTypeBase<ICredentialService, ICredentialServiceFactory<ICredentialService, CredentialServiceConfiguration>, CredentialServiceConfiguration>),
    typeof(ICredentialServiceType),
    typeof(CredentialServiceTypes),
    GenerateProvider = true,
    ServiceInterface = typeof(ICredentialService),
    ConfigurationType = typeof(CredentialServiceConfiguration),
    ProviderType = typeof(CredentialServiceProvider),
    ProviderInterface = typeof(ICredentialServiceProvider),
    ServiceCategory = "CredentialService",
    RestrictToCurrentCompilation = true,
    Group = 5)]
public partial class CredentialServiceTypes : ServiceTypeCollectionBase<
    CredentialServiceTypeBase<ICredentialService, ICredentialServiceFactory<ICredentialService, CredentialServiceConfiguration>, CredentialServiceConfiguration>,
    ICredentialServiceType<ICredentialService, ICredentialServiceFactory<ICredentialService, CredentialServiceConfiguration>, CredentialServiceConfiguration>>
{
    // Configure(), Register() and Initialize() are source-generated

    /// <summary>
    /// Sets this collection's Register body: the option sweep, then this domain's provider.
    /// </summary>
    /// <remarks>
    /// The provider is one registration for the whole collection and this declaration already names it,
    /// so the body that registers it is written here beside the declaration. Setting it as the phase's
    /// body is what makes it replaceable: an application calling <c>Registration(...)</c> replaces the
    /// sweep and this registration together, which is the correct semantic for a host taking over phase 2.
    /// </remarks>
    static CredentialServiceTypes()
    {
        var sweepOptions = RegisterFunc;

        // Why a local: this closed generic is the DI key a consumer injects, and it is reported at
        // three points below — the deferred declaration, the milestone, and the zero-option warning.
        // Written out three times it is three chances for them to disagree.
        var providerService = typeof(ICredentialServiceProvider).ToString();

        Registration((builder, loggerFactory) =>
        {
            var log = loggerFactory?.CreateLogger<CredentialServiceTypes>() ?? NullLogger<CredentialServiceTypes>.Instance;

            // Why the result is read: this replacement calls the func it captured, and discarding
            // what that returned meant an option that failed to register was followed by this body
            // registering the provider anyway and reporting success.
            var registered = sweepOptions(builder, loggerFactory);
            if (registered.IsFailure)
                return registered;

            var declaredOptions = Options;
            var optionNames = string.Join(", ", declaredOptions.Select(option => option.Name));

            ServiceTypeLog.DomainOptionSweepCompleted(log, nameof(CredentialServiceTypes), declaredOptions.Length, optionNames);
            ServiceTypeLog.DomainProviderDeclared(log, nameof(CredentialServiceTypes), providerService);

            builder.Services.AddScoped<ICredentialServiceProvider>(sp =>
            {
                var provider = new CredentialServiceProvider(
                    sp,
                    sp.GetService<ILoggerFactory>()?.CreateLogger<CredentialServiceProvider>()
                    ?? NullLogger<CredentialServiceProvider>.Instance);

                // Why ILogger<CredentialServiceTypes> and not CreateLogger("CredentialServiceTypes"): SourceContext then
                // carries the namespace-qualified collection, and the category cannot drift from the
                // type it claims to name. The provider logs its own lines under its own type, so the
                // two layers read base-then-derived rather than collapsing onto one category.
                var stLogger = sp.GetService<ILoggerFactory>()?.CreateLogger<CredentialServiceTypes>()
                    ?? NullLogger<CredentialServiceTypes>.Instance;
                ServiceTypeLog.DomainProviderConstructing(stLogger, nameof(CredentialServiceTypes), provider.GetType().Name);
                try
                {
                    if (sp.GetService<IServiceConfigurationProvider<CredentialServiceConfiguration>>() is { } cfgProvider)
                    {
                        // Why the result is read: a provider that did not take its parent still constructs, and
                        // every later read silently misses. The failure has to be said out loud here or nowhere.
                        var parentResult = provider.Register(cfgProvider);
                        if (parentResult.IsSuccess)
                            ServiceTypeLog.DomainConfigurationSourceAttached(stLogger, nameof(CredentialServiceTypes), provider.GetType().Name, cfgProvider.GetType().Name);
                        else
                            ServiceTypeLog.DomainConfigurationSourceRejected(stLogger, nameof(CredentialServiceTypes), provider.GetType().Name, cfgProvider.GetType().Name, parentResult.CurrentMessage);
                    }
                    else
                    {
                        // Why Critical, and why the collection says it rather than the provider: from
                        // inside the provider a null parent is indistinguishable from a domain that needs
                        // none. This is the one place that knows one was meant to arrive, and without it
                        // the domain fails every lookup by name for the life of the scope with nothing
                        // pointing back here.
                        ServiceTypeLog.DomainHasNoConfigurationSource(
                            stLogger,
                            nameof(CredentialServiceTypes),
                            provider.GetType().Name,
                            typeof(IServiceConfigurationProvider<CredentialServiceConfiguration>).ToString());
                    }
                }
                catch (Exception ex)
                {
                    // Why rethrow: a throw here was previously silent, and a provider that failed to take
                    // its parent is unusable in a way that only surfaces much later.
                    ServiceTypeLog.FactoryRegistrationException(stLogger, ex, nameof(CredentialServiceTypes));
                    throw;
                }
                return provider;
            });

            // Why the milestone comes after the registration and not before: it states that the domain
            // finished phase 2, which is only true once the provider is actually in the container.
            if (declaredOptions.Length == 0)
                ServiceTypeLog.DomainRegisteredWithNoOptions(log, nameof(CredentialServiceTypes), providerService);
            else
                ServiceTypeLog.DomainRegistered(log, nameof(CredentialServiceTypes), declaredOptions.Length, optionNames, providerService);

            return GenericResult<IHostApplicationBuilder>.Success(builder);
        });
    }
}
