using System.Diagnostics.CodeAnalysis;
using Fdw.Collections;
using Fdw.Services;
using Fdw.Services.Abstractions;
using Fdw.ServiceTypes;
using Fdw.Services.Credentials.Abstractions;
using Fdw.ServiceTypes.Logging;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Logging.Abstractions;
using System;

namespace Fdw.Services.Credentials;

/// <summary>
/// Collection of credential service types.
/// Generated by ServiceTypeCollectionGenerator with high-performance lookups.
/// </summary>
/// <remarks>
/// <para>
/// <c>RestrictToCurrentCompilation</c> is <c>true</c>: the credential domain default
/// (the SQL option) lives in a SIBLING assembly (<c>Fdw.Services.Credentials.Sql</c>),
/// not here. There is no same-assembly option, so this collection compiles with an empty option
/// set (generator emits the <c>NotFound</c> sentinel). The cross-assembly Sql option is registered
/// at the entry-point app via its Registration.SourceGenerators module initializer — package
/// reference IS the registration intent.
/// </para>
/// </remarks>
[ExcludeFromCodeCoverage]
[ServiceTypeCollection(
    typeof(CredentialServiceTypeBase<ICredentialService, ICredentialServiceFactory<ICredentialService, CredentialServiceConfiguration>, CredentialServiceConfiguration>),
    typeof(ICredentialServiceType),
    typeof(CredentialServiceTypes),
    GenerateProvider = true,
    ServiceInterface = typeof(ICredentialService),
    ConfigurationType = typeof(CredentialServiceConfiguration),
    ProviderType = typeof(CredentialServiceProvider),
    ProviderInterface = typeof(ICredentialServiceProvider),
    ServiceCategory = "CredentialService",
    RestrictToCurrentCompilation = true,
    Group = 5)]
public partial class CredentialServiceTypes : ServiceTypeCollectionBase<
    CredentialServiceTypeBase<ICredentialService, ICredentialServiceFactory<ICredentialService, CredentialServiceConfiguration>, CredentialServiceConfiguration>,
    ICredentialServiceType<ICredentialService, ICredentialServiceFactory<ICredentialService, CredentialServiceConfiguration>, CredentialServiceConfiguration>>
{
    // Configure(), Register() and Initialize() are source-generated

    /// <summary>
    /// Sets this collection's Register body: the option sweep, then this domain's provider.
    /// </summary>
    /// <remarks>
    /// The provider is one registration for the whole collection and this declaration already names it,
    /// so the body that registers it is written here beside the declaration. Setting it as the phase's
    /// body is what makes it replaceable: an application calling <c>Registration(...)</c> replaces the
    /// sweep and this registration together, which is the correct semantic for a host taking over phase 2.
    /// </remarks>
    static CredentialServiceTypes()
    {
        var sweepOptions = RegisterFunc;
        Registration((builder, loggerFactory) =>
        {
            sweepOptions(builder, loggerFactory);
            builder.Services.AddScoped<ICredentialServiceProvider>(sp =>
            {
                var provider = new CredentialServiceProvider(
                    sp,
                    sp.GetService<ILoggerFactory>()?.CreateLogger<CredentialServiceProvider>()
                    ?? NullLogger<CredentialServiceProvider>.Instance);
                var stLogger = sp.GetService<ILoggerFactory>()?.CreateLogger("CredentialServiceTypes");
                try
                {
                    if (sp.GetService<IServiceConfigurationProvider<CredentialServiceConfiguration>>() is { } cfgProvider)
                    {
                        // Why the result is read: a provider that did not take its parent still constructs, and
                        // every later read silently misses. The failure has to be said out loud here or nowhere.
                        var parentResult = provider.Register(cfgProvider);
                        if (!parentResult.IsSuccess && stLogger != null)
                            ServiceTypeLog.FactoryRegistrationFailed(stLogger, "CredentialServiceTypes", parentResult.CurrentMessage ?? "CredentialServiceTypes");
                    }
                }
                catch (Exception ex)
                {
                    // Why rethrow: a throw here was previously silent, and a provider that failed to take
                    // its parent is unusable in a way that only surfaces much later.
                    if (stLogger != null) ServiceTypeLog.FactoryRegistrationException(stLogger, ex, "CredentialServiceTypes");
                    throw;
                }
                return provider;
            });
            return builder;
        });
    }
}
