#!/usr/bin/env bash
# Generates a tailwind-safelist.html from all FDW UI .razor files.
# The output is a single HTML file containing every Tailwind CSS class used
# in FDW component and page packages. Consuming apps reference it via:
#   @source "./path/to/tailwind-safelist.html";
#
# Usage: ./generate-tailwind-safelist.sh [output-path]
#   Default output: public/src/Fdw.UI/wwwroot/tailwind-safelist.html

set -e

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
SRC_DIR="$SCRIPT_DIR/../src"
OUTPUT="${1:-$SRC_DIR/Fdw.UI/wwwroot/tailwind-safelist.html}"

mkdir -p "$(dirname "$OUTPUT")"

# Find all .razor files in UI-related projects
RAZOR_FILES=$(find "$SRC_DIR" \
    \( -path "*Components*" -o -path "*UI.Pages*" -o -path "*UI.Components*" -o -path "*Dashboard*" \) \
    -name "*.razor" -type f 2>/dev/null)

FILE_COUNT=$(echo "$RAZOR_FILES" | grep -c . || true)

# Extract all class="..." values, split into individual classes, filter out
# Razor expressions and C# fragments that leak through the regex.
# Valid Tailwind classes: start with a letter, bracket, or modifier prefix,
# contain only alphanumeric, hyphens, slashes, brackets, colons, dots, percent.
CLASSES=$(echo "$RAZOR_FILES" | xargs grep -ohP '(?:class|Class)="[^"]*"' 2>/dev/null \
    | sed 's/^[Cc]lass="//;s/"$//' \
    | tr ' ' '\n' \
    | grep -v '^$' \
    | grep -v '^@' \
    | grep -v '[(){}]' \
    | grep -v ',' \
    | grep -v '\.$' \
    | grep -vP '^[0-9]+$' \
    | grep -vP '^[A-Z][a-z]' \
    | grep -vP '^\$' \
    | grep -vP '^[=<>?:!]' \
    | sort -u)

CLASS_COUNT=$(echo "$CLASSES" | grep -c . || true)

# Generate HTML file that Tailwind can scan
{
    echo "<!--"
    echo "  Fdw Tailwind Safelist"
    echo "  Auto-generated by generate-tailwind-safelist.sh"
    echo "  $CLASS_COUNT unique classes from $FILE_COUNT .razor files"
    echo "  Do not edit manually — regenerate with: ./scripts/generate-tailwind-safelist.sh"
    echo "-->"
    echo "<div class=\""
    echo "$CLASSES" | tr '\n' ' '
    echo "\">"
    echo "</div>"
} > "$OUTPUT"

echo "Generated $OUTPUT ($CLASS_COUNT classes from $FILE_COUNT files)"
