# Generates a tailwind-safelist.html from all FDW UI .razor files.
# The output is a single HTML file containing every Tailwind CSS class used
# in FDW component and page packages. Consuming apps reference it via:
#   @source "./path/to/tailwind-safelist.html";
#
# Usage: .\generate-tailwind-safelist.ps1 [-Output <path>]
#   Default output: public/src/Fdw.UI/wwwroot/tailwind-safelist.html

param(
    [Parameter(Position = 0)]
    [string]$Output
)

$ErrorActionPreference = "Stop"

$srcDir = Resolve-Path "$PSScriptRoot\..\src"
if (-not $Output) {
    $Output = Join-Path $srcDir "Fdw.UI\wwwroot\tailwind-safelist.html"
}

$outDir = Split-Path $Output -Parent
if (-not (Test-Path $outDir)) {
    New-Item -ItemType Directory -Force -Path $outDir | Out-Null
}

# Find UI-related .razor files (matches the .sh path filters).
$razorFiles = Get-ChildItem -Path $srcDir -Recurse -Filter *.razor -File -ErrorAction SilentlyContinue |
    Where-Object {
        $p = $_.FullName
        $p -like '*Components*' -or $p -like '*UI.Pages*' -or `
        $p -like '*UI.Components*' -or $p -like '*Dashboard*'
    }

$fileCount = $razorFiles.Count

# Extract class="..." / Class="..." values, split on whitespace, then apply the
# same filter chain as the .sh: drop empties, Razor expressions, C# fragments,
# digit-only, PascalCase identifiers, expression-leading tokens.
$classRegex = [regex]'(?:class|Class)="([^"]*)"'
$classes = [System.Collections.Generic.HashSet[string]]::new()

foreach ($file in $razorFiles) {
    $content = Get-Content -Raw -LiteralPath $file.FullName -ErrorAction SilentlyContinue
    if (-not $content) { continue }
    foreach ($m in $classRegex.Matches($content)) {
        foreach ($cls in ($m.Groups[1].Value -split '\s+')) {
            if (-not $cls) { continue }
            if ($cls.StartsWith('@')) { continue }
            if ($cls -match '[(){}]') { continue }
            if ($cls.Contains(',')) { continue }
            if ($cls.EndsWith('.')) { continue }
            if ($cls -match '^[0-9]+$') { continue }
            if ($cls -match '^[A-Z][a-z]') { continue }
            if ($cls.StartsWith('$')) { continue }
            if ($cls -match '^[=<>?:!]') { continue }
            [void]$classes.Add($cls)
        }
    }
}

$sorted = $classes | Sort-Object
$classCount = $sorted.Count

$html = @"
<!--
  Fdw Tailwind Safelist
  Auto-generated by generate-tailwind-safelist.ps1
  $classCount unique classes from $fileCount .razor files
  Do not edit manually — regenerate with: .\scripts\generate-tailwind-safelist.ps1
-->
<div class="
$([string]::Join(' ', $sorted))
">
</div>
"@

Set-Content -Path $Output -Value $html -Encoding UTF8
Write-Host "Generated $Output ($classCount classes from $fileCount files)" -ForegroundColor Green
