# Setup local NuGet folder for multi-project local development
#
# Usage:
#   .\setup-local-nuget.ps1                           # Interactive setup
#   .\setup-local-nuget.ps1 -Path C:\dev\local-nuget  # Specify folder path
#   .\setup-local-nuget.ps1 -SetupProject             # Set up pack-local for a project
#
# This script handles:
#   1. Creating LocalNugetFolder and setting environment variable
#   2. Creating versions.json for tracking package versions across projects
#   3. Generating pack-local.ps1 scripts for individual projects

param(
    [Parameter(Position = 0)]
    [string]$Path,

    [switch]$SetupProject,

    [string]$PackagePrefix,
    [string]$SolutionPath,
    [string]$OutputPath
)

$ErrorActionPreference = "Stop"

function Initialize-LocalNugetFolder {
    param([string]$FolderPath)

    Write-Host "`n=== Initializing Local NuGet Folder ===" -ForegroundColor Cyan

    # Create folder if needed
    if (!(Test-Path $FolderPath)) {
        Write-Host "Creating folder: $FolderPath"
        New-Item -ItemType Directory -Force -Path $FolderPath | Out-Null
        Write-Host "  Created" -ForegroundColor Green
    } else {
        Write-Host "Folder exists: $FolderPath" -ForegroundColor Green
    }

    # Create versions.json if needed
    $versionsPath = Join-Path $FolderPath "versions.json"
    if (!(Test-Path $versionsPath)) {
        Write-Host "Creating versions.json..."
        Set-Content -Path $versionsPath -Value "{}" -Encoding UTF8
        Write-Host "  Created: $versionsPath" -ForegroundColor Green
    } else {
        Write-Host "versions.json exists: $versionsPath" -ForegroundColor Green
    }

    # Create nuget.config template
    $configPath = Join-Path $FolderPath "Local.nuget.config"
    $configContent = @"
<?xml version="1.0" encoding="utf-8"?>
<!--
  Local NuGet configuration for development.
  Copy to your solution folder and add package patterns as needed.
-->
<configuration>
  <packageSources>
    <clear />
    <add key="Local" value="%LocalNugetFolder%" />
    <add key="nuget.org" value="https://api.nuget.org/v3/index.json" />
  </packageSources>

  <packageSourceMapping>
    <packageSource key="Local">
      <!-- Add your package patterns here -->
      <package pattern="Fdw.*" />
    </packageSource>
    <packageSource key="nuget.org">
      <package pattern="*" />
    </packageSource>
  </packageSourceMapping>
</configuration>
"@
    Set-Content -Path $configPath -Value $configContent -Encoding UTF8
    Write-Host "Created: $configPath" -ForegroundColor Green

    # Set environment variable
    if ($env:LocalNugetFolder -ne $FolderPath) {
        Write-Host "`nSetting LocalNugetFolder environment variable..."
        $env:LocalNugetFolder = $FolderPath
        [System.Environment]::SetEnvironmentVariable('LocalNugetFolder', $FolderPath, 'User')
        Write-Host "  Set to: $FolderPath" -ForegroundColor Green
        Write-Host "  Note: Restart terminals/IDEs to pick up persistent setting" -ForegroundColor Yellow
    } else {
        Write-Host "`nLocalNugetFolder already set: $FolderPath" -ForegroundColor Green
    }
}

function New-PackLocalScript {
    param(
        [string]$PackagePrefix,
        [string]$SolutionPath,
        [string]$OutputPath
    )

    $scriptContent = @"
# Pack $PackagePrefix packages to local NuGet folder
# Generated by setup-local-nuget.ps1
#
# Usage: .\pack-local.ps1 [-NoBuild]

param(
    [switch]`$NoBuild
)

`$ErrorActionPreference = "Stop"

if (!`$env:LocalNugetFolder) {
    Write-Error "LocalNugetFolder environment variable not set. Run setup-local-nuget.ps1 first."
    exit 1
}

`$localNuget = `$env:LocalNugetFolder
`$rootDir = Split-Path -Parent `$PSScriptRoot
`$solutionPath = "$SolutionPath"
`$packagePrefix = "$PackagePrefix"

Write-Host "=== Packing `$packagePrefix to Local NuGet ===" -ForegroundColor Cyan
Write-Host "Target: `$localNuget" -ForegroundColor Cyan

# Detect version using Nerdbank.GitVersioning
Write-Host "`n=== Detecting version ===" -ForegroundColor Cyan
`$version = (nbgv get-version -v NuGetPackageVersion)
if (!`$version) {
    Write-Error "Failed to detect version. Ensure Nerdbank.GitVersioning is installed."
    exit 1
}
Write-Host "Version: `$version" -ForegroundColor Green

# Clean old packages
Write-Host "`n=== Cleaning ===" -ForegroundColor Cyan
`$oldProgress = `$ProgressPreference
`$ProgressPreference = 'SilentlyContinue'
Get-ChildItem "`$localNuget\`$packagePrefix.*`$version.nupkg" -ErrorAction SilentlyContinue | Remove-Item -Force
Get-ChildItem "`$localNuget\`$packagePrefix.*`$version.snupkg" -ErrorAction SilentlyContinue | Remove-Item -Force

# Clean NuGet cache
`$cacheRoot = "`$env:USERPROFILE\.nuget\packages"
Get-ChildItem `$cacheRoot -Directory -ErrorAction SilentlyContinue |
    Where-Object { `$_.Name -like "`$(`$packagePrefix.ToLower()).*" } |
    ForEach-Object {
        `$versionFolder = Join-Path `$_.FullName `$version
        if (Test-Path `$versionFolder) {
            Remove-Item `$versionFolder -Recurse -Force -ErrorAction SilentlyContinue
        }
    }
`$ProgressPreference = `$oldProgress

# Pack
Write-Host "`n=== Packing ===" -ForegroundColor Cyan
`$packArgs = @(
    "pack"
    "`$rootDir/`$solutionPath"
    "-c", "Release"
    "-o", `$localNuget
)
if (`$NoBuild) { `$packArgs += "--no-build" }

& dotnet @packArgs
if (`$LASTEXITCODE -ne 0) { exit `$LASTEXITCODE }

# Update versions.json
Write-Host "`n=== Updating versions.json ===" -ForegroundColor Cyan
`$versionsPath = Join-Path `$localNuget "versions.json"
`$versions = @{}
if (Test-Path `$versionsPath) {
    `$versions = Get-Content `$versionsPath -Raw | ConvertFrom-Json -AsHashtable
}
`$versions[`$packagePrefix] = `$version
`$versions | ConvertTo-Json | Set-Content -Path `$versionsPath -Encoding UTF8
Write-Host "  `$packagePrefix = `$version" -ForegroundColor Green

Write-Host "`n=== Success ===" -ForegroundColor Green
Write-Host "`$packagePrefix `$version published to: `$localNuget" -ForegroundColor Green
"@

    # Ensure output directory exists
    $outputDir = Split-Path -Parent $OutputPath
    if (!(Test-Path $outputDir)) {
        New-Item -ItemType Directory -Force -Path $outputDir | Out-Null
    }

    Set-Content -Path $OutputPath -Value $scriptContent -Encoding UTF8
    Write-Host "`nCreated pack-local.ps1: $OutputPath" -ForegroundColor Green
}

# ============================================================================
# Main
# ============================================================================

Write-Host "=== Local NuGet Setup ===" -ForegroundColor Cyan

# Determine folder path
if (!$Path) {
    if ($env:LocalNugetFolder) {
        $Path = $env:LocalNugetFolder
        Write-Host "Using existing LocalNugetFolder: $Path" -ForegroundColor Green
    } else {
        $Path = Read-Host "Enter LocalNugetFolder path (default: C:\development\local-nuget)"
        if (!$Path) { $Path = "C:\development\local-nuget" }
    }
}

# Always ensure folder is initialized
Initialize-LocalNugetFolder -FolderPath $Path

# Check if we should set up a project
$setupProject = $SetupProject
if (!$setupProject -and !$PackagePrefix) {
    $response = Read-Host "`nSet up pack-local.ps1 for a project? [y/N]"
    $setupProject = $response -match "^[Yy]"
}

if ($setupProject -or $PackagePrefix) {
    Write-Host "`n=== Project Setup ===" -ForegroundColor Cyan

    # Get package prefix
    if (!$PackagePrefix) {
        $PackagePrefix = Read-Host "Package prefix (e.g., Fdw, Mc3Po)"
        if (!$PackagePrefix) {
            Write-Error "Package prefix is required"
            exit 1
        }
    }
    Write-Host "  Package prefix: $PackagePrefix" -ForegroundColor Cyan

    # Get solution path
    if (!$SolutionPath) {
        $defaultSlnx = Get-ChildItem "*.slnx" -ErrorAction SilentlyContinue | Select-Object -First 1
        $defaultPrompt = if ($defaultSlnx) { " (default: $($defaultSlnx.Name))" } else { "" }
        $SolutionPath = Read-Host "Solution file path relative to scripts folder$defaultPrompt"
        if (!$SolutionPath -and $defaultSlnx) { $SolutionPath = $defaultSlnx.Name }
        if (!$SolutionPath) {
            Write-Error "Solution path is required"
            exit 1
        }
    }
    Write-Host "  Solution: $SolutionPath" -ForegroundColor Cyan

    # Get output path
    if (!$OutputPath) {
        $defaultOutput = ".\scripts\pack-local.ps1"
        $OutputPath = Read-Host "Output path for pack-local.ps1 (default: $defaultOutput)"
        if (!$OutputPath) { $OutputPath = $defaultOutput }
    }
    $OutputPath = [System.IO.Path]::GetFullPath($OutputPath)
    Write-Host "  Output: $OutputPath" -ForegroundColor Cyan

    # Generate the script
    New-PackLocalScript -PackagePrefix $PackagePrefix -SolutionPath $SolutionPath -OutputPath $OutputPath
}

Write-Host "`n=== Setup Complete ===" -ForegroundColor Green
Write-Host "LocalNugetFolder: $Path" -ForegroundColor Cyan
Write-Host "versions.json: $(Join-Path $Path 'versions.json')" -ForegroundColor Cyan
