using Fdw.Collections;
using Fdw.Collections.Attributes;
using System.Diagnostics.CodeAnalysis;

namespace Fdw.Web.Http.Abstractions.EndPoints;

/// <summary>
/// Collection of endpoint types for HTTP operations.
/// Generated by TypeCollectionGenerator with high-performance lookups.
/// </summary>
[ExcludeFromCodeCoverage]
[TypeCollection(typeof(EndpointTypeBase), typeof(IEndpointType), typeof(EndpointTypes))]
public partial class EndpointTypes : TypeCollectionBase<EndpointTypeBase, IEndpointType>
{
}