using System.Diagnostics.CodeAnalysis;
using Fdw.Abstractions;
using Fdw.Collections;

namespace Fdw.Services.SessionState;

/// <summary>
/// ServiceTypeCollection for session state service types.
/// Generated by ServiceTypeCollectionGenerator with high-performance lookups.
/// </summary>
[ExcludeFromCodeCoverage]
[ServiceTypeCollection(
    typeof(SessionStateServiceTypeBase<IGenericService, ISessionStateServiceFactory>),
    typeof(ISessionStateServiceType),
    typeof(SessionStateTypes),
    ServiceCategory = "SessionState")]
public partial class SessionStateTypes : ServiceTypeCollectionBase<
    SessionStateServiceTypeBase<IGenericService, ISessionStateServiceFactory>,
    ISessionStateServiceType>
{
}
