using System.Diagnostics.CodeAnalysis;
using Fdw.Collections;
using Fdw.Collections.Attributes;

namespace Fdw.Data.SchemaImporters.Abstractions;

/// <summary>
/// TypeCollection for schema importers.
/// Implementations use [TypeOption(typeof(SchemaImporters), "name", RestrictToCurrentCompilation = true)] attribute.
/// Generated by TypeCollectionGenerator with high-performance lookups.
/// </summary>
/// <ExcludedFromCoverage>Source-generated TypeCollection class</ExcludedFromCoverage>
[ExcludeFromCodeCoverage]
[TypeCollection(typeof(ISchemaImporter), typeof(ISchemaImporter), typeof(SchemaImporters))]
public abstract partial class SchemaImporters : TypeCollectionBase<ISchemaImporter>
{
}
