using System.Diagnostics.CodeAnalysis;
using Fdw.Abstractions;
using Fdw.Collections;

namespace Fdw.Services.Data;

/// <summary>
/// ServiceTypeCollection for DataGateway service types.
/// Generated by ServiceTypeCollectionGenerator with high-performance lookups.
/// </summary>
[ExcludeFromCodeCoverage]
[ServiceTypeCollection(
    typeof(DataGatewayTypeBase<IGenericService, IDataGatewayFactory>),
    typeof(IDataGatewayType),
    typeof(DataGatewayTypes),
    ServiceCategory = "DataGateway")]
public partial class DataGatewayTypes : ServiceTypeCollectionBase<
    DataGatewayTypeBase<IGenericService, IDataGatewayFactory>,
    IDataGatewayType>
{
}
