using System.Diagnostics.CodeAnalysis;
using Fdw.Abstractions;
using Fdw.Collections;
using Fdw.Results;
using Fdw.Services.Data.Abstractions;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.DependencyInjection.Extensions;
using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.Logging;

namespace Fdw.Services.Data;

/// <summary>
/// ServiceTypeCollection for DataGateway service types.
/// Generated by ServiceTypeCollectionGenerator with high-performance lookups.
/// </summary>
[ExcludeFromCodeCoverage]
[ServiceTypeCollection(
    typeof(DataGatewayTypeBase<IGenericService, IDataGatewayFactory>),
    typeof(IDataGatewayType),
    typeof(DataGatewayServiceTypes),
    ServiceCategory = "DataGateway")]
public partial class DataGatewayServiceTypes : ServiceTypeCollectionBase<
    DataGatewayTypeBase<IGenericService, IDataGatewayFactory>,
    IDataGatewayType>
{
    /// <summary>Gets or sets the connection this domain's records are read from.</summary>
    /// <remarks>
    /// Settable, because which connection holds a domain's records is the host's to say -- the
    /// default is the one the reference apps ship. Spoken once here rather than at each call site:
    /// an implementation cannot read from a different store than its domain, and a name repeated
    /// per registration is how the two drift apart.
    /// </remarks>
    public static string ConfigurationConnection { get; set; } = "ServerConfiguration";

    static DataGatewayServiceTypes()
    {
        // Domain-level, in the collection: the connection name is a value and the rest comes from
        // DI, which is why it is a factory delegate. It has to exist before an option can register
        // into it, which is why this runs ahead of the option collect.
        Registration((builder, loggerFactory) =>
        {
            builder.Services.TryAddSingleton<DataGatewayDomainConfigurationProvider>(sp =>
                new DataGatewayDomainConfigurationProvider(
                    sp.GetService<ILogger<DataGatewayDomainConfigurationProvider>>(),
                    sp.GetRequiredService<IConfigurationGatewayProvider>(),
                    ConfigurationConnection));

            builder.Services.TryAddSingleton<IDataGatewayConfigurationProvider>(
                sp => sp.GetRequiredService<DataGatewayDomainConfigurationProvider>());

            return GenericResult<IHostApplicationBuilder>.Success(builder);
        });
    }
}
