using System.Diagnostics.CodeAnalysis;
using Fdw.Collections;
using Fdw.Collections.Attributes;

namespace Fdw.Services.Authorization.Abstractions;

/// <summary>
/// Collection of permission action types for authorization and UI rendering.
/// Generated by TypeCollectionGenerator with high-performance lookups.
/// </summary>
/// <remarks>
/// <para>
/// PermissionActions provides the standard set of actions that can be performed on resources.
/// Each action includes visual properties (icon, color) for consistent rendering.
/// </para>
/// <para>
/// Usage in Blazor:
/// <code>
/// var action = PermissionActions.ByName("Read");
/// &lt;MudIcon Icon="@action.Icon" Color="@action.Color" /&gt;
/// </code>
/// </para>
/// </remarks>
[ExcludeFromCodeCoverage]
[TypeCollection(typeof(PermissionActionBase), typeof(IPermissionAction), typeof(PermissionActions))]
public abstract partial class PermissionActions : TypeCollectionBase<PermissionActionBase, IPermissionAction>
{
}