-- =====================================================
-- FractalDataWorks MsSql Secret Manager
-- Schema: secrets (configurable via cfg.MsSqlSecretManager.Schema)
-- Table:  Secret  (configurable via cfg.MsSqlSecretManager.TableName)
-- =====================================================

-- Create the secrets schema
IF NOT EXISTS (SELECT 1 FROM sys.schemas WHERE name = 'secrets')
BEGIN
    EXEC('CREATE SCHEMA [secrets]')
END
GO

-- Create the Secret table for storing secrets
IF NOT EXISTS (SELECT 1 FROM sys.objects WHERE object_id = OBJECT_ID(N'secrets.Secret') AND type = 'U')
BEGIN
    CREATE TABLE [secrets].[Secret]
    (
        [RowId]         UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID()
       ,[SecretKey]     NVARCHAR(256)    NOT NULL
       ,[SecretValue]   NVARCHAR(MAX)    NOT NULL
       ,[Version]       INT              NOT NULL DEFAULT 1
       ,[SecretType]    NVARCHAR(50)     NOT NULL DEFAULT 'Password'
       ,[Description]   NVARCHAR(500)    NULL
       ,[ExpiresAt]     DATETIME2        NULL
       ,[CreateDate]    DATETIME2        NOT NULL DEFAULT SYSUTCDATETIME()
       ,[ModifyDate]    DATETIME2        NOT NULL DEFAULT SYSUTCDATETIME()
       ,[IsCurrent]     BIT              NOT NULL DEFAULT 1
       ,[IsDeleted]     BIT              NOT NULL DEFAULT 0
       ,CONSTRAINT [PK_secrets_Secret] PRIMARY KEY NONCLUSTERED ([RowId])
    )

    -- Enforce one current row per secret key
    CREATE UNIQUE INDEX [IX_secrets_Secret_Current]
        ON [secrets].[Secret] ([SecretKey])
        WHERE [IsCurrent] = 1 AND [IsDeleted] = 0
END
GO

-- Extended properties
IF NOT EXISTS (SELECT 1 FROM sys.extended_properties WHERE major_id = OBJECT_ID('secrets.Secret') AND minor_id = 0 AND name = 'MS_Description')
BEGIN
    EXEC sp_addextendedproperty
        @name = N'MS_Description',
        @value = N'Stores application secrets managed by the MsSql Secret Manager. Uses version-on-write pattern with IsCurrent/IsDeleted flags.',
        @level0type = N'SCHEMA', @level0name = 'secrets',
        @level1type = N'TABLE',  @level1name = 'Secret'
END
GO

-- =====================================================
-- Configuration table: cfg.MsSqlSecretManager
-- (child of cfg.SecretManager, auto-generated by [ManagedConfiguration])
-- =====================================================
-- NOTE: The cfg.MsSqlSecretManager table is generated by the
-- ManagedConfiguration source generator from MsSqlSecretManagerConfiguration.cs.
-- It creates a child table of cfg.SecretManager with columns:
--   RowId, SecretManagerId (FK), ConnectionString, Schema, TableName,
--   CommandTimeoutSeconds, CreateDate, ModifyDate, IsCurrent, IsDeleted
--
-- To manually create for bootstrapping, use:
--
-- IF NOT EXISTS (SELECT 1 FROM sys.objects WHERE object_id = OBJECT_ID(N'cfg.MsSqlSecretManager') AND type = 'U')
-- BEGIN
--     CREATE TABLE [cfg].[MsSqlSecretManager]
--     (
--         [RowId]                  UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID()
--        ,[SecretManagerId]        UNIQUEIDENTIFIER NOT NULL
--        ,[ConnectionString]       NVARCHAR(1000)   NOT NULL
--        ,[Schema]                 NVARCHAR(128)    NOT NULL DEFAULT 'secrets'
--        ,[TableName]              NVARCHAR(128)    NOT NULL DEFAULT 'Secret'
--        ,[CommandTimeoutSeconds]  INT              NOT NULL DEFAULT 30
--        ,[CreateDate]             DATETIME2        NOT NULL DEFAULT SYSUTCDATETIME()
--        ,[ModifyDate]             DATETIME2        NOT NULL DEFAULT SYSUTCDATETIME()
--        ,[IsCurrent]              BIT              NOT NULL DEFAULT 1
--        ,[IsDeleted]              BIT              NOT NULL DEFAULT 0
--        ,CONSTRAINT [PK_cfg_MsSqlSecretManager] PRIMARY KEY NONCLUSTERED ([RowId])
--     )
--
--     CREATE UNIQUE INDEX [IX_cfg_MsSqlSecretManager_Current]
--         ON [cfg].[MsSqlSecretManager] ([SecretManagerId])
--         WHERE [IsCurrent] = 1 AND [IsDeleted] = 0
-- END
-- GO

-- =====================================================
-- Dedicated SQL Login (optional, recommended)
-- =====================================================
-- Create a dedicated login restricted to the secrets schema:
--
-- CREATE LOGIN fdw_secrets WITH PASSWORD = 'YourSecurePassword';
-- CREATE USER fdw_secrets FOR LOGIN fdw_secrets;
-- GRANT SELECT, INSERT, UPDATE ON SCHEMA::secrets TO fdw_secrets;
-- DENY SELECT, INSERT, UPDATE, DELETE ON SCHEMA::cfg TO fdw_secrets;
-- DENY SELECT, INSERT, UPDATE, DELETE ON SCHEMA::auth TO fdw_secrets;
