using Fdw.Commands.Abstractions;

namespace Fdw.Commands.Abstractions.Tests;

public sealed class CommandTypeBaseTests
{
    [Fact]
    [Trait("Priority", "P0")]
    [Trait("Category", "CoreFramework")]
    public void ConstructorInitializesPropertiesCorrectly()
    {
        // Arrange
        var category = new TestCommandCategory();
        var translators = new List<ITranslatorType> { Mock.Of<ITranslatorType>() };

        // Act
        var commandType = new TestCommandType(
            id: 1,
            name: "SqlQuery",
            description: "SQL query command",
            category: category,
            supportedTranslators: translators,
            supportsBatching: true,
            supportsPipelining: true,
            maxBatchSize: 100);

        // Assert
        commandType.Id.ShouldBe(1);
        commandType.Name.ShouldBe("SqlQuery");
        // Description is auto-generated by TypeOptionBase as "Type option: {name}"
        commandType.Description.ShouldBe("Type option: SqlQuery");
        commandType.CommandCategory.ShouldBe(category);
        commandType.SupportedTranslators.ShouldBe(translators);
        commandType.SupportsBatching.ShouldBeTrue();
        commandType.SupportsPipelining.ShouldBeTrue();
        commandType.MaxBatchSize.ShouldBe(100);
    }

    [Fact]
    [Trait("Priority", "P0")]
    [Trait("Category", "CoreFramework")]
    public void ConstructorUsesDefaultBatchingValues()
    {
        // Arrange
        var category = new TestCommandCategory();
        var translators = new List<ITranslatorType>();

        // Act
        var commandType = new TestCommandType(
            id: 2,
            name: "Simple",
            description: "Simple command",
            category: category,
            supportedTranslators: translators);

        // Assert
        commandType.SupportsBatching.ShouldBeFalse();
        commandType.SupportsPipelining.ShouldBeFalse();
        commandType.MaxBatchSize.ShouldBe(1);
    }

    [Fact]
    [Trait("Priority", "P0")]
    [Trait("Category", "CoreFramework")]
    public void ConstructorHandlesEmptyTranslatorList()
    {
        // Arrange
        var category = new TestCommandCategory();
        var translators = new List<ITranslatorType>();

        // Act
        var commandType = new TestCommandType(
            id: 3,
            name: "NoTranslators",
            description: "Command with no translators",
            category: category,
            supportedTranslators: translators);

        // Assert
        commandType.SupportedTranslators.ShouldBeEmpty();
    }

    [Fact]
    [Trait("Priority", "P0")]
    [Trait("Category", "CoreFramework")]
    public void ConstructorHandlesMultipleTranslators()
    {
        // Arrange
        var category = new TestCommandCategory();
        var translators = new List<ITranslatorType>
        {
            Mock.Of<ITranslatorType>(),
            Mock.Of<ITranslatorType>(),
            Mock.Of<ITranslatorType>()
        };

        // Act
        var commandType = new TestCommandType(
            id: 4,
            name: "MultiTranslator",
            description: "Command with multiple translators",
            category: category,
            supportedTranslators: translators);

        // Assert
        commandType.SupportedTranslators.Count.ShouldBe(3);
    }

    [Fact]
    [Trait("Priority", "P0")]
    [Trait("Category", "CoreFramework")]
    public void CommandInterfaceTypeReturnsGenericCommandByDefault()
    {
        // Arrange
        var category = new TestCommandCategory();
        var translators = new List<ITranslatorType>();

        // Act
        var commandType = new TestCommandType(
            id: 5,
            name: "Default",
            description: "Default interface type",
            category: category,
            supportedTranslators: translators);

        // Assert
        commandType.CommandInterfaceType.ShouldBe(typeof(IGenericCommand));
    }

    [Fact]
    [Trait("Priority", "P0")]
    [Trait("Category", "CoreFramework")]
    public void ConstructorHandlesMaxBatchSizeZero()
    {
        // Arrange
        var category = new TestCommandCategory();
        var translators = new List<ITranslatorType>();

        // Act
        var commandType = new TestCommandType(
            id: 6,
            name: "ZeroBatch",
            description: "Zero batch size",
            category: category,
            supportedTranslators: translators,
            supportsBatching: false,
            supportsPipelining: false,
            maxBatchSize: 0);

        // Assert
        commandType.MaxBatchSize.ShouldBe(0);
    }

    [Fact]
    [Trait("Priority", "P0")]
    [Trait("Category", "CoreFramework")]
    public void ConstructorHandlesLargeMaxBatchSize()
    {
        // Arrange
        var category = new TestCommandCategory();
        var translators = new List<ITranslatorType>();

        // Act
        var commandType = new TestCommandType(
            id: 7,
            name: "LargeBatch",
            description: "Large batch size",
            category: category,
            supportedTranslators: translators,
            supportsBatching: true,
            supportsPipelining: true,
            maxBatchSize: 10000);

        // Assert
        commandType.MaxBatchSize.ShouldBe(10000);
    }

    [ExcludeFromCodeCoverage]
    private sealed class TestCommandType : CommandTypeBase
    {
        public TestCommandType(
            int id,
            string name,
            string description,
            IGenericCommandCategory category,
            IReadOnlyCollection<ITranslatorType> supportedTranslators,
            bool supportsBatching = false,
            bool supportsPipelining = false,
            int maxBatchSize = 1)
            : base(id, name, description, category, supportedTranslators, supportsBatching, supportsPipelining, maxBatchSize)
        {
        }
    }

    [ExcludeFromCodeCoverage]
    private sealed class TestCommandCategory : CommandCategoryBase
    {
        public TestCommandCategory()
            : base(1, "Test", false, false, false, false, 50)
        {
        }
    }

}
