using Fdw.Collections;
using Fdw.Collections.Attributes;
using System.Diagnostics.CodeAnalysis;

namespace Fdw.Services.Scheduling.Abstractions;

/// <summary>
/// Collection of scheduling command types.
/// Generated by TypeCollectionGenerator with high-performance lookups.
/// Provides unified access to all scheduling commands in the domain.
/// </summary>
[ExcludeFromCodeCoverage]
[TypeCollection(typeof(ISchedulingCommand), typeof(ISchedulingCommand), typeof(SchedulingCommands))]
public abstract partial class SchedulingCommands : TypeCollectionBase<ISchedulingCommand>
{
}