using System.Diagnostics.CodeAnalysis;
using Fdw.Collections;
using Fdw.Collections.Attributes;

namespace Fdw.Data.SchemaObjects.Abstractions;

/// <summary>
/// Collection of schema object types for UI rendering.
/// Generated by TypeCollectionGenerator with high-performance lookups.
/// </summary>
/// <remarks>
/// <para>
/// SchemaObjectTypes provides type metadata for database objects displayed in the UI.
/// Each type includes visual properties (icon, color, CSS class) for consistent rendering.
/// </para>
/// <para>
/// Usage in Blazor:
/// <code>
/// var objectType = SchemaObjectTypes.ByName("Table");
/// &lt;MudIcon Icon="@objectType.Icon" Color="@objectType.Color" /&gt;
/// </code>
/// </para>
/// </remarks>
[ExcludeFromCodeCoverage]
[TypeCollection(typeof(SchemaObjectTypeBase), typeof(ISchemaObjectType), typeof(SchemaObjectTypes))]
public abstract partial class SchemaObjectTypes : TypeCollectionBase<SchemaObjectTypeBase, ISchemaObjectType>
{
}
