using System.Diagnostics.CodeAnalysis;
using Fdw.Collections;
using Fdw.Services;
using Fdw.Services.Abstractions;
using Fdw.ServiceTypes;
using Fdw.Services.Credentials.Abstractions;
using Fdw.ServiceTypes.Logging;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Logging.Abstractions;
using System;
using System.Linq;
using Fdw.Results;
using Fdw.Services.Configuration;
using Fdw.Services.Data.Abstractions;
using Microsoft.Extensions.DependencyInjection.Extensions;
using Microsoft.Extensions.Hosting;

namespace Fdw.Services.Credentials;

/// <summary>
/// Collection of credential service types.
/// Generated by ServiceTypeCollectionGenerator with high-performance lookups.
/// </summary>
/// <remarks>
/// <para>
/// <c>RestrictToCurrentCompilation</c> is <c>true</c>: the credential domain default
/// (the SQL option) lives in a SIBLING assembly (<c>Fdw.Services.Credentials.Sql</c>),
/// not here. There is no same-assembly option, so this collection compiles with an empty option
/// set (generator emits the <c>NotFound</c> sentinel). The cross-assembly Sql option is registered
/// at the entry-point app via its Registration.SourceGenerators module initializer — package
/// reference IS the registration intent.
/// </para>
/// </remarks>
[ExcludeFromCodeCoverage]
[ServiceTypeCollection(
    typeof(CredentialServiceTypeBase<ICredentialService, ICredentialServiceFactory<ICredentialService, ICredentialServiceImplementationConfiguration>, ICredentialServiceImplementationConfiguration>),
    typeof(ICredentialServiceType),
    typeof(CredentialServiceTypes),
    ServiceInterface = typeof(ICredentialService),
    ProviderType = typeof(CredentialServiceProvider),
    ProviderInterface = typeof(ICredentialServiceProvider),
    ServiceCategory = "CredentialService",
    RestrictToCurrentCompilation = true)]
public partial class CredentialServiceTypes : ServiceTypeCollectionBase<
    CredentialServiceTypeBase<ICredentialService, ICredentialServiceFactory<ICredentialService, ICredentialServiceImplementationConfiguration>, ICredentialServiceImplementationConfiguration>,
    ICredentialServiceType<ICredentialService, ICredentialServiceFactory<ICredentialService, ICredentialServiceImplementationConfiguration>, ICredentialServiceImplementationConfiguration>>
{
    /// <summary>
    /// The connection this domain's configuration rows are read from and written to.
    /// </summary>
    public static string ConfigurationConnection { get; set; } = "PlatformConfiguration";

    // Configure(), Register() and Initialize() are source-generated

    /// <summary>
    /// Sets this collection's Register body: the option collect, then this domain's provider.
    /// </summary>
    /// <remarks>
    /// The provider is one registration for the whole collection and this declaration already names it,
    /// so the body that registers it is written here beside the declaration. Setting it as the phase's
    /// body is what makes it replaceable: an application calling <c>Registration(...)</c> replaces the
    /// collect and this registration together, which is the correct semantic for a host taking over phase 2.
    /// </remarks>
    static CredentialServiceTypes()
    {
        var collectOptions = RegisterFunc;

        var providerService = typeof(ICredentialServiceProvider).ToString();

        Registration((builder, loggerFactory) =>
        {
            var log = loggerFactory?.CreateLogger<CredentialServiceTypes>() ?? NullLogger<CredentialServiceTypes>.Instance;

            builder.Services.TryAddSingleton<ICredentialServiceConfigurationProvider>(sp =>
                new CredentialServiceConfigurationProvider(
                    sp.GetService<ILogger<CredentialServiceConfigurationProvider>>()!,
                    sp.GetRequiredService<IConfigurationGatewayProvider>(),
                    ConfigurationConnection));
            builder.Services.TryAddSingleton<CredentialServiceConfigurationProvider>(
                sp => (CredentialServiceConfigurationProvider)sp.GetRequiredService<ICredentialServiceConfigurationProvider>());

            builder.Services.TryAddSingleton<ImplementationConfigurationProviderBase<CredentialServiceConfiguration, CredentialServiceConfigurationCommand>>(
                sp => sp.GetRequiredService<CredentialServiceConfigurationProvider>());
            builder.Services.TryAddSingleton<IServiceConfigurationProvider<CredentialServiceConfiguration>>(
                sp => sp.GetRequiredService<CredentialServiceConfigurationProvider>());

            var registered = collectOptions(builder, loggerFactory);
            if (registered.IsFailure)
                return registered;

            var declaredOptions = Options;
            var optionNames = string.Join(", ", declaredOptions.Select(option => option.Name));

            ServiceTypeLog.DomainOptionsCollected(log, nameof(CredentialServiceTypes), declaredOptions.Length, optionNames);
            ServiceTypeLog.DomainProviderDeclared(log, nameof(CredentialServiceTypes), providerService);

            builder.Services.AddScoped<ICredentialServiceProvider>(sp =>
            {
                var provider = new CredentialServiceProvider(
                    sp,
                    sp.GetService<ILoggerFactory>()?.CreateLogger<CredentialServiceProvider>()
                    ?? NullLogger<CredentialServiceProvider>.Instance);

                var stLogger = sp.GetService<ILoggerFactory>()?.CreateLogger<CredentialServiceTypes>()
                    ?? NullLogger<CredentialServiceTypes>.Instance;
                ServiceTypeLog.DomainProviderConstructing(stLogger, nameof(CredentialServiceTypes), provider.GetType().Name);
                try
                {
                    if (sp.GetService<ICredentialServiceConfigurationProvider>() is { } cfgProvider)
                    {
                        var domainResult = provider.Register(cfgProvider);
                        if (domainResult.IsSuccess)
                            ServiceTypeLog.DomainConfigurationSourceAttached(stLogger, nameof(CredentialServiceTypes), provider.GetType().Name, cfgProvider.GetType().Name);
                        else
                            ServiceTypeLog.DomainConfigurationSourceRejected(stLogger, nameof(CredentialServiceTypes), provider.GetType().Name, cfgProvider.GetType().Name, domainResult.CurrentMessage);
                    }
                    else
                    {
                        ServiceTypeLog.DomainHasNoConfigurationSource(
                            stLogger,
                            nameof(CredentialServiceTypes),
                            provider.GetType().Name,
                            typeof(IServiceConfigurationProvider<CredentialServiceConfiguration>).ToString());
                    }
                }
                catch (Exception ex)
                {
                    ServiceTypeLog.FactoryRegistrationException(stLogger, ex, nameof(CredentialServiceTypes));
                    throw;
                }
                return provider;
            });

            if (declaredOptions.Length == 0)
                ServiceTypeLog.DomainRegisteredWithNoOptions(log, nameof(CredentialServiceTypes), providerService);
            else
                ServiceTypeLog.DomainRegistered(log, nameof(CredentialServiceTypes), declaredOptions.Length, optionNames, providerService);

            return GenericResult<IHostApplicationBuilder>.Success(builder);
        });
    }
}
