using System.Text;
using System.Linq;
using Fdw.Configuration.UI.SourceGenerators.Models;

namespace Fdw.Configuration.UI.SourceGenerators.Generators;

/// <summary>
/// Generates Blazor-specific components with RenderTreeBuilder.
/// </summary>
public sealed class BlazorComponentGenerator
{
    /// <summary>
    /// Generates Blazor component source code for the given configuration model.
    /// </summary>
    /// <param name="model">The configuration model to generate code for.</param>
    /// <returns>Generated C# source code.</returns>
    public static string Generate(ConfigurationModel model)
    {
        var builder = new StringBuilder();

        builder.AppendLine("// <auto-generated/>");
        builder.AppendLine("#nullable enable");
        builder.AppendLine();

        // Usings
        builder.AppendLine("using System;");
        builder.AppendLine("using System.Collections.Generic;");
        builder.AppendLine("using System.Threading.Tasks;");
        builder.AppendLine("using Microsoft.AspNetCore.Components;");
        builder.AppendLine("using Microsoft.AspNetCore.Components.Rendering;");
        builder.AppendLine("using Fdw.UI.Components;");
        builder.AppendLine("using Fdw.UI.Components.Primitives;");
        builder.AppendLine("using Fdw.UI.Abstractions;");
        builder.AppendLine();

        builder.AppendLine($"namespace {model.Namespace};");
        builder.AppendLine();

        // Class declaration
        builder.AppendLine("/// <summary>");
        builder.AppendLine($"/// Blazor component for {model.ClassName}.");
        builder.AppendLine("/// Renders using Blazor RenderTreeBuilder.");
        builder.AppendLine("/// Generated from [ManagedConfiguration] attribute.");
        builder.AppendLine("/// </summary>");
        builder.AppendLine($"public partial class {model.ClassName}Component");
        builder.AppendLine($"    : BlazorComponent<{model.ClassName}Component, {model.ClassName}>");
        builder.AppendLine("{");

        // Generate property components
        foreach (var property in model.Properties)
        {
            GeneratePropertyComponent(builder, property, model);
        }

        // GetPropertyComponents method
        GenerateGetPropertyComponents(builder, model);

        // CanContain method
        builder.AppendLine("    protected override bool CanContain<TChild>() => false;");
        builder.AppendLine();

        // BuildRenderTree method
        GenerateBuildRenderTree(builder, model);

        builder.AppendLine("}");

        return builder.ToString();
    }

    private static void GeneratePropertyComponent(StringBuilder builder, PropertyModel property, ConfigurationModel model)
    {
        builder.AppendLine($"    public sealed class {property.PropertyName}Property : BlazorPropertyComponent<{property.PropertyName}Property, {property.PropertyType}>");
        builder.AppendLine("    {");

        builder.AppendLine("        protected override void BuildRenderTree(RenderTreeBuilder builder)");
        builder.AppendLine("        {");

        var componentType = GetBlazorComponentType(property);
        builder.AppendLine($"            builder.OpenComponent<{componentType}>(0);");

        var sequence = 1;
        builder.AppendLine($"            builder.AddAttribute({sequence++}, nameof({componentType}.Value), Value);");
        builder.AppendLine($"            builder.AddAttribute({sequence++}, nameof({componentType}.ValueChanged),");
        builder.AppendLine($"                EventCallback.Factory.Create<{property.PropertyType}>(this, OnValueChanged));");

        if (property.Label != null)
            builder.AppendLine($"            builder.AddAttribute({sequence++}, nameof({componentType}.Label), \"{EscapeString(property.Label)}\");");

        if (property.HelpText != null)
            builder.AppendLine($"            builder.AddAttribute({sequence++}, nameof({componentType}.HelpText), \"{EscapeString(property.HelpText)}\");");

        if (property.IsRequired)
            builder.AppendLine($"            builder.AddAttribute({sequence++}, nameof({componentType}.Required), true);");

        // Add validation attributes
        foreach (var rule in property.ValidationRules)
        {
            var attributeName = GetBlazorAttributeName(rule.Key);
            if (attributeName != null)
            {
                builder.AppendLine($"            builder.AddAttribute({sequence++}, nameof({componentType}.{attributeName}), {FormatValue(rule.Value)});");
            }
        }

        builder.AppendLine($"            builder.AddAttribute({sequence++}, nameof({componentType}.ReadOnly), ReadOnly);");
        builder.AppendLine("            builder.CloseComponent();");

        builder.AppendLine("        }");

        builder.AppendLine("    }");
        builder.AppendLine();
    }

    private static void GenerateGetPropertyComponents(StringBuilder builder, ConfigurationModel model)
    {
        builder.AppendLine("    protected override IEnumerable<IPropertyComponent> GetPropertyComponents()");
        builder.AppendLine("    {");

        foreach (var property in model.Properties)
        {
            builder.AppendLine($"        yield return new {property.PropertyName}Property");
            builder.AppendLine("        {");
            builder.AppendLine($"            Value = Value?.{property.PropertyName},");
            builder.AppendLine("            ReadOnly = RenderMode?.Name == \"View\"");
            builder.AppendLine("        };");
            builder.AppendLine();
        }

        builder.AppendLine("    }");
        builder.AppendLine();
    }

    private static void GenerateBuildRenderTree(StringBuilder builder, ConfigurationModel model)
    {
        builder.AppendLine("    protected override void BuildRenderTree(RenderTreeBuilder builder)");
        builder.AppendLine("    {");
        builder.AppendLine("        int sequence = 0;");
        builder.AppendLine();
        builder.AppendLine("        builder.OpenElement(sequence++, \"div\");");
        builder.AppendLine("        builder.AddAttribute(sequence++, \"class\", GetCssClass());");
        builder.AppendLine();

        foreach (var property in model.Properties)
        {
            builder.AppendLine($"        // Render {property.PropertyName}");
            builder.AppendLine($"        builder.OpenComponent<{property.PropertyName}Property>(sequence++);");
            builder.AppendLine($"        builder.AddComponentParameter(sequence++, nameof({property.PropertyName}Property.Value), Value?.{property.PropertyName});");
            builder.AppendLine($"        builder.AddComponentParameter(sequence++, nameof({property.PropertyName}Property.ValueChanged),");
            builder.AppendLine($"            EventCallback.Factory.Create<{property.PropertyType}>(this, newValue =>");
            builder.AppendLine("            {");
            builder.AppendLine("                if (Value != null)");
            builder.AppendLine("                {");
            builder.AppendLine($"                    Value.{property.PropertyName} = newValue;");
            builder.AppendLine("                    StateHasChanged();");
            builder.AppendLine("                }");
            builder.AppendLine("            }));");
            builder.AppendLine("        builder.CloseComponent();");
            builder.AppendLine();
        }

        builder.AppendLine("        builder.CloseElement();");
        builder.AppendLine("    }");
    }

    private static string GetBlazorComponentType(PropertyModel property)
    {
        if (property.IsTypeCollectionReference && property.TypeCollectionName != null && property.TypeOptionInterfaceName != null)
        {
            return $"TypeCollectionDropdown<{property.TypeCollectionName}, {property.TypeOptionInterfaceName}>";
        }

#pragma warning disable FDW018
        return property.ComponentType switch
        {
            ComponentTypeMapping.TextInput => $"TextInput<{property.PropertyType}>",
            ComponentTypeMapping.NumericInput => $"NumericInput<{property.PropertyType}>",
            ComponentTypeMapping.Switch => "Switch",
            ComponentTypeMapping.DateTimePicker => "DateTimePicker",
            ComponentTypeMapping.TextArea => "TextArea",
            ComponentTypeMapping.Dropdown => $"Dropdown<{property.PropertyType}>",
            ComponentTypeMapping.Collection => $"ConfigurationCollection<{property.CollectionItemType}, {property.CollectionItemType}Component>",
            _ => $"TextInput<{property.PropertyType}>"
        };
#pragma warning restore FDW018
    }

    private static string? GetBlazorAttributeName(string ruleName)
    {
        return ruleName switch
        {
            "maxLength" => "MaxLength",
            "minLength" => "MinLength",
            "min" => "Min",
            "max" => "Max",
            "pattern" => "Pattern",
            _ => null
        };
    }

    private static string FormatValue(object value)
    {
        return value switch
        {
            string s => $"\"{EscapeString(s)}\"",
            _ => value.ToString() ?? "null"
        };
    }

    private static string EscapeString(string input)
    {
        return input.Replace("\\", "\\\\").Replace("\"", "\\\"");
    }
}
