using System;
using System.Globalization;
using System.Linq;
using System.Text;
using Fdw.Configuration.UI.SourceGenerators.Models;

namespace Fdw.Configuration.UI.SourceGenerators.Generators;

/// <summary>
/// Generates ConfigurationFormModel derived classes for [ManagedConfiguration] classes.
/// Creates strongly-typed UI models that can be rendered by any IUIRenderer implementation.
/// </summary>
public static class ConfigurationFormModelGenerator
{
    /// <summary>
    /// Generates ConfigurationFormModel source code for the given configuration model.
    /// </summary>
    /// <param name="model">The configuration model to generate code for.</param>
    /// <returns>Generated C# source code.</returns>
    public static string Generate(ConfigurationModel model)
    {
        var builder = new StringBuilder();

        builder.AppendLine("// <auto-generated/>");
        builder.AppendLine("#nullable enable");
        builder.AppendLine();

        // Usings
        builder.AppendLine("using System;");
        builder.AppendLine("using System.Collections.Generic;");
        builder.AppendLine("using Fdw.UI.Abstractions.Components;");
        builder.AppendLine("using Fdw.UI.Abstractions.Pages;");
        builder.AppendLine("using Fdw.UI.Components.Configuration;");
        builder.AppendLine("using Fdw.UI.Components.Models;");
        builder.AppendLine("using Fdw.UI.Components.TypeIntegration;");
        builder.AppendLine();

        builder.AppendLine($"namespace {model.Namespace};");
        builder.AppendLine();

        // Class declaration
        builder.AppendLine("/// <summary>");
        builder.AppendLine($"/// UI form model for {model.ClassName}.");
        builder.AppendLine("/// Provides strongly-typed component models for each configuration property.");
        builder.AppendLine("/// Generated from [ManagedConfiguration] attribute.");
        builder.AppendLine("/// </summary>");
        builder.AppendLine($"public sealed partial class {model.ClassName}FormModel");
        builder.AppendLine($"    : ConfigurationFormModel<{model.ClassName}>");
        builder.AppendLine("{");

        // Component model properties
        GenerateComponentProperties(builder, model);

        // Constructor
        GenerateConstructor(builder, model);

        // ToConfiguration method
        GenerateToConfigurationMethod(builder, model);

        // ToPageModel method
        GenerateToPageModelMethod(builder, model);

        // Validate method
        GenerateValidateMethod(builder, model);

        // Reset method
        GenerateResetMethod(builder, model);

        // Static factory method
        GenerateFactoryMethod(builder, model);

        builder.AppendLine("}");

        return builder.ToString();
    }

    private static void GenerateComponentProperties(StringBuilder builder, ConfigurationModel model)
    {
        builder.AppendLine("    #region Component Properties");
        builder.AppendLine();

        foreach (var property in model.Properties)
        {
            var componentType = GetComponentModelType(property);
            builder.AppendLine($"    /// <summary>");
            builder.AppendLine($"    /// Gets the UI component for {property.Label ?? property.PropertyName}.");
            builder.AppendLine($"    /// </summary>");
            builder.AppendLine($"    public {componentType} {property.PropertyName}Component {{ get; }}");
            builder.AppendLine();
        }

        builder.AppendLine("    #endregion");
        builder.AppendLine();
    }

    private static void GenerateConstructor(StringBuilder builder, ConfigurationModel model)
    {
        builder.AppendLine($"    /// <summary>");
        builder.AppendLine($"    /// Initializes a new instance of the <see cref=\"{model.ClassName}FormModel\"/> class.");
        builder.AppendLine($"    /// </summary>");
        builder.AppendLine($"    /// <param name=\"configuration\">The configuration instance to edit.</param>");
        builder.AppendLine($"    public {model.ClassName}FormModel({model.ClassName} configuration)");
        builder.AppendLine("        : base(configuration)");
        builder.AppendLine("    {");

        foreach (var property in model.Properties)
        {
            GenerateComponentInitialization(builder, property, model);
        }

        builder.AppendLine("    }");
        builder.AppendLine();
    }

    // MA0051: Method length acceptable - procedural code generation with switch on component types
#pragma warning disable MA0051 // Method is too long
    private static void GenerateComponentInitialization(StringBuilder builder, PropertyModel property, ConfigurationModel model)
#pragma warning restore MA0051
    {
        var label = EscapeString(property.Label ?? property.PropertyName);
        var helpText = property.HelpText != null ? $"\"{EscapeString(property.HelpText)}\"" : "null";

        if (property.IsTypeCollectionReference && property.TypeCollectionName != null)
        {
            builder.AppendLine($"        {property.PropertyName}Component = new TypeCollectionSelectModel");
            builder.AppendLine("        {");
            builder.AppendLine($"            Id = \"{property.PropertyName}\",");
            builder.AppendLine($"            Label = \"{label}\",");
            builder.AppendLine($"            HelpText = {helpText},");
            builder.AppendLine($"            IsRequired = {(property.IsRequired ? "true" : "false")},");
            builder.AppendLine($"            IsReadOnly = {(property.IsReadOnly ? "true" : "false")},");
            builder.AppendLine($"            Order = {property.Order},");
            builder.AppendLine($"            TypeCollectionName = \"{property.TypeCollectionName}\",");
            builder.AppendLine($"            Value = configuration.{property.PropertyName}");
            builder.AppendLine("        };");
            builder.AppendLine($"        // Load TypeCollection options: {property.PropertyName}Component.LoadOptions({property.TypeCollectionName}.Instance.All().Select(t => (t.Id, t.Name)));");
        }
        else if (property.IsCollection && property.CollectionItemType != null)
        {
            builder.AppendLine($"        {property.PropertyName}Component = new CollectionModel<{property.CollectionItemType}>");
            builder.AppendLine("        {");
            builder.AppendLine($"            Id = \"{property.PropertyName}\",");
            builder.AppendLine($"            Label = \"{label}\",");
            builder.AppendLine($"            HelpText = {helpText},");
            builder.AppendLine($"            IsRequired = {(property.IsRequired ? "true" : "false")},");
            builder.AppendLine($"            IsReadOnly = {(property.IsReadOnly ? "true" : "false")},");
            builder.AppendLine($"            Order = {property.Order}");
            builder.AppendLine("        };");
            builder.AppendLine($"        {property.PropertyName}Component.SetItems(configuration.{property.PropertyName} ?? new List<{property.CollectionItemType}>());");
        }
        else
        {
#pragma warning disable FDW018
            switch (property.ComponentType)
            {
                case ComponentTypeMapping.Switch:
                    builder.AppendLine($"        {property.PropertyName}Component = new CheckboxModel");
                    builder.AppendLine("        {");
                    builder.AppendLine($"            Id = \"{property.PropertyName}\",");
                    builder.AppendLine($"            Label = \"{label}\",");
                    builder.AppendLine($"            HelpText = {helpText},");
                    builder.AppendLine($"            IsRequired = {(property.IsRequired ? "true" : "false")},");
                    builder.AppendLine($"            IsReadOnly = {(property.IsReadOnly ? "true" : "false")},");
                    builder.AppendLine($"            Order = {property.Order},");
                    builder.AppendLine($"            Value = configuration.{property.PropertyName}");
                    builder.AppendLine("        };");
                    break;

                case ComponentTypeMapping.NumericInput:
                    var numericType = property.PropertyType;
                    builder.AppendLine($"        {property.PropertyName}Component = new NumericInputModel<{numericType}>");
                    builder.AppendLine("        {");
                    builder.AppendLine($"            Id = \"{property.PropertyName}\",");
                    builder.AppendLine($"            Label = \"{label}\",");
                    builder.AppendLine($"            HelpText = {helpText},");
                    builder.AppendLine($"            IsRequired = {(property.IsRequired ? "true" : "false")},");
                    builder.AppendLine($"            IsReadOnly = {(property.IsReadOnly ? "true" : "false")},");
                    builder.AppendLine($"            Order = {property.Order},");
                    builder.AppendLine($"            Value = configuration.{property.PropertyName}");
                    if (property.ValidationRules.TryGetValue("min", out var min))
                    {
                        builder.AppendLine($"            , MinValue = ({numericType}){min}");
                    }
                    if (property.ValidationRules.TryGetValue("max", out var max))
                    {
                        builder.AppendLine($"            , MaxValue = ({numericType}){max}");
                    }
                    builder.AppendLine("        };");
                    break;

                case ComponentTypeMapping.DateTimePicker:
                    builder.AppendLine($"        {property.PropertyName}Component = new DatePickerModel");
                    builder.AppendLine("        {");
                    builder.AppendLine($"            Id = \"{property.PropertyName}\",");
                    builder.AppendLine($"            Label = \"{label}\",");
                    builder.AppendLine($"            HelpText = {helpText},");
                    builder.AppendLine($"            IsRequired = {(property.IsRequired ? "true" : "false")},");
                    builder.AppendLine($"            IsReadOnly = {(property.IsReadOnly ? "true" : "false")},");
                    builder.AppendLine($"            Order = {property.Order},");
                    builder.AppendLine($"            Value = configuration.{property.PropertyName}");
                    builder.AppendLine("        };");
                    break;

                case ComponentTypeMapping.TextArea:
                    builder.AppendLine($"        {property.PropertyName}Component = new TextInputModel");
                    builder.AppendLine("        {");
                    builder.AppendLine($"            Id = \"{property.PropertyName}\",");
                    builder.AppendLine($"            Label = \"{label}\",");
                    builder.AppendLine($"            HelpText = {helpText},");
                    builder.AppendLine($"            IsRequired = {(property.IsRequired ? "true" : "false")},");
                    builder.AppendLine($"            IsReadOnly = {(property.IsReadOnly ? "true" : "false")},");
                    builder.AppendLine($"            Order = {property.Order},");
                    builder.AppendLine($"            IsMultiline = true,");
                    builder.AppendLine($"            Value = configuration.{property.PropertyName}");
                    AppendTextValidationRules(builder, property);
                    builder.AppendLine("        };");
                    break;

                default: // TextInput
                    builder.AppendLine($"        {property.PropertyName}Component = new TextInputModel");
                    builder.AppendLine("        {");
                    builder.AppendLine($"            Id = \"{property.PropertyName}\",");
                    builder.AppendLine($"            Label = \"{label}\",");
                    builder.AppendLine($"            HelpText = {helpText},");
                    builder.AppendLine($"            IsRequired = {(property.IsRequired ? "true" : "false")},");
                    builder.AppendLine($"            IsReadOnly = {(property.IsReadOnly ? "true" : "false")},");
                    builder.AppendLine($"            Order = {property.Order},");
                    builder.AppendLine($"            Value = configuration.{property.PropertyName}");
                    AppendTextValidationRules(builder, property);
                    builder.AppendLine("        };");
                    break;
            }
#pragma warning restore FDW018
        }

        builder.AppendLine();
    }

    private static void AppendTextValidationRules(StringBuilder builder, PropertyModel property)
    {
        if (property.ValidationRules.TryGetValue("maxLength", out var maxLength))
        {
            builder.AppendLine($"            , MaxLength = {maxLength}");
        }
        if (property.ValidationRules.TryGetValue("minLength", out var minLength))
        {
            builder.AppendLine($"            , MinLength = {minLength}");
        }
        if (property.ValidationRules.TryGetValue("pattern", out var pattern))
        {
            builder.AppendLine($"            , Pattern = \"{EscapeString(pattern?.ToString() ?? "")}\"");
        }
    }

    private static void GenerateToConfigurationMethod(StringBuilder builder, ConfigurationModel model)
    {
        builder.AppendLine("    /// <inheritdoc />");
        builder.AppendLine($"    public override {model.ClassName} ToConfiguration()");
        builder.AppendLine("    {");
        builder.AppendLine($"        var config = new {model.ClassName}();");
        builder.AppendLine();

        foreach (var property in model.Properties)
        {
            GeneratePropertyAssignment(builder, property);
        }

        builder.AppendLine();
        builder.AppendLine("        return config;");
        builder.AppendLine("    }");
        builder.AppendLine();
    }

    private static void GeneratePropertyAssignment(StringBuilder builder, PropertyModel property)
    {
        if (property.IsTypeCollectionReference)
        {
            builder.AppendLine($"        config.{property.PropertyName} = {property.PropertyName}Component.Value ?? 0;");
        }
        else if (property.IsCollection && property.CollectionItemType != null)
        {
            builder.AppendLine($"        config.{property.PropertyName} = new List<{property.CollectionItemType}>({property.PropertyName}Component.Items);");
        }
        else
        {
#pragma warning disable FDW018
            switch (property.ComponentType)
            {
                case ComponentTypeMapping.Switch:
                    builder.AppendLine($"        config.{property.PropertyName} = {property.PropertyName}Component.Value ?? false;");
                    break;

                case ComponentTypeMapping.NumericInput:
                    builder.AppendLine($"        config.{property.PropertyName} = {property.PropertyName}Component.Value ?? default;");
                    break;

                case ComponentTypeMapping.DateTimePicker:
                    builder.AppendLine($"        config.{property.PropertyName} = {property.PropertyName}Component.Value ?? default;");
                    break;

                default:
                    builder.AppendLine($"        config.{property.PropertyName} = {property.PropertyName}Component.Value ?? \"\";");
                    break;
            }
#pragma warning restore FDW018
        }
    }

    private static void GenerateToPageModelMethod(StringBuilder builder, ConfigurationModel model)
    {
        // Group properties by their Group attribute
        var groups = model.Properties
            .GroupBy(p => p.Group ?? "General", StringComparer.Ordinal)
            .OrderBy(g => g.Key, StringComparer.Ordinal)
            .ToList();

        builder.AppendLine("    /// <inheritdoc />");
        builder.AppendLine("    public override IPageModel ToPageModel(IPageMode mode)");
        builder.AppendLine("    {");
        builder.AppendLine("        var page = new PageModel");
        builder.AppendLine("        {");
        builder.AppendLine($"            Id = \"{model.ClassName}\",");
        builder.AppendLine("            Mode = mode,");
        builder.AppendLine($"            Title = \"{SplitCamelCase(model.ClassName)}\",");
        builder.AppendLine($"            Description = \"Configure {SplitCamelCase(model.ClassName)} settings\"");
        builder.AppendLine("        };");
        builder.AppendLine();

        foreach (var group in groups)
        {
            builder.AppendLine($"        // Section: {group.Key}");
            builder.AppendLine($"        var section{SanitizeIdentifier(group.Key)} = new SectionModel");
            builder.AppendLine("        {");
            builder.AppendLine($"            Id = \"{SanitizeIdentifier(group.Key)}\",");
            builder.AppendLine($"            Title = \"{group.Key}\",");
            builder.AppendLine("            IsCollapsible = true,");
            builder.AppendLine("            IsExpanded = true");
            builder.AppendLine("        };");

            // Create single column for simplicity
            builder.AppendLine($"        var column{SanitizeIdentifier(group.Key)} = new ColumnModel {{ Id = \"{SanitizeIdentifier(group.Key)}Col\", Width = 12 }};");

            foreach (var property in group.OrderBy(p => p.Order))
            {
                builder.AppendLine($"        column{SanitizeIdentifier(group.Key)}.AddComponent({property.PropertyName}Component);");
            }

            builder.AppendLine($"        section{SanitizeIdentifier(group.Key)}.AddColumn(column{SanitizeIdentifier(group.Key)});");
            builder.AppendLine($"        page.AddSection(section{SanitizeIdentifier(group.Key)});");
            builder.AppendLine();
        }

        builder.AppendLine("        return page;");
        builder.AppendLine("    }");
        builder.AppendLine();
    }

    private static void GenerateValidateMethod(StringBuilder builder, ConfigurationModel model)
    {
        builder.AppendLine("    /// <inheritdoc />");
        builder.AppendLine("    public override ValidationResult Validate()");
        builder.AppendLine("    {");
        builder.AppendLine("        var messages = new List<ValidationMessage>();");
        builder.AppendLine();

        foreach (var property in model.Properties)
        {
            builder.AppendLine($"        var {property.PropertyName.ToLower(CultureInfo.InvariantCulture)}Result = {property.PropertyName}Component.Validate();");
            builder.AppendLine($"        if (!{property.PropertyName.ToLower(CultureInfo.InvariantCulture)}Result.IsValid)");
            builder.AppendLine("        {");
            builder.AppendLine($"            messages.AddRange({property.PropertyName.ToLower(CultureInfo.InvariantCulture)}Result.Messages);");
            builder.AppendLine("        }");
            builder.AppendLine();
        }

        builder.AppendLine("        return messages.Count == 0");
        builder.AppendLine("            ? ValidationResult.Success()");
        builder.AppendLine("            : ValidationResult.FromMessages(messages);");
        builder.AppendLine("    }");
        builder.AppendLine();
    }

    private static void GenerateResetMethod(StringBuilder builder, ConfigurationModel model)
    {
        builder.AppendLine("    /// <inheritdoc />");
        builder.AppendLine("    public override void Reset()");
        builder.AppendLine("    {");

        foreach (var property in model.Properties)
        {
            if (property.IsTypeCollectionReference)
            {
                builder.AppendLine($"        {property.PropertyName}Component.Value = Configuration.{property.PropertyName};");
            }
            else if (property.IsCollection)
            {
                builder.AppendLine($"        {property.PropertyName}Component.SetItems(Configuration.{property.PropertyName} ?? new List<{property.CollectionItemType}>());");
            }
            else
            {
#pragma warning disable FDW018
                switch (property.ComponentType)
                {
                    case ComponentTypeMapping.Switch:
                        builder.AppendLine($"        {property.PropertyName}Component.Value = Configuration.{property.PropertyName};");
                        break;

                    case ComponentTypeMapping.NumericInput:
                    case ComponentTypeMapping.DateTimePicker:
                        builder.AppendLine($"        {property.PropertyName}Component.Value = Configuration.{property.PropertyName};");
                        break;

                    default:
                        builder.AppendLine($"        {property.PropertyName}Component.Value = Configuration.{property.PropertyName};");
                        break;
                }
#pragma warning restore FDW018
            }
        }

        builder.AppendLine("        HasChanges = false;");
        builder.AppendLine("    }");
        builder.AppendLine();
    }

    private static void GenerateFactoryMethod(StringBuilder builder, ConfigurationModel model)
    {
        builder.AppendLine($"    /// <summary>");
        builder.AppendLine($"    /// Creates a new form model for a new configuration instance.");
        builder.AppendLine($"    /// </summary>");
        builder.AppendLine($"    /// <returns>A new form model instance.</returns>");
        builder.AppendLine($"    public static {model.ClassName}FormModel CreateNew()");
        builder.AppendLine("    {");
        builder.AppendLine($"        return new {model.ClassName}FormModel(new {model.ClassName}());");
        builder.AppendLine("    }");
    }

    private static string GetComponentModelType(PropertyModel property)
    {
        if (property.IsTypeCollectionReference)
        {
            return "TypeCollectionSelectModel";
        }

        if (property.IsCollection && property.CollectionItemType != null)
        {
            return $"CollectionModel<{property.CollectionItemType}>";
        }

#pragma warning disable FDW018
        return property.ComponentType switch
        {
            ComponentTypeMapping.Switch => "CheckboxModel",
            ComponentTypeMapping.NumericInput => $"NumericInputModel<{property.PropertyType}>",
            ComponentTypeMapping.DateTimePicker => "DatePickerModel",
            ComponentTypeMapping.Dropdown => $"SelectModel<{property.PropertyType}>",
            ComponentTypeMapping.Collection => $"CollectionModel<{property.CollectionItemType ?? "object"}>",
            _ => "TextInputModel"
        };
#pragma warning restore FDW018
    }

    private static string EscapeString(string input)
    {
        return input.Replace("\\", "\\\\").Replace("\"", "\\\"");
    }

    private static string SplitCamelCase(string input)
    {
        return string.Concat(input.Select((x, i) => i > 0 && char.IsUpper(x) ? " " + x : x.ToString()));
    }

    private static string SanitizeIdentifier(string input)
    {
        return new string(input.Where(c => char.IsLetterOrDigit(c)).ToArray());
    }
}
