using System;
using System.Globalization;
using System.Text;
using System.Linq;
using Fdw.Configuration.UI.SourceGenerators.Models;

namespace Fdw.Configuration.UI.SourceGenerators.Generators;

/// <summary>
/// Generates Terminal UI components with Spectre.Console.
/// </summary>
public sealed class TUIComponentGenerator
{
    /// <summary>
    /// Generates TUI component source code for the given configuration model.
    /// </summary>
    /// <param name="model">The configuration model to generate code for.</param>
    /// <returns>Generated C# source code.</returns>
    public static string Generate(ConfigurationModel model)
    {
        var builder = new StringBuilder();

        builder.AppendLine("// <auto-generated/>");
        builder.AppendLine("#nullable enable");
        builder.AppendLine();

        // Usings
        builder.AppendLine("using System;");
        builder.AppendLine("using System.Collections.Generic;");
        builder.AppendLine("using System.Threading.Tasks;");
        builder.AppendLine("using Spectre.Console;");
        builder.AppendLine("using Fdw.UI.Components.TUI;");
        builder.AppendLine("using Fdw.UI.Components.TUI.Prompts;");
        builder.AppendLine("using Fdw.UI.Abstractions;");
        builder.AppendLine();

        builder.AppendLine($"namespace {model.Namespace};");
        builder.AppendLine();

        // Class declaration
        builder.AppendLine("/// <summary>");
        builder.AppendLine($"/// Terminal UI component for {model.ClassName}.");
        builder.AppendLine("/// Renders using Spectre.Console.");
        builder.AppendLine("/// Generated from [ManagedConfiguration] attribute.");
        builder.AppendLine("/// </summary>");
        builder.AppendLine($"public partial class {model.ClassName}TUIComponent");
        builder.AppendLine($"    : TUIComponent<{model.ClassName}TUIComponent, {model.ClassName}>");
        builder.AppendLine("{");

        // GetPropertyComponents method
        builder.AppendLine("    protected override IEnumerable<IPropertyComponent> GetPropertyComponents()");
        builder.AppendLine("    {");
        builder.AppendLine("        yield break; // TUI doesn't use property components directly");
        builder.AppendLine("    }");
        builder.AppendLine();

        // CanContain method
        builder.AppendLine("    protected override bool CanContain<TChild>() => false;");
        builder.AppendLine();

        // Prompt method
        GeneratePromptMethod(builder, model);

        // Render method
        GenerateRenderMethod(builder, model);

        builder.AppendLine("}");

        return builder.ToString();
    }

    private static void GeneratePromptMethod(StringBuilder builder, ConfigurationModel model)
    {
        builder.AppendLine($"    public override async Task<{model.ClassName}?> Prompt(IAnsiConsole console)");
        builder.AppendLine("    {");
        builder.AppendLine($"        var config = Value ?? new {model.ClassName}();");
        builder.AppendLine();
        builder.AppendLine($"        RenderHeader(console, \"{SplitCamelCase(model.ClassName)}\");");
        builder.AppendLine();

        foreach (var property in model.Properties)
        {
            GeneratePropertyPrompt(builder, property, model);
            builder.AppendLine();
        }

        builder.AppendLine("        return config;");
        builder.AppendLine("    }");
        builder.AppendLine();
    }

    // MA0051: Method length acceptable - procedural code generation with switch on component types
#pragma warning disable MA0051 // Method is too long
    private static void GeneratePropertyPrompt(StringBuilder builder, PropertyModel property, ConfigurationModel model)
#pragma warning restore MA0051
    {
        if (property.HelpText != null)
        {
            builder.AppendLine($"        console.MarkupLine(\"[dim]{EscapeMarkup(property.HelpText)}[/]\");");
        }

        var label = property.Label ?? property.PropertyName;
        var promptHelper = GetTUIPromptHelper(property);

        if (property.IsTypeCollectionReference && property.TypeCollectionName != null && property.TypeOptionInterfaceName != null)
        {
            builder.AppendLine($"        config.{property.PropertyName} = PromptTypeCollectionId<{property.TypeCollectionName}, {property.TypeOptionInterfaceName}>(");
            builder.AppendLine($"            console,");
            builder.AppendLine($"            \"{label}:\",");
            builder.AppendLine($"            config.{property.PropertyName});");
        }
        else
        {
#pragma warning disable FDW018
            switch (property.ComponentType)
            {
                case ComponentTypeMapping.Switch:
                    builder.AppendLine($"        config.{property.PropertyName} = ConfirmationPromptHelper.Prompt(");
                    builder.AppendLine($"            console,");
                    builder.AppendLine($"            \"{label}?\",");
                    builder.AppendLine($"            config.{property.PropertyName},");
                    builder.AppendLine($"            Theme);");
                    break;

                case ComponentTypeMapping.NumericInput:
                    builder.AppendLine($"        config.{property.PropertyName} = NumericPromptHelper.Prompt<{property.PropertyType}>(");
                    builder.AppendLine($"            console,");
                    builder.AppendLine($"            \"{label}:\",");
                    builder.AppendLine($"            config.{property.PropertyName},");
                    GenerateValidationMetadata(builder, property);
                    builder.AppendLine($"            Theme);");
                    break;

                case ComponentTypeMapping.DateTimePicker:
                    builder.AppendLine($"        config.{property.PropertyName} = DateTimePromptHelper.Prompt(");
                    builder.AppendLine($"            console,");
                    builder.AppendLine($"            \"{label}:\",");
                    builder.AppendLine($"            config.{property.PropertyName},");
                    builder.AppendLine($"            Theme);");
                    break;

                case ComponentTypeMapping.Collection:
                    builder.AppendLine($"        config.{property.PropertyName} = CollectionPromptHelper.Prompt<{property.CollectionItemType}>(");
                    builder.AppendLine($"            console,");
                    builder.AppendLine($"            \"{label}\",");
                    builder.AppendLine($"            config.{property.PropertyName},");
                    builder.AppendLine($"            Theme);");
                    break;

                default: // TextInput, TextArea
                    builder.AppendLine($"        config.{property.PropertyName} = TextPromptHelper.Prompt(");
                    builder.AppendLine($"            console,");
                    builder.AppendLine($"            \"{label}:\",");
                    builder.AppendLine($"            config.{property.PropertyName},");
                    GenerateValidationMetadata(builder, property);
                    builder.AppendLine($"            Theme);");
                    break;
            }
#pragma warning restore FDW018
        }
    }

    private static void GenerateValidationMetadata(StringBuilder builder, PropertyModel property)
    {
        if (property.IsRequired || property.ValidationRules.Count > 0)
        {
            builder.AppendLine("            new PropertyMetadata");
            builder.AppendLine("            {");
            if (property.IsRequired)
                builder.AppendLine("                Required = true,");

            if (property.ValidationRules.Count > 0)
            {
                builder.AppendLine("                ValidationRules = new Dictionary<string, object>");
                builder.AppendLine("                {");
                foreach (var rule in property.ValidationRules)
                {
                    builder.AppendLine($"                    [\"{rule.Key}\"] = {FormatValue(rule.Value)},");
                }
                builder.AppendLine("                }");
            }
            builder.AppendLine("            },");
        }
        else
        {
            builder.AppendLine("            null,");
        }
    }

    private static void GenerateRenderMethod(StringBuilder builder, ConfigurationModel model)
    {
        builder.AppendLine("    public override void Render(IAnsiConsole console)");
        builder.AppendLine("    {");
        builder.AppendLine("        if (Value == null)");
        builder.AppendLine("        {");
        builder.AppendLine("            console.MarkupLine(\"[dim]No configuration data[/]\");");
        builder.AppendLine("            return;");
        builder.AppendLine("        }");
        builder.AppendLine();

        builder.AppendLine("        var border = Theme?.TableBorder ?? TableBorder.Rounded;");
        builder.AppendLine("        var borderColor = Theme?.PrimaryColor ?? Color.Blue;");
        builder.AppendLine();

        builder.AppendLine("        var table = new Table()");
        builder.AppendLine("            .Border(border)");
        builder.AppendLine("            .BorderColor(borderColor)");
        builder.AppendLine("            .AddColumn(\"[bold]Property[/]\")");
        builder.AppendLine("            .AddColumn(\"[bold]Value[/]\");");
        builder.AppendLine();

        foreach (var property in model.Properties)
        {
            var label = property.Label ?? property.PropertyName;
            GenerateTableRow(builder, property, label);
        }

        builder.AppendLine();
        builder.AppendLine("        console.Write(table);");
        builder.AppendLine("    }");
    }

    private static void GenerateTableRow(StringBuilder builder, PropertyModel property, string label)
    {
        if (property.IsTypeCollectionReference && property.TypeCollectionName != null)
        {
            builder.AppendLine($"        var {property.PropertyName.ToLower(CultureInfo.InvariantCulture)}Type = {property.TypeCollectionName}.ById(Value.{property.PropertyName});");
            builder.AppendLine($"        table.AddRow(\"{label}\", {property.PropertyName.ToLower(CultureInfo.InvariantCulture)}Type?.Name ?? \"[dim]None[/]\");");
        }
        else if (string.Equals(property.ComponentType.ToString(), "Switch", StringComparison.Ordinal))
        {
            builder.AppendLine($"        table.AddRow(\"{label}\", Value.{property.PropertyName} ? \"[{{Theme?.SuccessColor ?? Color.Green}}]Yes[/]\" : \"[{{Theme?.ErrorColor ?? Color.Red}}]No[/]\");");
        }
        else if (string.Equals(property.PropertyType, "string", StringComparison.Ordinal))
        {
            builder.AppendLine($"        table.AddRow(\"{label}\", Markup.Escape(Value.{property.PropertyName} ?? \"\"));");
        }
        else
        {
            builder.AppendLine($"        table.AddRow(\"{label}\", Value.{property.PropertyName}.ToString() ?? \"\");");
        }
    }

    private static string GetTUIPromptHelper(PropertyModel property)
    {
#pragma warning disable FDW018
        return property.ComponentType switch
        {
            ComponentTypeMapping.NumericInput => "NumericPromptHelper",
            ComponentTypeMapping.Switch => "ConfirmationPromptHelper",
            ComponentTypeMapping.DateTimePicker => "DateTimePromptHelper",
            ComponentTypeMapping.Collection => "CollectionPromptHelper",
            _ => "TextPromptHelper"
        };
#pragma warning restore FDW018
    }

    private static string FormatValue(object value)
    {
        return value switch
        {
            string s => $"\"{EscapeString(s)}\"",
            _ => value.ToString() ?? "null"
        };
    }

    private static string EscapeString(string input)
    {
        return input.Replace("\\", "\\\\").Replace("\"", "\\\"");
    }

    private static string EscapeMarkup(string input)
    {
        return input.Replace("[", "[[").Replace("]", "]]");
    }

    private static string SplitCamelCase(string input)
    {
        return string.Concat(input.Select((x, i) => i > 0 && char.IsUpper(x) ? " " + x : x.ToString()));
    }
}
