using System.Text;
using System.Linq;
using Fdw.Configuration.UI.SourceGenerators.Models;

namespace Fdw.Configuration.UI.SourceGenerators.Generators;

/// <summary>
/// Generates framework-agnostic web components with metadata.
/// </summary>
public sealed class WebComponentGenerator
{
    /// <summary>
    /// Generates web component source code for the given configuration model.
    /// </summary>
    /// <param name="model">The configuration model to generate code for.</param>
    /// <returns>Generated C# source code.</returns>
    public static string Generate(ConfigurationModel model)
    {
        var builder = new StringBuilder();

        builder.AppendLine("// <auto-generated/>");
        builder.AppendLine("#nullable enable");
        builder.AppendLine();

        // Usings
        builder.AppendLine("using System;");
        builder.AppendLine("using System.Collections.Generic;");
        builder.AppendLine("using System.Linq;");
        builder.AppendLine("using Fdw.UI.Web.Abstractions;");
        builder.AppendLine("using Fdw.UI.Abstractions;");
        builder.AppendLine();

        builder.AppendLine($"namespace {model.Namespace};");
        builder.AppendLine();

        // Class declaration
        builder.AppendLine("/// <summary>");
        builder.AppendLine($"/// Web component for {model.ClassName}.");
        builder.AppendLine("/// Framework-agnostic with JSON-serializable metadata.");
        builder.AppendLine("/// Generated from [ManagedConfiguration] attribute.");
        builder.AppendLine("/// </summary>");
        builder.AppendLine($"public partial class {model.ClassName}WebComponent");
        builder.AppendLine($"    : WebComponentBase<{model.ClassName}WebComponent, {model.ClassName}>");
        builder.AppendLine("{");

        // Generate property components
        foreach (var property in model.Properties)
        {
            GeneratePropertyComponent(builder, property, model);
        }

        // GetPropertyComponents method
        GenerateGetPropertyComponents(builder, model);

        // CanContain method
        builder.AppendLine("    protected override bool CanContain<TChild>() => false;");
        builder.AppendLine();

        // GetMetadata method
        GenerateGetMetadata(builder, model);

        builder.AppendLine("}");

        return builder.ToString();
    }

    private static void GeneratePropertyComponent(StringBuilder builder, PropertyModel property, ConfigurationModel model)
    {
        builder.AppendLine($"    public sealed class {property.PropertyName}Property : PropertyComponent<{property.PropertyName}Property, {property.PropertyType}>");
        builder.AppendLine("    {");

        builder.AppendLine($"        public {property.PropertyName}Property()");
        builder.AppendLine("        {");

        builder.AppendLine("            Metadata = new PropertyMetadata");
        builder.AppendLine("            {");

        builder.AppendLine($"                Name = nameof({model.ClassName}.{property.PropertyName}),");
        builder.AppendLine($"                PropertyType = \"{property.PropertyType}\",");
        if (property.Label != null)
            builder.AppendLine($"                Label = \"{EscapeString(property.Label)}\",");
        if (property.HelpText != null)
            builder.AppendLine($"                HelpText = \"{EscapeString(property.HelpText)}\",");
        builder.AppendLine($"                Required = {(property.IsRequired ? "true" : "false")},");
        builder.AppendLine($"                ComponentTypeId = {(int)property.ComponentType},");

        if (property.ValidationRules.Count > 0)
        {
            builder.AppendLine("                ValidationRules = new Dictionary<string, object>");
            builder.AppendLine("                {");
            foreach (var rule in property.ValidationRules)
            {
                builder.AppendLine($"                    [\"{rule.Key}\"] = {FormatValue(rule.Value)},");
            }
            builder.AppendLine("                },");
        }

        // Add TypeCollection metadata if applicable
        if (property.IsTypeCollectionReference)
        {
            builder.AppendLine("                Attributes = new Dictionary<string, object>");
            builder.AppendLine("                {");
            builder.AppendLine($"                    [\"TypeCollectionType\"] = \"{property.TypeCollectionName}\",");
            builder.AppendLine($"                    [\"TypeOptionInterface\"] = \"{property.TypeOptionInterfaceName}\"");
            builder.AppendLine("                },");
        }

        builder.AppendLine("            };");

        builder.AppendLine("        }");

        builder.AppendLine("    }");
        builder.AppendLine();
    }

    private static void GenerateGetPropertyComponents(StringBuilder builder, ConfigurationModel model)
    {
        builder.AppendLine("    protected override IEnumerable<IPropertyComponent> GetPropertyComponents()");
        builder.AppendLine("    {");

        foreach (var property in model.Properties)
        {
            builder.AppendLine($"        yield return new {property.PropertyName}Property");
            builder.AppendLine("        {");
            builder.AppendLine($"            Value = Value?.{property.PropertyName},");
            builder.AppendLine("            ValueChanged = newValue =>");
            builder.AppendLine("            {");
            builder.AppendLine($"                if (Value != null) Value.{property.PropertyName} = newValue;");
            builder.AppendLine("            }");
            builder.AppendLine("        };");
            builder.AppendLine();
        }

        builder.AppendLine("    }");
        builder.AppendLine();
    }

    private static void GenerateGetMetadata(StringBuilder builder, ConfigurationModel model)
    {
        builder.AppendLine("    public override ComponentMetadata GetMetadata()");
        builder.AppendLine("    {");

        builder.AppendLine("        return new ComponentMetadata");
        builder.AppendLine("        {");
        builder.AppendLine($"            ComponentType = nameof({model.ClassName}WebComponent),");
        builder.AppendLine($"            ModelType = nameof({model.ClassName}),");
        builder.AppendLine("            RenderModeId = RenderModeId,");
        builder.AppendLine("            Properties = GetPropertyComponents()");
        builder.AppendLine("                .OfType<IPropertyComponent>()");
        builder.AppendLine("                .Select(p => p.Metadata!)");
        builder.AppendLine("                .ToList()");
        builder.AppendLine("        };");

        builder.AppendLine("    }");
    }

    private static string FormatValue(object value)
    {
        return value switch
        {
            string s => $"\"{EscapeString(s)}\"",
            _ => value.ToString() ?? "null"
        };
    }

    private static string EscapeString(string input)
    {
        return input.Replace("\\", "\\\\").Replace("\"", "\\\"");
    }
}
