<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>preview</LangVersion>

    <!-- Package Properties -->
    <PackageDescription>Extended logging abstractions with IGenericMessage return types. Fork of Microsoft.Extensions.Logging.Abstractions with return value support.</PackageDescription>
    <PackageTags>logging;messages;source-generator;logging-abstractions</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Fdw.Messages\Fdw.Messages.csproj" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
  </ItemGroup>

</Project>
