using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Spectre.Console;
using Fdw.UI.Abstractions;
using Fdw.UI.Components.TUI;

namespace Fdw.UI.Components.RazorConsole;

/// <summary>
/// Base class for RazorConsole components.
/// Inherits from TUIComponent to provide Spectre.Console integration.
/// </summary>
/// <typeparam name="TModel">The model type this component renders</typeparam>
public abstract class RazorConsoleComponent<TModel> : TUIComponent<RazorConsoleComponent<TModel>, TModel>
{
    /// <summary>
    /// The console instance to render to.
    /// Set by generated code or consumer.
    /// </summary>
    protected IAnsiConsole Console { get; set; } = AnsiConsole.Console;

    /// <summary>
    /// Gets or sets the model being rendered.
    /// Alias for Value property from base class for Razor compatibility.
    /// </summary>
    public TModel Model
    {
        get => Value!;
        set => Value = value;
    }

    /// <summary>
    /// Called when component initializes.
    /// Override in derived components for initialization logic.
    /// </summary>
    protected virtual void OnInitialized()
    {
    }

    /// <summary>
    /// Async version of OnInitialized.
    /// </summary>
#pragma warning disable FDW001 // Blazor lifecycle convention requires Async suffix
    protected virtual Task OnInitializedAsync()
#pragma warning restore FDW001
    {
        return Task.CompletedTask;
    }

    /// <summary>
    /// Called when parameters are set.
    /// </summary>
    protected virtual void OnParametersSet()
    {
    }

    /// <summary>
    /// Async version of OnParametersSet.
    /// </summary>
#pragma warning disable FDW001 // Blazor lifecycle convention requires Async suffix
    protected virtual Task OnParametersSetAsync()
#pragma warning restore FDW001
    {
        return Task.CompletedTask;
    }

    /// <summary>
    /// Gets property components (not used in RazorConsole, but required by base).
    /// </summary>
    protected override IEnumerable<IPropertyComponent> GetPropertyComponents()
    {
        yield break;
    }

    /// <summary>
    /// Determines if this component can contain a child (not used in RazorConsole).
    /// </summary>
    protected override bool CanContain<TChild>() => false;

    /// <summary>
    /// Prompts for interactive input.
    /// Generated by source generator from .cshtml markup.
    /// </summary>
    public abstract override Task<TModel?> Prompt(IAnsiConsole console);

    /// <summary>
    /// Renders component to console (display-only).
    /// Generated by source generator from .cshtml markup.
    /// </summary>
    public abstract override void Render(IAnsiConsole console);
}
