using System.Linq;
using System.Threading.Tasks;
using Microsoft.CodeAnalysis;
using Xunit;

namespace Fdw.Collections.SourceGenerators.Tests;

/// <summary>
/// End-to-end tests for generated TypeCollection code (modeled after Microsoft pattern).
/// Tests that generated code actually compiles and behaves correctly.
/// </summary>
public class TypeCollectionGeneratedCodeTests
{
    [Fact]
    [Trait("Priority", "P0")]
    [Trait("Category", "SourceGen")]
    public async Task GeneratedCollection_Compiles()
    {
        var source = @"
using Fdw.Collections;
using Fdw.Collections.Attributes;

namespace Test;

public abstract class ConnectionTypeBase : TypeOptionBase<int, ConnectionTypeBase>
{
    protected ConnectionTypeBase(int id, string name) : base(id, name) { }
}

[TypeCollection(typeof(ConnectionTypeBase), typeof(ConnectionTypeBase), typeof(ConnectionTypes))]
public partial class ConnectionTypes : TypeCollectionBase<ConnectionTypeBase, ConnectionTypeBase>
{
}

[TypeOption(typeof(ConnectionTypes), ""MsSql"")]
public class MsSqlConnectionType : ConnectionTypeBase
{
    public MsSqlConnectionType() : base(1, ""MsSql"") { }
}

[TypeOption(typeof(ConnectionTypes), ""PostgreSql"")]
public class PostgreSqlConnectionType : ConnectionTypeBase
{
    public PostgreSqlConnectionType() : base(2, ""PostgreSql"") { }
}
";

        var (compilation, diagnostics) = CompilationHelper.RunGenerator(source);

        // No generator errors
        Assert.Empty(diagnostics.Where(d => d.Severity == DiagnosticSeverity.Error));

        // Verify generated code has expected content
        var generated = CompilationHelper.GetGeneratedOutput(compilation, "ConnectionTypes.TypeCollection.g.cs");
        Assert.NotNull(generated);
        Assert.Contains("partial class ConnectionTypes", generated);
        Assert.Contains("MsSql", generated);
        Assert.Contains("PostgreSql", generated);
    }

    [Fact]
    [Trait("Priority", "P0")]
    [Trait("Category", "SourceGen")]
    public async Task GeneratedCollection_ByName_ReturnsCorrectType()
    {
        var source = @"
using Fdw.Collections;
using Fdw.Collections.Attributes;

namespace Test;

public abstract class TestBase : TypeOptionBase<int, TestBase>
{
    protected TestBase(int id, string name) : base(id, name) { }
}

[TypeCollection(typeof(TestBase), typeof(TestBase), typeof(Tests))]
public partial class Tests : TypeCollectionBase<TestBase, TestBase>
{
}

[TypeOption(typeof(Tests), ""Alpha"")]
public class AlphaType : TestBase
{
    public AlphaType() : base(1, ""Alpha"") { }
}
";

        var (compilation, _) = CompilationHelper.RunGenerator(source);
        var generated = CompilationHelper.GetGeneratedOutput(compilation, "Tests.TypeCollection.g.cs");

        Assert.NotNull(generated);

        // Generated ByName method
        Assert.Contains("ByName", generated);

        // Has Alpha property
        Assert.Contains("Alpha", generated);
    }

    [Fact]
    [Trait("Priority", "P0")]
    [Trait("Category", "SourceGen")]
    public async Task GeneratedCollection_Empty_ReturnsNonNull()
    {
        var source = @"
using Fdw.Collections;
using Fdw.Collections.Attributes;

namespace Test;

public abstract class TestBase : TypeOptionBase<int, TestBase>
{
    protected TestBase(int id, string name) : base(id, name) { }
}

[TypeCollection(typeof(TestBase), typeof(TestBase), typeof(Tests))]
public partial class Tests : TypeCollectionBase<TestBase, TestBase>
{
}
";

        var (compilation, _) = CompilationHelper.RunGenerator(source);
        var generated = CompilationHelper.GetGeneratedOutput(compilation, "Tests.TypeCollection.g.cs");

        Assert.NotNull(generated);

        // NotFound sentinel generated
        Assert.Contains("NotFound", generated);
        Assert.Contains("NotFoundTests", generated);
    }

    [Fact]
    [Trait("Priority", "P0")]
    [Trait("Category", "SourceGen")]
    public async Task ParentChildCollection_GeneratesCorrectHierarchy()
    {
        var source = @"
using Fdw.Collections;
using Fdw.Collections.Attributes;

namespace Test;

// Parent base
public abstract class ParentBase : TypeCollectionBase<ChildBase, ChildBase>
{
    protected ParentBase(string name) : base(name) { }
}

// Parent collection
[TypeCollection(typeof(ParentBase), typeof(ParentBase), typeof(Parents))]
public partial class Parents : TypeCollectionBase<ParentBase, ParentBase>
{
}

// Child base
public abstract class ChildBase : TypeOptionBase<int, ChildBase>
{
    protected ChildBase(int id, string name) : base(id, name) { }
}

// Child collection (member of parent)
[TypeCollection(typeof(ChildBase),
                typeof(ChildBase),
                typeof(MsSqlTypes),
                TypeOption = typeof(Parents),
                TypeOptionName = ""MsSql"")]
public partial class MsSqlTypes : ParentBase
{
    protected MsSqlTypes() : base(""Microsoft SQL Server"") { }
}

// TypeOption in child collection
[TypeOption(typeof(MsSqlTypes), ""Int32"")]
public class Int32Type : ChildBase
{
    public Int32Type() : base(1, ""Int32"") { }
}
";

        var (compilation, diagnostics) = CompilationHelper.RunGenerator(source);

        Assert.Empty(diagnostics.Where(d => d.Severity == DiagnosticSeverity.Error));

        // Parent should reference child
        var parentGenerated = CompilationHelper.GetGeneratedOutput(compilation, "Parents.TypeCollection.g.cs");
        Assert.NotNull(parentGenerated);
        Assert.Contains("MsSql", parentGenerated);

        // Child should have its options
        var childGenerated = CompilationHelper.GetGeneratedOutput(compilation, "MsSqlTypes.TypeCollection.g.cs");
        Assert.NotNull(childGenerated);
        Assert.Contains("Int32", childGenerated);
    }
}
