using System.Diagnostics.CodeAnalysis;
using Fdw.Abstractions;
using Fdw.Collections;

namespace Fdw.Web.Clients.Abstractions.Registration;

/// <summary>
/// ServiceTypeCollection for all registered API client types.
/// </summary>
/// <remarks>
/// <para>
/// Cross-assembly options (e.g., <c>PipelineClientType</c> in <c>Pipelines.Clients</c>) are registered
/// via a <c>[ModuleInitializer]</c> generated by <c>Fdw.Registration.SourceGenerators</c>
/// in the entry point project (e.g., <c>Reference.Api</c>, <c>Reference.UI</c>).
/// </para>
/// <para>
/// The entry point calls <c>ApiClientTypes.Configure(builder)</c> and <c>ApiClientTypes.Register(builder.Services)</c>
/// which iterate all registered options and invoke each type's
/// <c>Configure</c> and <c>Register</c> methods.
/// </para>
/// </remarks>
[ExcludeFromCodeCoverage]
[ServiceTypeCollection(
    typeof(ApiClientTypeBase<IGenericService>),
    typeof(IApiClientType),
    typeof(ApiClientTypes),
    ServiceCategory = "ApiClient")]
public partial class ApiClientTypes
    : ServiceTypeCollectionBase<ApiClientTypeBase<IGenericService>, IApiClientType> { }
