<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <RootNamespace>Fdw.Services.Catalog.Clients</RootNamespace>
    <PackageId>Fdw.Services.Catalog.Clients</PackageId>
    <Title>Fdw Catalog API Clients</Title>
    <Description>API clients and DTOs for catalog operations.</Description>
    <PackageTags>api;clients;catalog</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../Fdw.Web.Clients/Fdw.Web.Clients.csproj" />
    <ProjectReference Include="..\Fdw.Web.Endpoints\Fdw.Web.Endpoints.csproj" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Http" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Fdw.Collections.SourceGenerators\Fdw.Collections.SourceGenerators.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" PrivateAssets="all" />
    <ProjectReference Include="..\Fdw.Web.Http.Authentication\Fdw.Web.Http.Authentication.csproj" />
    <ProjectReference Include="..\Fdw.Services.Catalog.Clients.Models\Fdw.Services.Catalog.Clients.Models.csproj" />
  </ItemGroup>

</Project>
