using System;
using System.Linq;
using System.Text;
using Fdw.Configuration.SourceGenerators.Analysis;
using Fdw.Configuration.SourceGenerators.Models;

namespace Fdw.Configuration.SourceGenerators.Generators;

/// <summary>
/// Generates DDL definition code for configuration classes.
/// </summary>
public static class DdlGenerator
{
    /// <summary>
    /// Generates the source code for a configuration's DDL provider implementation.
    /// </summary>
    // MA0051: Method length acceptable - comprehensive DDL generation with parent/child relationships and audit columns
#pragma warning disable MA0051 // Method is too long
    public static string Generate(ConfigurationModel model, ParentChildGraph graph)
#pragma warning restore MA0051
    {
        var sb = new StringBuilder();
        var tableName = model.GetEffectiveTableName();
        // Why: Parent-child structure is now owned by IDataNode, not [ManagedConfiguration].
        // All config types generate as flat root tables. hasParent is always false here.
        var hasParent = false;
        var parentFkColumn = (string?)null;

        // Map properties to columns, applying the following exclusions:
        // - "Id" and "Name" are added separately as standard columns above
        // - Navigation properties (IsNavigationProperty=true, ExcludeFromDdl=true) are excluded
        //   because their type carries [ManagedConfiguration] and represents a separate child
        //   table — emitting them as SQL columns would create a bogus varchar(MAX) JSON column
        //   where a FK relationship already exists. ExcludeFromDdl is set by PropertyAnalyzer
        //   during the analysis phase; by the time Properties reaches here those entries are
        //   already removed by ConfigurationAnalyzer (which filters on !p.ExcludeFromDdl).
        var userColumns = model.Properties
            .Where(p => !string.Equals(p.PropertyName, "Id", StringComparison.Ordinal) &&
                       !string.Equals(p.PropertyName, "Name", StringComparison.Ordinal))
            .Select(SqlTypeMapper.MapToColumn)
            .ToList();

        // Header
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        // Usings
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using Fdw.Configuration.Persistence.Schema;");
        sb.AppendLine();

        // Namespace
        sb.AppendLine($"namespace {model.Namespace}");
        sb.AppendLine("{");

        // Partial class implementing IConfigurationDdlProvider
        // Why the attribute goes on the generated MEMBERS below and not on this declaration: the
        // type is a partial shared with the user's hand-written [ManagedConfiguration] POCO, and an
        // attribute on any part of a partial applies to the WHOLE type — marking it here would
        // silently exclude the consumer's own properties and any logic they add. Member-level
        // marking excludes exactly what this generator emits and nothing else.
        sb.AppendLine($"    partial class {model.ClassName} : IConfigurationDdlProvider");
        sb.AppendLine("    {");

        // GetDdlDefinition static method
        // Why: Use 'new' only when the parent class also has [ManagedConfiguration] (both generate GetDdlDefinition).
        // ParentHasManagedConfiguration is now set by Roslyn symbol analysis in ConfigurationAnalyzer
        // rather than by the attribute — IDataNode owns structural hierarchy, not [ManagedConfiguration].
        var methodModifier = model.ParentHasManagedConfiguration ? "public new static" : "public static";
        sb.AppendLine("        /// <summary>");
        sb.AppendLine("        /// Gets the DDL definition for this configuration type.");
        sb.AppendLine("        /// </summary>");
        sb.AppendLine("        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]");
        sb.AppendLine($"        {methodModifier} DdlDefinition GetDdlDefinition()");
        sb.AppendLine("        {");
        sb.AppendLine("            return new DdlDefinition");
        sb.AppendLine("            {");
        sb.AppendLine($"                TableName = \"{tableName}\",");
        sb.AppendLine($"                ConfigurationTypeName = \"{model.FullTypeName}\",");

        // Columns
        sb.AppendLine("                Columns = new List<ColumnDefinition>");
        sb.AppendLine("                {");

        // RowId column - version-specific primary key (always first)
        GenerateRowIdColumn(sb);

        // Id column - logical identity for root tables (persists across versions)
        // Child tables get Id from parent via join on FK
        if (!hasParent)
        {
            GenerateIdColumn(sb);
        }

        // FK column for child tables (e.g., ConnectionId)
        // References parent's logical Id, join with WHERE IsCurrent = 1
        if (hasParent && parentFkColumn != null)
        {
            sb.AppendLine("                    new ColumnDefinition");
            sb.AppendLine("                    {");
            sb.AppendLine($"                        Name = \"{parentFkColumn}\",");
            sb.AppendLine("                        SqlType = \"uniqueidentifier\",");
            sb.AppendLine("                        IsNullable = false");
            sb.AppendLine("                    },");
        }

        // Name column for root configurations only
        // Skip for child tables - they inherit Name from parent via FK
        if (!hasParent)
        {
            sb.AppendLine("                    new ColumnDefinition");
            sb.AppendLine("                    {");
            sb.AppendLine("                        Name = \"Name\",");
            sb.AppendLine("                        SqlType = \"varchar\",");
            sb.AppendLine("                        MaxLength = 256,");
            sb.AppendLine("                        IsNullable = false,");
            sb.AppendLine("                        IsUnique = false");  // Unique per IsCurrent=1, not globally
            sb.AppendLine("                    },");
        }

        // Add columns from properties
        foreach (var column in userColumns)
        {
            GenerateColumnDefinition(sb, column);
        }

        // Standard audit columns (8 columns for version tracking)
        // IsCurrent - indicates this is the current/active version
        sb.AppendLine("                    new ColumnDefinition");
        sb.AppendLine("                    {");
        sb.AppendLine("                        Name = \"IsCurrent\",");
        sb.AppendLine("                        SqlType = \"bit\",");
        sb.AppendLine("                        IsNullable = false,");
        sb.AppendLine("                        DefaultValue = \"1\"");
        sb.AppendLine("                    },");

        // IsDeleted - soft delete flag
        sb.AppendLine("                    new ColumnDefinition");
        sb.AppendLine("                    {");
        sb.AppendLine("                        Name = \"IsDeleted\",");
        sb.AppendLine("                        SqlType = \"bit\",");
        sb.AppendLine("                        IsNullable = false,");
        sb.AppendLine("                        DefaultValue = \"0\"");
        sb.AppendLine("                    },");

        // CreateDate - when the record was created
        sb.AppendLine("                    new ColumnDefinition");
        sb.AppendLine("                    {");
        sb.AppendLine("                        Name = \"CreateDate\",");
        sb.AppendLine("                        SqlType = \"datetimeoffset\",");
        sb.AppendLine("                        IsNullable = false,");
        sb.AppendLine("                        DefaultValue = \"SYSDATETIMEOFFSET()\"");
        sb.AppendLine("                    },");

        // CreateBy - system user/service that created the record
        sb.AppendLine("                    new ColumnDefinition");
        sb.AppendLine("                    {");
        sb.AppendLine("                        Name = \"CreateBy\",");
        sb.AppendLine("                        SqlType = \"varchar\",");
        sb.AppendLine("                        MaxLength = 100,");
        sb.AppendLine("                        IsNullable = false,");
        sb.AppendLine("                        DefaultValue = \"SYSTEM_USER\"");
        sb.AppendLine("                    },");

        // CreateByUser - application-level user who initiated the creation
        sb.AppendLine("                    new ColumnDefinition");
        sb.AppendLine("                    {");
        sb.AppendLine("                        Name = \"CreateByUser\",");
        sb.AppendLine("                        SqlType = \"varchar\",");
        sb.AppendLine("                        MaxLength = 100,");
        sb.AppendLine("                        IsNullable = true");
        sb.AppendLine("                    },");

        // ModifyDate - when the record was last modified
        sb.AppendLine("                    new ColumnDefinition");
        sb.AppendLine("                    {");
        sb.AppendLine("                        Name = \"ModifyDate\",");
        sb.AppendLine("                        SqlType = \"datetimeoffset\",");
        sb.AppendLine("                        IsNullable = true");
        sb.AppendLine("                    },");

        // ModifyBy - system user/service that last modified the record
        sb.AppendLine("                    new ColumnDefinition");
        sb.AppendLine("                    {");
        sb.AppendLine("                        Name = \"ModifyBy\",");
        sb.AppendLine("                        SqlType = \"varchar\",");
        sb.AppendLine("                        MaxLength = 100,");
        sb.AppendLine("                        IsNullable = true");
        sb.AppendLine("                    },");

        // ModifyOnBehalfOf - application-level user who initiated the last modification
        sb.AppendLine("                    new ColumnDefinition");
        sb.AppendLine("                    {");
        sb.AppendLine("                        Name = \"ModifyOnBehalfOf\",");
        sb.AppendLine("                        SqlType = \"varchar\",");
        sb.AppendLine("                        MaxLength = 100,");
        sb.AppendLine("                        IsNullable = true");
        sb.AppendLine(model.Temporal ? "                    }," : "                    }");

        GenerateTemporalColumns(sb, model);

        sb.AppendLine("                },");

        // Foreign Keys
        GenerateForeignKeys(sb, model, graph, tableName, hasParent, parentFkColumn);

        // Indexes
        GenerateIndexes(sb, model, tableName, hasParent, parentFkColumn);

        sb.AppendLine("            };");
        sb.AppendLine("        }");

        // Instance method that calls static (for interface implementation)
        sb.AppendLine();
        sb.AppendLine("        /// <summary>");
        sb.AppendLine("        /// Gets the DDL definition for this configuration instance.");
        sb.AppendLine("        /// </summary>");
        sb.AppendLine("        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]");
        sb.AppendLine("        DdlDefinition IConfigurationDdlProvider.GetDefinition() => GetDdlDefinition();");

        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    private static void GenerateForeignKeys(StringBuilder sb, ConfigurationModel model, ParentChildGraph graph, string tableName, bool hasParent, string? parentFkColumn)
    {
        sb.AppendLine("                ForeignKeys = new List<ForeignKeyDefinition>");
        sb.AppendLine("                {");

        var hasForeignKeys = false;

        // Why: Parent FK generation was removed — IDataNode now owns parent-child structure.
        // hasParent is always false; this block would never execute. Omitted entirely.

        // TypeCollection FKs
        foreach (var prop in model.Properties.Where(p => p.TypeCollectionReference != null))
        {
            var tcRef = prop.TypeCollectionReference!;
            // When ById is true, the FK column references Id directly (e.g., StatusId -> Id)
            // When ById is false, the FK column references Name (e.g., Status -> Name)
            var fkColumn = prop.PropertyName;
            var referencedColumn = tcRef.ById ? "Id" : "Name";

            if (hasForeignKeys)
                sb.AppendLine(",");

            sb.AppendLine("                    new ForeignKeyDefinition");
            sb.AppendLine("                    {");
            sb.AppendLine($"                        Name = \"FK_{tableName}_{tcRef.TableName}\",");
            sb.AppendLine($"                        Column = \"{fkColumn}\",");
            sb.AppendLine($"                        ReferencedSchema = \"{tcRef.Schema}\",");
            sb.AppendLine($"                        ReferencedTable = \"{tcRef.TableName}\",");
            sb.AppendLine($"                        ReferencedColumn = \"{referencedColumn}\",");
            sb.AppendLine("                        OnDelete = new NoActionForeignKeyAction()");
            sb.AppendLine("                    }");
            hasForeignKeys = true;
        }

        sb.AppendLine("                },");
    }

    // MA0051: Method length acceptable - procedural generation of filtered unique indexes and performance indexes for version tracking
#pragma warning disable MA0051 // Method is too long
    private static void GenerateIndexes(StringBuilder sb, ConfigurationModel model, string tableName, bool hasParent, string? parentFkColumn)
#pragma warning restore MA0051
    {
        sb.AppendLine("                Indexes = new List<IndexDefinition>");
        sb.AppendLine("                {");

        bool hasIndexes = false;

        // Filtered unique index on Id WHERE IsCurrent=1 (for root tables)
        // Ensures only one current version per logical Id
        if (!hasParent)
        {
            sb.AppendLine("                    new IndexDefinition");
            sb.AppendLine("                    {");
            sb.AppendLine($"                        Name = \"UX_{tableName}_Id_Current\",");
            sb.AppendLine("                        Columns = new[] { \"Id\" },");
            sb.AppendLine("                        IsUnique = true,");
            sb.AppendLine("                        FilterPredicate = \"IsCurrent = 1\"");
            sb.AppendLine("                    },");
            hasIndexes = true;

            // Filtered unique index on Name WHERE IsCurrent=1
            sb.AppendLine("                    new IndexDefinition");
            sb.AppendLine("                    {");
            sb.AppendLine($"                        Name = \"UX_{tableName}_Name_Current\",");
            sb.AppendLine("                        Columns = new[] { \"Name\" },");
            sb.AppendLine("                        IsUnique = true,");
            sb.AppendLine("                        FilterPredicate = \"IsCurrent = 1\"");
            sb.AppendLine("                    },");

            // Regular index on Id for all versions
            sb.AppendLine("                    new IndexDefinition");
            sb.AppendLine("                    {");
            sb.AppendLine($"                        Name = \"IX_{tableName}_Id\",");
            sb.AppendLine("                        Columns = new[] { \"Id\" },");
            sb.AppendLine("                        IsUnique = false");
            sb.AppendLine("                    },");
        }

        // Index on FK column for child tables (improves join performance)
        // Plus filtered unique index for one current version per parent
        if (hasParent && parentFkColumn != null)
        {
            if (hasIndexes) sb.AppendLine();
            // Filtered unique index - one current child per parent
            sb.AppendLine("                    new IndexDefinition");
            sb.AppendLine("                    {");
            sb.AppendLine($"                        Name = \"UX_{tableName}_{parentFkColumn}_Current\",");
            sb.AppendLine($"                        Columns = new[] {{ \"{parentFkColumn}\" }},");
            sb.AppendLine("                        IsUnique = true,");
            sb.AppendLine("                        FilterPredicate = \"IsCurrent = 1\"");
            sb.AppendLine("                    },");

            // Regular index on FK
            sb.AppendLine("                    new IndexDefinition");
            sb.AppendLine("                    {");
            sb.AppendLine($"                        Name = \"IX_{tableName}_{parentFkColumn}\",");
            sb.AppendLine($"                        Columns = new[] {{ \"{parentFkColumn}\" }},");
            sb.AppendLine("                        IsUnique = false");
            sb.AppendLine("                    },");
            hasIndexes = true;
        }

        // Index on IsCurrent for active record queries
        if (hasIndexes) sb.AppendLine();
        sb.AppendLine("                    new IndexDefinition");
        sb.AppendLine("                    {");
        sb.AppendLine($"                        Name = \"IX_{tableName}_IsCurrent\",");
        sb.AppendLine("                        Columns = new[] { \"IsCurrent\" },");
        sb.AppendLine("                        IsUnique = false");
        sb.AppendLine("                    },");

        // Index on IsDeleted for soft delete queries
        sb.AppendLine();
        sb.AppendLine("                    new IndexDefinition");
        sb.AppendLine("                    {");
        sb.AppendLine($"                        Name = \"IX_{tableName}_IsDeleted\",");
        sb.AppendLine("                        Columns = new[] { \"IsDeleted\" },");
        sb.AppendLine("                        IsUnique = false");
        sb.AppendLine("                    }");

        // Why an as-of covering index: every other index here is filtered WHERE IsCurrent = 1, so
        // none of them serves a historical lookup. An as-of read scans by logical Id across ALL
        // versions and picks the one whose effective interval contains the instant — unindexed,
        // that degrades to a full scan of the entity's whole history on every restatement.
        if (model.Temporal)
        {
            sb.AppendLine("                    ,");
            sb.AppendLine("                    new IndexDefinition");
            sb.AppendLine("                    {");
            sb.AppendLine($"                        Name = \"IX_{tableName}_Id_Effective\",");
            sb.AppendLine("                        Columns = new[] { \"Id\", \"EffectiveStart\", \"EffectiveEnd\" },");
            sb.AppendLine("                        IsUnique = false");
            sb.AppendLine("                    }");
        }

        // Add property-specific indexes
        foreach (var prop in model.Properties.Where(p => !string.IsNullOrEmpty(p.IndexName)))
        {
            sb.AppendLine("                    ,");
            sb.AppendLine("                    new IndexDefinition");
            sb.AppendLine("                    {");
            sb.AppendLine($"                        Name = \"{prop.IndexName}\",");
            sb.AppendLine($"                        Columns = new[] {{ \"{prop.ColumnName ?? prop.PropertyName}\" }},");
            sb.AppendLine("                        IsUnique = false");
            sb.AppendLine("                    }");
        }

        sb.AppendLine("                }");
    }

    /// <summary>
    /// Emits the valid-time columns for an effective-dated configuration.
    /// </summary>
    /// <remarks>
    /// Why these sit alongside CreateDate/ModifyDate rather than replacing them: the two record
    /// different facts. CreateDate/ModifyDate are transaction-time — when the row was written —
    /// and answer "what did we believe on date X". EffectiveStart/EffectiveEnd are valid-time —
    /// the period the row governs — and answer "what was in force FOR period X". A restatement
    /// needs the second; an audit of who changed what needs the first. Keeping both makes the
    /// configuration bitemporal for the types that opt in.
    /// EffectiveEnd is nullable and open-ended: NULL means "still in force", which is what lets
    /// an as-of predicate be written without a sentinel end date.
    /// </remarks>
    private static void GenerateTemporalColumns(StringBuilder sb, ConfigurationModel model)
    {
        if (!model.Temporal)
        {
            return;
        }

        sb.AppendLine("                    new ColumnDefinition");
        sb.AppendLine("                    {");
        sb.AppendLine("                        Name = \"EffectiveStart\",");
        sb.AppendLine("                        SqlType = \"datetimeoffset\",");
        sb.AppendLine("                        IsNullable = false,");
        sb.AppendLine("                        DefaultValue = \"SYSDATETIMEOFFSET()\"");
        sb.AppendLine("                    },");

        sb.AppendLine("                    new ColumnDefinition");
        sb.AppendLine("                    {");
        sb.AppendLine("                        Name = \"EffectiveEnd\",");
        sb.AppendLine("                        SqlType = \"datetimeoffset\",");
        sb.AppendLine("                        IsNullable = true");
        sb.AppendLine("                    }");
    }

    private static void GenerateRowIdColumn(StringBuilder sb)
    {
        // RowId is the version-specific primary key
        sb.AppendLine("                    new ColumnDefinition");
        sb.AppendLine("                    {");
        sb.AppendLine("                        Name = \"RowId\",");
        sb.AppendLine("                        SqlType = \"uniqueidentifier\",");
        sb.AppendLine("                        IsNullable = false,");
        sb.AppendLine("                        DefaultValue = \"NEWID()\"");
        sb.AppendLine("                    },");
    }

    private static void GenerateIdColumn(StringBuilder sb)
    {
        // Id is the logical/durable identity (persists across versions)
        sb.AppendLine("                    new ColumnDefinition");
        sb.AppendLine("                    {");
        sb.AppendLine("                        Name = \"Id\",");
        sb.AppendLine("                        SqlType = \"uniqueidentifier\",");
        sb.AppendLine("                        IsNullable = false");
        sb.AppendLine("                    },");
    }

    private static void GenerateColumnDefinition(StringBuilder sb, SqlColumnDefinition column)
    {
        sb.AppendLine("                    new ColumnDefinition");
        sb.AppendLine("                    {");
        sb.AppendLine($"                        Name = \"{column.ColumnName}\",");
        sb.AppendLine($"                        SqlType = \"{column.SqlType}\",");

        if (column.MaxLength.HasValue)
        {
            sb.AppendLine($"                        MaxLength = {column.MaxLength.Value},");
        }

        if (column.Precision.HasValue)
        {
            sb.AppendLine($"                        Precision = {column.Precision.Value},");
        }

        if (column.Scale.HasValue)
        {
            sb.AppendLine($"                        Scale = {column.Scale.Value},");
        }

        sb.AppendLine($"                        IsNullable = {(column.IsNullable ? "true" : "false")},");
        sb.AppendLine($"                        IsIdentity = {(column.IsIdentity ? "true" : "false")},");
        sb.AppendLine($"                        IsUnique = {(column.IsUnique ? "true" : "false")}");

        if (!string.IsNullOrEmpty(column.DefaultValue))
        {
            // Remove trailing newline and add DefaultValue
            RemoveTrailingNewline(sb);
            sb.AppendLine(",");
            sb.AppendLine($"                        DefaultValue = \"{EscapeString(column.DefaultValue!)}\"");
        }

        sb.AppendLine("                    },");
    }

    private static void RemoveTrailingNewline(StringBuilder sb)
    {
        while (sb.Length > 0 && (sb[sb.Length - 1] == '\n' || sb[sb.Length - 1] == '\r'))
        {
            sb.Length--;
        }
    }

    private static string EscapeString(string value)
    {
        return value.Replace("\\", "\\\\").Replace("\"", "\\\"");
    }
}
