using System;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Fdw.Configuration.SourceGenerators.Models;

namespace Fdw.Configuration.SourceGenerators.Generators;

/// <summary>
/// Generates DDL definitions for TypeCollections referenced by [ConfigurationOption].
/// </summary>
public static class TypeCollectionDdlGenerator
{
    /// <summary>
    /// Generates DDL provider class for a TypeCollection.
    /// </summary>
    // MA0051: Statement count acceptable - procedural DDL code generation with fixed schema structure
#pragma warning disable MA0051 // Method is too long
    public static string Generate(TypeCollectionReference tcRef)
#pragma warning restore MA0051
    {
        var sb = new StringBuilder();
        var className = $"{tcRef.TypeCollectionName}TypeCollectionDdl";

        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using Fdw.Configuration.Persistence.Schema;");
        sb.AppendLine();
        sb.AppendLine("namespace Fdw.Configuration.Generated;");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine($"/// DDL definition for TypeCollection {tcRef.TypeCollectionName}.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine($"public static class {className}");
        sb.AppendLine("{");
        sb.AppendLine($"    /// <summary>Gets the DDL definition for the {tcRef.TableName} table.</summary>");
        sb.AppendLine("    public static DdlDefinition GetDdlDefinition() => new DdlDefinition");
        sb.AppendLine("    {");
        sb.AppendLine($"        Schema = \"{tcRef.Schema}\",");
        sb.AppendLine($"        TableName = \"{tcRef.TableName}\",");
        sb.AppendLine($"        ConfigurationTypeName = \"{tcRef.TypeCollectionFullName}\",");
        sb.AppendLine("        Columns = new List<ColumnDefinition>");
        sb.AppendLine("        {");
        sb.AppendLine("            new ColumnDefinition");
        sb.AppendLine("            {");
        sb.AppendLine("                Name = \"Id\",");
        sb.AppendLine("                SqlType = \"int\",");
        sb.AppendLine("                IsNullable = false");
        sb.AppendLine("            },");
        sb.AppendLine("            new ColumnDefinition");
        sb.AppendLine("            {");
        sb.AppendLine("                Name = \"Name\",");
        sb.AppendLine("                SqlType = \"varchar\",");
        sb.AppendLine("                MaxLength = 100,");
        sb.AppendLine("                IsNullable = false,");
        sb.AppendLine("                IsUnique = true");
        sb.AppendLine("            }");
        sb.AppendLine("        },");
        sb.AppendLine("        Indexes = new List<IndexDefinition>");
        sb.AppendLine("        {");
        sb.AppendLine("            new IndexDefinition");
        sb.AppendLine("            {");
        sb.AppendLine($"                Name = \"IX_{tcRef.TableName}_Name\",");
        sb.AppendLine("                Columns = new[] { \"Name\" },");
        sb.AppendLine("                IsUnique = true");
        sb.AppendLine("            }");
        sb.AppendLine("        },");
        sb.AppendLine("        ForeignKeys = new List<ForeignKeyDefinition>()");
        sb.AppendLine("    };");
        sb.AppendLine("}");

        return sb.ToString();
    }

    /// <summary>
    /// Generates the TypeCollectionDdlRegistry class.
    /// </summary>
    // MA0051: Statement count acceptable - procedural registry code generation with fixed structure
#pragma warning disable MA0051 // Method is too long
    public static string GenerateRegistry(ImmutableArray<TypeCollectionReference> typeCollections, string targetNamespace)
#pragma warning restore MA0051
    {
        var sb = new StringBuilder();
        var distinct = typeCollections
            .GroupBy(tc => tc.TypeCollectionFullName, StringComparer.Ordinal)
            .Select(g => g.First())
            .ToList();

        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using Fdw.Configuration.Persistence.Schema;");
        sb.AppendLine();
        sb.AppendLine($"namespace {targetNamespace};");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// Registry of all TypeCollections that need DDL generation.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("public static class TypeCollectionDdlRegistry");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>Gets all TypeCollection DDL registrations.</summary>");
        sb.AppendLine("    public static IReadOnlyList<TypeCollectionDdlInfo> All { get; } = new TypeCollectionDdlInfo[]");
        sb.AppendLine("    {");

        foreach (var tc in distinct)
        {
            var ddlClassName = $"{tc.TypeCollectionName}TypeCollectionDdl";
            sb.AppendLine($"        new TypeCollectionDdlInfo(");
            sb.AppendLine($"            \"{tc.TypeCollectionName}\",");
            sb.AppendLine($"            \"{tc.Schema}\",");
            sb.AppendLine($"            \"{tc.TableName}\",");
            sb.AppendLine($"            typeof({tc.TypeCollectionFullName}),");
            sb.AppendLine($"            Fdw.Configuration.Generated.{ddlClassName}.GetDdlDefinition),");
        }

        sb.AppendLine("    };");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// Information about a TypeCollection that needs DDL generation.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("/// <param name=\"Name\">The TypeCollection name.</param>");
        sb.AppendLine("/// <param name=\"Schema\">The database schema.</param>");
        sb.AppendLine("/// <param name=\"TableName\">The database table name.</param>");
        sb.AppendLine("/// <param name=\"TypeCollectionType\">The TypeCollection CLR type.</param>");
        sb.AppendLine("/// <param name=\"GetDdlDefinition\">Function to get the DDL definition.</param>");
        sb.AppendLine("public sealed record TypeCollectionDdlInfo(");
        sb.AppendLine("    string Name,");
        sb.AppendLine("    string Schema,");
        sb.AppendLine("    string TableName,");
        sb.AppendLine("    Type TypeCollectionType,");
        sb.AppendLine("    Func<DdlDefinition> GetDdlDefinition);");

        return sb.ToString();
    }
}
