using System;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Fdw.Data.SourceGenerators;

/// <summary>
/// Source generator that creates POCO to IDataRow mappers for types decorated with [GenerateMapper].
/// </summary>
/// <remarks>
/// <para>
/// This generator creates mapper classes for types marked with <c>[GenerateMapper]</c>.
/// The attribute is defined in <c>Fdw.Data.Abstractions</c>.
/// </para>
/// <para>
/// The generated mappers are registered with <c>PocoMapperCollection</c> via a module initializer
/// generated by <c>Fdw.Registration.SourceGenerators</c>. This separation ensures
/// that the module initializer runs in the consuming application's assembly, not in a library,
/// which guarantees proper initialization order.
/// </para>
/// <para>
/// Beyond scalar reader/dictionary mapping, the generator also emits the reflection-free cascade
/// surface (<c>CreateList</c>/<c>CreateArray</c>/<c>GetTypedBody</c>/<c>CascadeChildren</c>) consumed
/// by the configuration load/save cascade — replacing the runtime <c>MakeGenericMethod</c>/
/// <c>Activator.CreateInstance</c>/expression-tree reflection.
/// </para>
/// </remarks>
[Generator]
public sealed class PocoMapperGenerator : IIncrementalGenerator
{
    private const string GenericConfigurationFullName = "Fdw.Configuration.IGenericConfiguration";

    /// <inheritdoc />
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Find types with [GenerateMapper] (attribute is in Fdw.Data.Abstractions)
        var typesWithMapper = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                "Fdw.Data.GenerateMapperAttribute",
                predicate: static (node, _) => node is TypeDeclarationSyntax,
                transform: static (ctx, ct) => GetTypeInfo(ctx))
            .Where(static t => t != null);

        // Generate individual mappers as [TypeOption] members
        // Module initializer is generated by Fdw.Registration.SourceGenerators
        context.RegisterSourceOutput(typesWithMapper, static (spc, typeInfo) =>
        {
            if (typeInfo == null) return;
            GenerateMapper(spc, typeInfo.Value);
        });
    }

    private static TypeInfo? GetTypeInfo(GeneratorAttributeSyntaxContext context)
    {
        if (context.TargetSymbol is not INamedTypeSymbol typeSymbol)
            return null;

        // Read the Direction property from [GenerateMapper(Direction = ...)].
        // Default is 0 (MapperDirection.Input) when the property is absent, which preserves
        // backward compat for all existing [GenerateMapper] sites.
        var direction = MapperDirection.Input;
        if (context.Attributes.Length > 0)
        {
            var attr = context.Attributes[0];
            foreach (var namedArg in attr.NamedArguments)
            {
                if (string.Equals(namedArg.Key, "Direction", System.StringComparison.Ordinal) &&
                    namedArg.Value.Value is int directionValue)
                {
                    direction = (MapperDirection)directionValue;
                }
            }
        }

        // Create a format that includes nullable annotations
        var displayFormat = SymbolDisplayFormat.FullyQualifiedFormat.WithMiscellaneousOptions(
            SymbolDisplayFormat.FullyQualifiedFormat.MiscellaneousOptions |
            SymbolDisplayMiscellaneousOptions.IncludeNullableReferenceTypeModifier);

        // Why: Walk the entire base type chain to collect all public settable properties.
        // Derived types (e.g., MsSqlConnectionConfiguration) must include inherited properties
        // (e.g., Id, Name from ConnectionConfiguration) so that MsSqlConfigurationSaveTranslator
        // can intersect the PocoMapper property names with parent table container fields and
        // produce a non-empty INSERT column list for the parent table write.
        var seenNames = new System.Collections.Generic.HashSet<string>(System.StringComparer.Ordinal);
        var allProperties = new System.Collections.Generic.List<PropertyInfo>();
        var children = new System.Collections.Generic.List<ChildInfo>();
        string? typedBodyTypeFqn = null;

        // Why: the cascade stamps the parent's logical Id onto each level-1 child's FK property,
        // named {Strip(parentType)}Id (mirrors ImplementationConfigurationProviderBase.StripConfigurationSuffix).
        var parentFkName = StripConfigurationSuffix(typeSymbol.Name) + "Id";
        // Why: the READ cascade filters child rows by the PHYSICAL {Strip(parentType)}RowId FK
        // (e.g. DataStoreRowId, MsSqlConnectionRowId) = owner.RowId — version-pinned, no schema lookup.
        var parentFkRowId = StripConfigurationSuffix(typeSymbol.Name) + "RowId";

        var current = typeSymbol;
        while (current != null && current.SpecialType == SpecialType.None)
        {
            foreach (var p in current.GetMembers().OfType<IPropertySymbol>())
            {
                if (p.IsStatic || p.IsIndexer)
                    continue;
                if (!seenNames.Add(p.Name))
                    continue;

                // Typed body: the single "Configuration" property implementing IGenericConfiguration.
                // Read-only access is sufficient (GetTypedBody only reads it); never a scalar column.
                if (string.Equals(p.Name, "Configuration", System.StringComparison.Ordinal) &&
                    ImplementsGenericConfiguration(p.Type))
                {
                    if (p.GetMethod != null && p.GetMethod.DeclaredAccessibility == Accessibility.Public)
                        typedBodyTypeFqn = p.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                    continue;
                }

                var hasPublicSetter = p.SetMethod != null && p.SetMethod.DeclaredAccessibility == Accessibility.Public;

                // Property-collection (KVP) child: IDictionary<string, string> / <string, string?>.
                if (TryGetStringDictionary(p.Type, out var kvpValueNullable))
                {
                    if (hasPublicSetter)
                        children.Add(new ChildInfo(ChildKind.PropertyCollection, p.Name,
                            p.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
                            null, null, parentFkName, false, kvpValueNullable,
                            parentFkRowId, ResolveChildContainerName(p)));
                    continue;
                }

                // Typed-list child: a collection whose element implements IGenericConfiguration.
                if (IsCollectionType(p.Type))
                {
                    var elem = GetEnumerableElementType(p.Type);
                    if (hasPublicSetter && elem != null && ImplementsGenericConfiguration(elem))
                    {
                        children.Add(new ChildInfo(ChildKind.TypedList, p.Name,
                            p.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
                            elem.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
                            elem.Name,
                            parentFkName,
                            ChildHasFkSetter(elem, parentFkName),
                            false,
                            parentFkRowId,
                            string.Empty));
                    }
                    // Collections never become scalar columns (cannot bind as SQL parameters).
                    continue;
                }

                // Scalar column property.
                if (hasPublicSetter)
                {
                    allProperties.Add(new PropertyInfo(
                        p.Name,
                        ResolveColumnName(p),
                        p.Type.ToDisplayString(displayFormat),
                        p.Type.SpecialType,
                        p.Type.NullableAnnotation == NullableAnnotation.Annotated,
                        p.Type.IsValueType,
                        p.SetMethod!.IsInitOnly));
                }
            }
            current = current.BaseType;
        }
        var properties = allProperties.ToImmutableArray();

        // Use FullyQualifiedFormat for code references (typeof, new) to avoid ambiguity,
        // but strip 'global::' for the string key used in PocoMapperBase(typeFullName, ...)
        // so it matches Type.FullName at runtime.
        var fullyQualified = typeSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

        return new TypeInfo(
            typeSymbol.Name,
            typeSymbol.ContainingNamespace?.ToDisplayString() ?? string.Empty,
            fullyQualified,
            properties,
            children.ToImmutableArray(),
            typedBodyTypeFqn,
            direction);
    }

    // Why: int enum — cannot switch on MapperDirection from Data.Abstractions in a Roslyn
    // source generator without taking a package reference that causes a circular dependency.
    // Mirror the enum values locally so the generator stays self-contained.
    // FDW017 disabled: source generators are explicitly exempt from the TypeCollection rule because
    // they compile against netstandard2.0 and cannot reference the TypeCollection infrastructure.
#pragma warning disable FDW017
    private enum MapperDirection
    {
        Input = 0,
        Output = 1,
        Both = 2,
    }

    private enum ChildKind
    {
        TypedList = 0,
        PropertyCollection = 1,
    }
#pragma warning restore FDW017

#pragma warning disable MA0051 // Source generator emits complete POCO mapper class — splitting scatters the template
    private static void GenerateMapper(SourceProductionContext context, TypeInfo typeInfo)
    {
        var safeTypeName = typeInfo.Name.Replace("<", "_").Replace(">", "_");
        // Strip global:: from the string key so it matches Type.FullName at runtime
        var typeFullName = typeInfo.FullyQualifiedName.Replace("global::", "");

        // Why: input-side methods are only emitted when Direction is Input or Both.
        // Output-only mappers have no need for DbDataReader or Dictionary materialisation;
        // including them would pull unused using statements and dead code into output assemblies.
        var emitInput = typeInfo.Direction == MapperDirection.Input || typeInfo.Direction == MapperDirection.Both;

        var inputMethods = emitInput ? $$"""

                public override IGenericResult<object> MapFromReader(
                    DbDataReader reader,
                    IStorageContainer container)
                {
                    try
                    {
                        var instance = new {{typeInfo.FullyQualifiedName}}
                        {
            {{GenerateReaderPropertyMappings(typeInfo)}}
                        };

                        return GenericResult<object>.Success(instance);
                    }
                    catch (Exception ex)
                    {
                        return GenericResult<object>.Failure(
                            global::Fdw.Data.Abstractions.Results.MapperResultCodes.MappingFailed,
                            global::Fdw.Results.ResultDetails.Create("Type", "{{typeInfo.Name}}", "Source", "reader", "Error", ex.Message));
                    }
                }

                public override IGenericResult<object> MapFromDictionary(
                    IDictionary<string, object?> data)
                {
                    try
                    {
                        var instance = new {{typeInfo.FullyQualifiedName}}
                        {
            {{GenerateDictionaryPropertyMappings(typeInfo)}}
                        };

                        return GenericResult<object>.Success(instance);
                    }
                    catch (Exception ex)
                    {
                        return GenericResult<object>.Failure(
                            global::Fdw.Data.Abstractions.Results.MapperResultCodes.MappingFailed,
                            global::Fdw.Results.ResultDetails.Create("Type", "{{typeInfo.Name}}", "Source", "dictionary", "Error", ex.Message));
                    }
                }
            """ : string.Empty;

        // Why: helper methods (GetReaderValue_*) are only needed when input mapping is emitted.
        var helperMethods = emitInput ? GenerateHelperMethods(typeInfo) : string.Empty;

        // Why: data-reader using directives are only emitted for input-side mappers.
        var readerUsings = emitInput
            ? "using System.Data.Common;\r\n"
            : string.Empty;

        var code = $$"""
            // <auto-generated/>
            #nullable enable
            #pragma warning disable CS1591 // Missing XML comment

            using System;
            using System.Collections;
            {{readerUsings}}using System.Collections.Generic;
            using Fdw.Collections.Attributes;
            using Fdw.Configuration;
            using Fdw.Data.Abstractions;
            using Fdw.Data.Abstractions.Mappers.PocoMappers;
            using Fdw.Results;

            namespace {{typeInfo.Namespace}};

            /// <summary>
            /// Generated POCO mapper for {{typeInfo.Name}}.
            /// Registered with PocoMapperCollection TypeCollection for discovery.
            /// Maps from DbDataReader and Dictionary without reflection.
            /// Direction: {{typeInfo.Direction}}.
            /// </summary>
            [TypeOption(typeof(PocoMapperCollection), "{{typeInfo.Name}}", RestrictToCurrentCompilation = true)]
            public sealed class {{safeTypeName}}PocoMapper : PocoMapperBase
            {
                public {{safeTypeName}}PocoMapper()
                    : base("{{typeFullName}}", typeof({{typeInfo.FullyQualifiedName}}))
                {
                }
            {{inputMethods}}
            {{GenerateGetPropertyNames(typeInfo)}}

            {{GenerateMapToParameters(typeInfo)}}

            {{GenerateSetValue(typeInfo)}}

            {{GenerateCascadeSurface(typeInfo)}}

            {{helperMethods}}
            }
            """;

        context.AddSource($"{safeTypeName}PocoMapper.g.cs", SourceText.From(code, Encoding.UTF8));
    }

    private static string GenerateReaderPropertyMappings(TypeInfo typeInfo)
    {
        var sb = new StringBuilder();
        var indent = "                ";

        foreach (var prop in typeInfo.Properties)
        {
            sb.AppendLine($"{indent}{prop.Name} = GetReaderValue_{SanitizeName(prop.Name)}(reader),");
        }

        return sb.ToString().TrimEnd('\r', '\n', ',');
    }

    private static string GenerateDictionaryPropertyMappings(TypeInfo typeInfo)
    {
        var sb = new StringBuilder();
        var indent = "                ";

        foreach (var prop in typeInfo.Properties)
        {
            var varName = prop.Name.ToLowerInvariant() + "Val";
            var baseType = prop.TypeName.TrimEnd('?');
            var defaultValue = GetDefaultValueExpression(prop);

            sb.AppendLine($"{indent}{prop.Name} = data.TryGetValue(\"{prop.ColumnName}\", out var {varName}) && {varName} != null ? ({baseType}){varName} : {defaultValue},");
        }

        return sb.ToString().TrimEnd('\r', '\n', ',');
    }

    private static string GenerateGetPropertyNames(TypeInfo typeInfo)
    {
        var names = string.Join(", ", typeInfo.Properties.Select(p => $"\"{p.ColumnName}\""));
        return $$"""
                    private static readonly string[] _propertyNames = new string[] { {{names}} };

                    public override global::System.Collections.Generic.IReadOnlyList<string> GetPropertyNames()
                        => _propertyNames;
            """;
    }

    private static string GenerateMapToParameters(TypeInfo typeInfo)
    {
        var sb = new StringBuilder();
        sb.AppendLine("            public override global::System.Collections.Generic.IReadOnlyDictionary<string, object?> MapToParameters(object instance)");
        sb.AppendLine("            {");
        sb.AppendLine($"                var typed = ({typeInfo.FullyQualifiedName})instance;");
        sb.AppendLine($"                return new global::System.Collections.Generic.Dictionary<string, object?>(global::System.StringComparer.Ordinal)");
        sb.AppendLine("                {");

        foreach (var prop in typeInfo.Properties)
        {
            sb.AppendLine($"                    [\"{prop.ColumnName}\"] = typed.{prop.Name},");
        }

        sb.AppendLine("                };");
        sb.AppendLine("            }");

        return sb.ToString();
    }

    // Why: reflection-free property setter by column name — the generated switch replaces
    // GetProperty(name).SetValue used by the save cascade to stamp a child's runtime-named FK column.
    private static string GenerateSetValue(TypeInfo typeInfo)
    {
        var sb = new StringBuilder();
        sb.AppendLine("            public override void SetValue(object instance, string columnName, object? value)");
        sb.AppendLine("            {");
        sb.AppendLine($"                var typed = ({typeInfo.FullyQualifiedName})instance;");
        sb.AppendLine("                switch (columnName)");
        sb.AppendLine("                {");

        foreach (var prop in typeInfo.Properties)
        {
            // Why: init-only properties can only be set in an object initializer (MapFromReader does
            // that); a post-construction SetValue cannot assign them, so they are not emitted here.
            if (prop.IsInitOnly)
                continue;
            var baseType = prop.TypeName.TrimEnd('?');
            sb.AppendLine($"                    case \"{prop.ColumnName}\": typed.{prop.Name} = ({baseType})value!; break;");
        }

        // Unknown column is a no-op (mirrors the old GetProperty(name)?.SetValue null-conditional).
        sb.AppendLine("                    default: break;");
        sb.AppendLine("                }");
        sb.AppendLine("            }");

        return sb.ToString();
    }

    // Why: emits the reflection-free cascade surface (CreateList/CreateArray/GetTypedBody/CascadeChildren).
    // Emitted unconditionally (the members are abstract on PocoMapperBase), independent of Direction.
    private static string GenerateCascadeSurface(TypeInfo t)
    {
        var fqn = t.FullyQualifiedName;
        var typedBody = t.TypedBodyTypeFqn is null
            ? "null"
            : $"(({fqn})parent).Configuration";

        var sb = new StringBuilder();

        sb.AppendLine($"            public override global::System.Collections.IList CreateList() => new global::System.Collections.Generic.List<{fqn}>();");
        sb.AppendLine();
        sb.AppendLine($"            public override global::System.Array CreateArray(int length) => new {fqn}[length];");
        sb.AppendLine();
        sb.AppendLine($"            public override global::Fdw.Configuration.IGenericConfiguration? GetTypedBody(object parent) => {typedBody};");
        sb.AppendLine();

        // Why: reflection-free mirror of GetTypedBody used by the read path to attach a composed typed
        // body. When the type has no typed-body property the setter is a no-op; otherwise it casts the
        // incoming IGenericConfiguration to the declared Configuration property type and assigns it.
        // Why: cast to the NULLABLE typed-body type — body is IGenericConfiguration? and the Configuration
        // property is nullable, so the '?' on the cast avoids CS8600 (null → non-nullable) under nullable
        // reference types. The captured FQN is non-annotated, so the '?' is appended here.
        var setTypedBody = t.TypedBodyTypeFqn is null
            ? "{ }"
            : $"=> (({fqn})parent).Configuration = ({t.TypedBodyTypeFqn}?)body;";
        sb.AppendLine($"            public override void SetTypedBody(object parent, global::Fdw.Configuration.IGenericConfiguration? body) {setTypedBody}");
        sb.AppendLine();

        const string descIface = "global::Fdw.Data.Abstractions.Mappers.PocoMappers.IChildCascadeDescriptor";

        if (t.Children.IsDefaultOrEmpty)
        {
            sb.AppendLine($"            private static readonly global::System.Collections.Generic.IReadOnlyList<{descIface}> _cascadeChildren =");
            sb.AppendLine($"                global::System.Array.Empty<{descIface}>();");
            sb.AppendLine();
            sb.AppendLine($"            public override global::System.Collections.Generic.IReadOnlyList<{descIface}> CascadeChildren => _cascadeChildren;");
            return sb.ToString();
        }

        // Descriptor array.
        sb.AppendLine($"            private static readonly global::System.Collections.Generic.IReadOnlyList<{descIface}> _cascadeChildren = new {descIface}[]");
        sb.AppendLine("            {");
        foreach (var c in t.Children)
        {
            sb.AppendLine($"                new {DescriptorClassName(c)}(),");
        }
        sb.AppendLine("            };");
        sb.AppendLine();
        sb.AppendLine($"            public override global::System.Collections.Generic.IReadOnlyList<{descIface}> CascadeChildren => _cascadeChildren;");
        sb.AppendLine();

        // Per-child descriptor classes.
        foreach (var c in t.Children)
        {
            sb.AppendLine(GenerateDescriptorClass(fqn, c, descIface));
        }

        return sb.ToString();
    }

    private static string DescriptorClassName(ChildInfo c) => $"{SanitizeName(c.BoundPropertyName)}CascadeDescriptor";

    private static string GenerateDescriptorClass(string parentFqn, ChildInfo c, string descIface)
    {
        var name = DescriptorClassName(c);
        if (c.Kind == ChildKind.PropertyCollection)
        {
            // KVP child: fetched by the consumer as KeyValueRow (a fixed type); ChildType unused.
            // Why: build a dictionary whose value-nullability matches the parent property. When the
            // property's value side is non-nullable (IDictionary<string, string>), the loaded values
            // are copied with the null-forgiving operator — a compile-time assertion, not a runtime
            // fallback (no substitute value is introduced).
            var valType = c.KvpValueNullable ? "string?" : "string";
            var nullForgive = c.KvpValueNullable ? string.Empty : "!";
            return $$"""
                        private sealed class {{name}} : {{descIface}}
                        {
                            public string BoundPropertyName => "{{c.BoundPropertyName}}";
                            public global::System.Type ChildType => typeof(object);
                            public string ChildTypeName => "";
                            public bool IsPropertyCollection => true;
                            public string ChildForeignKeyColumn => "{{c.PhysicalFkColumn}}";
                            public string ChildContainerName => "{{c.ChildContainerName}}";
                            public global::System.Collections.IEnumerable? GetCollection(object parent) => null;
                            public void SetCollection(object parent, object? collection) { }
                            public void FillDictionary(object parent, global::System.Collections.Generic.IDictionary<string, string?> values)
                            {
                                var target = new global::System.Collections.Generic.Dictionary<string, {{valType}}>(values.Count, global::System.StringComparer.Ordinal);
                                foreach (var kv in values)
                                {
                                    target[kv.Key] = kv.Value{{nullForgive}};
                                }
                                (({{parentFqn}})parent).{{c.BoundPropertyName}} = target;
                            }
                            public global::System.Collections.Generic.IReadOnlyDictionary<string, string?>? ReadDictionary(object parent)
                            {
                                var source = (({{parentFqn}})parent).{{c.BoundPropertyName}};
                                if (source is null) return null;
                                var result = new global::System.Collections.Generic.Dictionary<string, string?>(source.Count, global::System.StringComparer.Ordinal);
                                foreach (var kv in source) { result[kv.Key] = kv.Value; }
                                return result;
                            }
                        }
                """;
        }

        // Typed-list child.
        return $$"""
                    private sealed class {{name}} : {{descIface}}
                    {
                        public string BoundPropertyName => "{{c.BoundPropertyName}}";
                        public global::System.Type ChildType => typeof({{c.ElementFqn}});
                        public string ChildTypeName => "{{c.ElementShortName}}";
                        public bool IsPropertyCollection => false;
                        public string ChildForeignKeyColumn => "{{c.PhysicalFkColumn}}";
                        public string ChildContainerName => "";
                        public global::System.Collections.IEnumerable? GetCollection(object parent) => (({{parentFqn}})parent).{{c.BoundPropertyName}} as global::System.Collections.IEnumerable;
                        public void SetCollection(object parent, object? collection) => (({{parentFqn}})parent).{{c.BoundPropertyName}} = ({{c.PropertyTypeFqn}})collection!;
                        public void FillDictionary(object parent, global::System.Collections.Generic.IDictionary<string, string?> values) { }
                        public global::System.Collections.Generic.IReadOnlyDictionary<string, string?>? ReadDictionary(object parent) => null;
                    }
            """;
    }

    private static string GenerateHelperMethods(TypeInfo typeInfo)
    {
        var sb = new StringBuilder();

        foreach (var prop in typeInfo.Properties)
        {
            var readerMethod = GetReaderMethod(prop.SpecialType, prop.TypeName);
            var defaultValue = GetDefaultValueExpression(prop);

            sb.AppendLine();
            sb.AppendLine($"        private static {prop.TypeName} GetReaderValue_{SanitizeName(prop.Name)}(DbDataReader reader)");
            sb.AppendLine("        {");
            sb.AppendLine("            try");
            sb.AppendLine("            {");
            sb.AppendLine($"                var ordinal = reader.GetOrdinal(\"{prop.ColumnName}\");");
            sb.AppendLine($"                if (reader.IsDBNull(ordinal)) return {defaultValue};");
            sb.AppendLine($"                return reader.{readerMethod}(ordinal);");
            sb.AppendLine("            }");
            sb.AppendLine("            catch (IndexOutOfRangeException)");
            sb.AppendLine("            {");
            sb.AppendLine($"                return {defaultValue};");
            sb.AppendLine("            }");
            sb.AppendLine("        }");
        }

        return sb.ToString();
    }

    // Exhaustive type mapping for DbDataReader methods
#pragma warning disable FDW006, FDW007, FDW018 // External Roslyn SpecialType enum — cannot convert to TypeCollection
    private static string GetReaderMethod(SpecialType specialType, string fullTypeName)
    {
        var baseType = fullTypeName.TrimEnd('?');

        return specialType switch
        {
            SpecialType.System_Boolean => "GetBoolean",
            SpecialType.System_Byte => "GetByte",
            SpecialType.System_Int16 => "GetInt16",
            SpecialType.System_Int32 => "GetInt32",
            SpecialType.System_Int64 => "GetInt64",
            SpecialType.System_Decimal => "GetDecimal",
            SpecialType.System_Double => "GetDouble",
            SpecialType.System_Single => "GetFloat",
            SpecialType.System_String => "GetString",
            SpecialType.System_DateTime => "GetDateTime",
            _ => baseType switch
            {
                "global::System.Guid" => "GetGuid",
                _ => $"GetFieldValue<{baseType.Replace("global::", "")}>"
            }
        };
    }
#pragma warning restore FDW006, FDW007, FDW018

    /// <summary>
    /// Gets the appropriate default value expression for a property type.
    /// For value types, returns default (no null issues).
    /// For nullable reference types, returns default (null is allowed).
    /// For non-nullable strings, returns string.Empty.
    /// For other non-nullable reference types, returns default! to suppress CS8601/CS8603.
    /// </summary>
    private static string GetDefaultValueExpression(PropertyInfo prop)
    {
        // Value types always use default (no null issues)
        if (prop.IsValueType)
        {
            return "default";
        }

        // Nullable reference types use default (which is null, but that's allowed)
        if (prop.IsNullable)
        {
            return "default";
        }

        // Non-nullable string -> use string.Empty
        if (prop.SpecialType == SpecialType.System_String)
        {
            return "string.Empty";
        }

        // Non-nullable reference types (collections, custom classes, etc.)
        // Use default! to indicate intentional null assignment when DB value is null/missing.
        // The POCO should have a default initializer for these properties.
        return "default!";
    }

    /// <summary>
    /// Returns true if the type is a collection (implements IEnumerable&lt;T&gt; or is an array),
    /// excluding string which is IEnumerable&lt;char&gt; but maps to SQL nvarchar directly.
    /// Why: Collection types (List&lt;string&gt;, IList&lt;T&gt;, etc.) cannot be passed as SQL parameters
    /// and have no standard SQL type mapping. They are excluded from generated scalar mappers so that
    /// MsSqlConfigurationSaveTranslator does not attempt to bind them as command parameters.
    /// </summary>
    private static bool IsCollectionType(ITypeSymbol type)
    {
        // String is IEnumerable<char> but is a valid scalar SQL type — never exclude it
        if (type.SpecialType == SpecialType.System_String)
            return false;

        // Arrays (T[]) are collection types
        if (type.TypeKind == TypeKind.Array)
            return true;

        // Check if the type implements IEnumerable<T>
        foreach (var iface in type.AllInterfaces)
        {
            if (iface.OriginalDefinition.SpecialType == SpecialType.System_Collections_Generic_IEnumerable_T)
                return true;
        }

        return false;
    }

    // Why: detects the typed-body / typed-list-child element types so the cascade descriptor can be
    // emitted. A type "implements IGenericConfiguration" if it (or a base/interface) is that interface.
    private static bool ImplementsGenericConfiguration(ITypeSymbol type)
    {
        if (IsGenericConfiguration(type))
            return true;
        foreach (var iface in type.AllInterfaces)
        {
            if (IsGenericConfiguration(iface))
                return true;
        }
        return false;
    }

    private static bool IsGenericConfiguration(ITypeSymbol type)
        => string.Equals(type.ToDisplayString(), GenericConfigurationFullName, StringComparison.Ordinal);

    // Why: extracts X from List<X>/IEnumerable<X>/X[] so the descriptor knows the child element type.
    private static ITypeSymbol? GetEnumerableElementType(ITypeSymbol type)
    {
        if (type is IArrayTypeSymbol array)
            return array.ElementType;

        foreach (var iface in type.AllInterfaces)
        {
            if (iface.OriginalDefinition.SpecialType == SpecialType.System_Collections_Generic_IEnumerable_T &&
                iface is INamedTypeSymbol named &&
                named.TypeArguments.Length == 1)
            {
                return named.TypeArguments[0];
            }
        }

        // The type itself may be the closed IEnumerable<T>.
        if (type is INamedTypeSymbol self &&
            self.OriginalDefinition.SpecialType == SpecialType.System_Collections_Generic_IEnumerable_T &&
            self.TypeArguments.Length == 1)
        {
            return self.TypeArguments[0];
        }

        return null;
    }

    // Why: detects a property-collection (KVP) child — IDictionary<string, string> or
    // IDictionary<string, string?> — and reports whether the value side is nullable so the generated
    // FillDictionary builds a dictionary whose value-nullability matches the parent property.
    private static bool TryGetStringDictionary(ITypeSymbol type, out bool valueNullable)
    {
        valueNullable = false;

        static bool IsStringStringDictionary(INamedTypeSymbol named) =>
            named.OriginalDefinition.ToDisplayString().StartsWith("System.Collections.Generic.IDictionary<", StringComparison.Ordinal) &&
            named.TypeArguments.Length == 2 &&
            named.TypeArguments[0].SpecialType == SpecialType.System_String &&
            named.TypeArguments[1].SpecialType == SpecialType.System_String;

        if (type is INamedTypeSymbol self && IsStringStringDictionary(self))
        {
            valueNullable = self.TypeArguments[1].NullableAnnotation == NullableAnnotation.Annotated;
            return true;
        }

        foreach (var iface in type.AllInterfaces)
        {
            if (IsStringStringDictionary(iface))
            {
                valueNullable = iface.TypeArguments[1].NullableAnnotation == NullableAnnotation.Annotated;
                return true;
            }
        }
        return false;
    }

    // Why: the cascade stamps domainConfigurationId onto the child's {Strip(parent)}Id property; only emit the
    // typed assignment when the child actually declares a public-settable Guid property of that name.
    private static bool ChildHasFkSetter(ITypeSymbol childType, string fkName)
    {
        var current = childType;
        while (current != null && current.SpecialType == SpecialType.None)
        {
            foreach (var p in current.GetMembers().OfType<IPropertySymbol>())
            {
                if (string.Equals(p.Name, fkName, StringComparison.Ordinal) &&
                    p.SetMethod != null &&
                    p.SetMethod.DeclaredAccessibility == Accessibility.Public &&
                    p.Type.SpecialType == SpecialType.None &&
                    string.Equals(p.Type.ToDisplayString(), "System.Guid", StringComparison.Ordinal))
                {
                    return true;
                }
            }
            current = current.BaseType;
        }
        return false;
    }

    // Why: mirrors ImplementationConfigurationProviderBase.StripConfigurationSuffix so the FK column name the
    // generator resolves matches the runtime cascade's logical FK ({Strip(parentType)}Id).
    private static string StripConfigurationSuffix(string typeName)
    {
        const string suffix = "Configuration";
        return typeName.EndsWith(suffix, StringComparison.Ordinal) && typeName.Length > suffix.Length
            ? typeName.Substring(0, typeName.Length - suffix.Length)
            : typeName;
    }

    private static string SanitizeName(string name)
    {
        return name.Replace("_", "").Replace(".", "").Replace("<", "").Replace(">", "");
    }

    private readonly record struct TypeInfo(
        string Name,
        string Namespace,
        string FullyQualifiedName,
        ImmutableArray<PropertyInfo> Properties,
        ImmutableArray<ChildInfo> Children,
        string? TypedBodyTypeFqn,
        MapperDirection Direction);

    private readonly record struct PropertyInfo(
        string Name,
        string ColumnName,
        string TypeName,
        SpecialType SpecialType,
        bool IsNullable,
        bool IsValueType,
        bool IsInitOnly);

    private readonly record struct ChildInfo(
        ChildKind Kind,
        string BoundPropertyName,
        string PropertyTypeFqn,
        string? ElementFqn,
        string? ElementShortName,
        string FkPropertyName,
        bool HasFkSetter,
        bool KvpValueNullable,
        string PhysicalFkColumn,
        string ChildContainerName);

    // Why: Property name == column name by default. When a POCO property's SQL column name
    // differs, the author decorates with [Column("SomeOtherName")] from
    // System.ComponentModel.DataAnnotations.Schema. The generator picks up the override here
    // so that reader.GetOrdinal(), GetPropertyNames(), MapToParameters keys, and the dictionary
    // mapping path all use the SQL column name, not the C# property name.
    private const string ColumnAttributeFullName = "System.ComponentModel.DataAnnotations.Schema.ColumnAttribute";
    private const string ChildTableAttributeFullName = "Fdw.Data.ConfigurationChildTableAttribute";

    // Why: a KVP property-collection child's table name is not derivable from the property/owner type
    // (e.g. "Properties" -> conn.MsSqlConnectionAuthentication), so the author declares it with
    // [ConfigurationChildTable("...")]. Emitted onto the descriptor's ChildContainerName so the read
    // cascade can query it with no schema lookup. Empty string when absent — the read then skips the
    // child (an unwired KVP bag) rather than guessing a table (NO FALLBACKS).
    private static string ResolveChildContainerName(IPropertySymbol prop)
    {
        foreach (var attr in prop.GetAttributes())
        {
            if (attr.AttributeClass is null)
                continue;
            if (!string.Equals(attr.AttributeClass.ToDisplayString(), ChildTableAttributeFullName, StringComparison.Ordinal))
                continue;
            if (attr.ConstructorArguments.Length == 0)
                continue;
            if (attr.ConstructorArguments[0].Value is string name && !string.IsNullOrWhiteSpace(name))
                return name;
        }
        return string.Empty;
    }

    private static string ResolveColumnName(IPropertySymbol prop)
    {
        foreach (var attr in prop.GetAttributes())
        {
            if (attr.AttributeClass is null)
                continue;
            if (!string.Equals(attr.AttributeClass.ToDisplayString(), ColumnAttributeFullName, StringComparison.Ordinal))
                continue;
            if (attr.ConstructorArguments.Length == 0)
                continue;
            var arg = attr.ConstructorArguments[0];
            if (arg.Value is string explicitName && !string.IsNullOrWhiteSpace(explicitName))
                return explicitName;
        }
        return prop.Name;
    }
}
